// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_QUANTIZEDCHUNKT_NCB_NIDL_H_
#define FLATBUFFERS_GENERATED_QUANTIZEDCHUNKT_NCB_NIDL_H_

#include <contrib/libs/flatbuffers/include/flatbuffers/flatbuffers.h>

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace NCB {
namespace NIdl {

struct TQuantizedFeatureChunk;
struct TQuantizedFeatureChunkBuilder;
struct TQuantizedFeatureChunkT;

enum EBitsPerDocumentFeature : uint8_t {
  EBitsPerDocumentFeature_BPDF_UKNOWN = 0,
  EBitsPerDocumentFeature_BPDF_1 = 1,
  EBitsPerDocumentFeature_BPDF_2 = 2,
  EBitsPerDocumentFeature_BPDF_4 = 4,
  EBitsPerDocumentFeature_BPDF_8 = 8,
  EBitsPerDocumentFeature_BPDF_16 = 16,
  EBitsPerDocumentFeature_BPDF_32 = 32,
  EBitsPerDocumentFeature_BPDF_64 = 64,
  EBitsPerDocumentFeature_MIN = EBitsPerDocumentFeature_BPDF_UKNOWN,
  EBitsPerDocumentFeature_MAX = EBitsPerDocumentFeature_BPDF_64
};

inline const EBitsPerDocumentFeature (&EnumValuesEBitsPerDocumentFeature())[8] {
  static const EBitsPerDocumentFeature values[] = {
    EBitsPerDocumentFeature_BPDF_UKNOWN,
    EBitsPerDocumentFeature_BPDF_1,
    EBitsPerDocumentFeature_BPDF_2,
    EBitsPerDocumentFeature_BPDF_4,
    EBitsPerDocumentFeature_BPDF_8,
    EBitsPerDocumentFeature_BPDF_16,
    EBitsPerDocumentFeature_BPDF_32,
    EBitsPerDocumentFeature_BPDF_64
  };
  return values;
}

inline const char *EnumNameEBitsPerDocumentFeature(EBitsPerDocumentFeature e) {
  switch (e) {
    case EBitsPerDocumentFeature_BPDF_UKNOWN: return "BPDF_UKNOWN";
    case EBitsPerDocumentFeature_BPDF_1: return "BPDF_1";
    case EBitsPerDocumentFeature_BPDF_2: return "BPDF_2";
    case EBitsPerDocumentFeature_BPDF_4: return "BPDF_4";
    case EBitsPerDocumentFeature_BPDF_8: return "BPDF_8";
    case EBitsPerDocumentFeature_BPDF_16: return "BPDF_16";
    case EBitsPerDocumentFeature_BPDF_32: return "BPDF_32";
    case EBitsPerDocumentFeature_BPDF_64: return "BPDF_64";
    default: return "";
  }
}

struct TQuantizedFeatureChunkT : public ::flatbuffers::NativeTable {
  typedef TQuantizedFeatureChunk TableType;
  NCB::NIdl::EBitsPerDocumentFeature BitsPerDocument = NCB::NIdl::EBitsPerDocumentFeature_BPDF_UKNOWN;
  std::vector<uint8_t> Quants{};
};

struct TQuantizedFeatureChunk FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TQuantizedFeatureChunkT NativeTableType;
  typedef TQuantizedFeatureChunkBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BITSPERDOCUMENT = 4,
    VT_QUANTS = 6
  };
  NCB::NIdl::EBitsPerDocumentFeature BitsPerDocument() const {
    return static_cast<NCB::NIdl::EBitsPerDocumentFeature>(GetField<uint8_t>(VT_BITSPERDOCUMENT, 0));
  }
  bool mutate_BitsPerDocument(NCB::NIdl::EBitsPerDocumentFeature _BitsPerDocument = static_cast<NCB::NIdl::EBitsPerDocumentFeature>(0)) {
    return SetField<uint8_t>(VT_BITSPERDOCUMENT, static_cast<uint8_t>(_BitsPerDocument), 0);
  }
  const ::flatbuffers::Vector<uint8_t> *Quants() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_QUANTS);
  }
  ::flatbuffers::Vector<uint8_t> *mutable_Quants() {
    return GetPointer<::flatbuffers::Vector<uint8_t> *>(VT_QUANTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_BITSPERDOCUMENT, 1) &&
           VerifyOffset(verifier, VT_QUANTS) &&
           verifier.VerifyVector(Quants()) &&
           verifier.EndTable();
  }
  TQuantizedFeatureChunkT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TQuantizedFeatureChunkT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TQuantizedFeatureChunk> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TQuantizedFeatureChunkT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TQuantizedFeatureChunkBuilder {
  typedef TQuantizedFeatureChunk Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_BitsPerDocument(NCB::NIdl::EBitsPerDocumentFeature BitsPerDocument) {
    fbb_.AddElement<uint8_t>(TQuantizedFeatureChunk::VT_BITSPERDOCUMENT, static_cast<uint8_t>(BitsPerDocument), 0);
  }
  void add_Quants(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Quants) {
    fbb_.AddOffset(TQuantizedFeatureChunk::VT_QUANTS, Quants);
  }
  explicit TQuantizedFeatureChunkBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TQuantizedFeatureChunk> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TQuantizedFeatureChunk>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TQuantizedFeatureChunk> CreateTQuantizedFeatureChunk(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NCB::NIdl::EBitsPerDocumentFeature BitsPerDocument = NCB::NIdl::EBitsPerDocumentFeature_BPDF_UKNOWN,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> Quants = 0) {
  TQuantizedFeatureChunkBuilder builder_(_fbb);
  builder_.add_Quants(Quants);
  builder_.add_BitsPerDocument(BitsPerDocument);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TQuantizedFeatureChunk> CreateTQuantizedFeatureChunkDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    NCB::NIdl::EBitsPerDocumentFeature BitsPerDocument = NCB::NIdl::EBitsPerDocumentFeature_BPDF_UKNOWN,
    const std::vector<uint8_t> *Quants = nullptr) {
  auto Quants__ = Quants ? _fbb.CreateVector<uint8_t>(*Quants) : 0;
  return NCB::NIdl::CreateTQuantizedFeatureChunk(
      _fbb,
      BitsPerDocument,
      Quants__);
}

::flatbuffers::Offset<TQuantizedFeatureChunk> CreateTQuantizedFeatureChunk(::flatbuffers::FlatBufferBuilder &_fbb, const TQuantizedFeatureChunkT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline TQuantizedFeatureChunkT *TQuantizedFeatureChunk::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<TQuantizedFeatureChunkT>(new TQuantizedFeatureChunkT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TQuantizedFeatureChunk::UnPackTo(TQuantizedFeatureChunkT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = BitsPerDocument(); _o->BitsPerDocument = _e; }
  { auto _e = Quants(); if (_e) { _o->Quants.resize(_e->size()); std::copy(_e->begin(), _e->end(), _o->Quants.begin()); } }
}

inline ::flatbuffers::Offset<TQuantizedFeatureChunk> TQuantizedFeatureChunk::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TQuantizedFeatureChunkT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateTQuantizedFeatureChunk(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TQuantizedFeatureChunk> CreateTQuantizedFeatureChunk(::flatbuffers::FlatBufferBuilder &_fbb, const TQuantizedFeatureChunkT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TQuantizedFeatureChunkT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _BitsPerDocument = _o->BitsPerDocument;
  auto _Quants = _o->Quants.size() ? _fbb.CreateVector(_o->Quants) : 0;
  return NCB::NIdl::CreateTQuantizedFeatureChunk(
      _fbb,
      _BitsPerDocument,
      _Quants);
}

}  // namespace NIdl
}  // namespace NCB

#endif  // FLATBUFFERS_GENERATED_QUANTIZEDCHUNKT_NCB_NIDL_H_
