// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/tensorboard/event.proto

#include "contrib/libs/tensorboard/event.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include <google/protobuf/messagext.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace tensorboard {
PROTOBUF_CONSTEXPR Event::Event(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.wall_time_)*/ 0

  , /*decltype(_impl_.step_)*/ ::arc_i64{0}

  , /*decltype(_impl_.what_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct EventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EventDefaultTypeInternal() {}
  union {
    Event _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EventDefaultTypeInternal _Event_default_instance_;
PROTOBUF_CONSTEXPR LogMessage::LogMessage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.level_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct LogMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR LogMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~LogMessageDefaultTypeInternal() {}
  union {
    LogMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 LogMessageDefaultTypeInternal _LogMessage_default_instance_;
PROTOBUF_CONSTEXPR SessionLog::SessionLog(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.checkpoint_path_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.msg_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.status_)*/ 0

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SessionLogDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SessionLogDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SessionLogDefaultTypeInternal() {}
  union {
    SessionLog _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SessionLogDefaultTypeInternal _SessionLog_default_instance_;
PROTOBUF_CONSTEXPR TaggedRunMetadata::TaggedRunMetadata(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.tag_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.run_metadata_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TaggedRunMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TaggedRunMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TaggedRunMetadataDefaultTypeInternal() {}
  union {
    TaggedRunMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TaggedRunMetadataDefaultTypeInternal _TaggedRunMetadata_default_instance_;
}  // namespace tensorboard
static ::_pb::Metadata file_level_metadata_contrib_2flibs_2ftensorboard_2fevent_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2fevent_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_contrib_2flibs_2ftensorboard_2fevent_2eproto = nullptr;
const ::arc_ui32 TableStruct_contrib_2flibs_2ftensorboard_2fevent_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::Event, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::tensorboard::Event, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::Event, _impl_.wall_time_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::Event, _impl_.step_),
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::tensorboard::Event, _impl_.what_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::LogMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::LogMessage, _impl_.level_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::LogMessage, _impl_.message_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::SessionLog, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::SessionLog, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::SessionLog, _impl_.checkpoint_path_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::SessionLog, _impl_.msg_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::TaggedRunMetadata, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::TaggedRunMetadata, _impl_.tag_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::TaggedRunMetadata, _impl_.run_metadata_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::tensorboard::Event)},
        { 18, -1, -1, sizeof(::tensorboard::LogMessage)},
        { 28, -1, -1, sizeof(::tensorboard::SessionLog)},
        { 39, -1, -1, sizeof(::tensorboard::TaggedRunMetadata)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::tensorboard::_Event_default_instance_._instance,
    &::tensorboard::_LogMessage_default_instance_._instance,
    &::tensorboard::_SessionLog_default_instance_._instance,
    &::tensorboard::_TaggedRunMetadata_default_instance_._instance,
};
const char descriptor_table_protodef_contrib_2flibs_2ftensorboard_2fevent_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n$contrib/libs/tensorboard/event.proto\022\013"
    "tensorboard\032&contrib/libs/tensorboard/su"
    "mmary.proto\"\277\002\n\005Event\022\021\n\twall_time\030\001 \001(\001"
    "\022\014\n\004step\030\002 \001(\003\022\026\n\014file_version\030\003 \001(\tH\000\022\023"
    "\n\tgraph_def\030\004 \001(\014H\000\022\'\n\007summary\030\005 \001(\0132\024.t"
    "ensorboard.SummaryH\000\022.\n\013log_message\030\006 \001("
    "\0132\027.tensorboard.LogMessageH\000\022.\n\013session_"
    "log\030\007 \001(\0132\027.tensorboard.SessionLogH\000\022=\n\023"
    "tagged_run_metadata\030\010 \001(\0132\036.tensorboard."
    "TaggedRunMetadataH\000\022\030\n\016meta_graph_def\030\t "
    "\001(\014H\000B\006\n\004what\"\226\001\n\nLogMessage\022,\n\005level\030\001 "
    "\001(\0162\035.tensorboard.LogMessage.Level\022\017\n\007me"
    "ssage\030\002 \001(\t\"I\n\005Level\022\013\n\007UNKNOWN\020\000\022\t\n\005DEB"
    "UG\020\n\022\010\n\004INFO\020\024\022\010\n\004WARN\020\036\022\t\n\005ERROR\020(\022\t\n\005F"
    "ATAL\0202\"\267\001\n\nSessionLog\0225\n\006status\030\001 \001(\0162%."
    "tensorboard.SessionLog.SessionStatus\022\027\n\017"
    "checkpoint_path\030\002 \001(\t\022\013\n\003msg\030\003 \001(\t\"L\n\rSe"
    "ssionStatus\022\026\n\022STATUS_UNSPECIFIED\020\000\022\t\n\005S"
    "TART\020\001\022\010\n\004STOP\020\002\022\016\n\nCHECKPOINT\020\003\"6\n\021Tagg"
    "edRunMetadata\022\013\n\003tag\030\001 \001(\t\022\024\n\014run_metada"
    "ta\030\002 \001(\014B\'\n\023org.tensorflow.utilB\013EventPr"
    "otosP\001\370\001\001b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_deps[1] =
    {
        &::descriptor_table_contrib_2flibs_2ftensorboard_2fsummary_2eproto,
};
static ::y_absl::once_flag descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto = {
    false,
    false,
    857,
    descriptor_table_protodef_contrib_2flibs_2ftensorboard_2fevent_2eproto,
    "contrib/libs/tensorboard/event.proto",
    &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_once,
    descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_contrib_2flibs_2ftensorboard_2fevent_2eproto::offsets,
    file_level_metadata_contrib_2flibs_2ftensorboard_2fevent_2eproto,
    file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2fevent_2eproto,
    file_level_service_descriptors_contrib_2flibs_2ftensorboard_2fevent_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_getter() {
  return &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_contrib_2flibs_2ftensorboard_2fevent_2eproto(&descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto);
namespace tensorboard {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogMessage_Level_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto);
  return file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2fevent_2eproto[0];
}
bool LogMessage_Level_IsValid(int value) {
  switch (value) {
    case 0:
    case 10:
    case 20:
    case 30:
    case 40:
    case 50:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr LogMessage_Level LogMessage::UNKNOWN;
constexpr LogMessage_Level LogMessage::DEBUG;
constexpr LogMessage_Level LogMessage::INFO;
constexpr LogMessage_Level LogMessage::WARN;
constexpr LogMessage_Level LogMessage::ERROR;
constexpr LogMessage_Level LogMessage::FATAL;
constexpr LogMessage_Level LogMessage::Level_MIN;
constexpr LogMessage_Level LogMessage::Level_MAX;
constexpr int LogMessage::Level_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SessionLog_SessionStatus_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto);
  return file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2fevent_2eproto[1];
}
bool SessionLog_SessionStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr SessionLog_SessionStatus SessionLog::STATUS_UNSPECIFIED;
constexpr SessionLog_SessionStatus SessionLog::START;
constexpr SessionLog_SessionStatus SessionLog::STOP;
constexpr SessionLog_SessionStatus SessionLog::CHECKPOINT;
constexpr SessionLog_SessionStatus SessionLog::SessionStatus_MIN;
constexpr SessionLog_SessionStatus SessionLog::SessionStatus_MAX;
constexpr int SessionLog::SessionStatus_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Event::_Internal {
 public:
  static constexpr ::arc_i32 kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::tensorboard::Event, _impl_._oneof_case_);
  static const ::tensorboard::Summary& summary(const Event* msg);
  static const ::tensorboard::LogMessage& log_message(const Event* msg);
  static const ::tensorboard::SessionLog& session_log(const Event* msg);
  static const ::tensorboard::TaggedRunMetadata& tagged_run_metadata(const Event* msg);
};

const ::tensorboard::Summary&
Event::_Internal::summary(const Event* msg) {
  return *msg->_impl_.what_.summary_;
}
const ::tensorboard::LogMessage&
Event::_Internal::log_message(const Event* msg) {
  return *msg->_impl_.what_.log_message_;
}
const ::tensorboard::SessionLog&
Event::_Internal::session_log(const Event* msg) {
  return *msg->_impl_.what_.session_log_;
}
const ::tensorboard::TaggedRunMetadata&
Event::_Internal::tagged_run_metadata(const Event* msg) {
  return *msg->_impl_.what_.tagged_run_metadata_;
}
void Event::set_allocated_summary(::tensorboard::Summary* summary) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_what();
  if (summary) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(summary));
    if (message_arena != submessage_arena) {
      summary = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, summary, submessage_arena);
    }
    set_has_summary();
    _impl_.what_.summary_ = summary;
  }
  // @@protoc_insertion_point(field_set_allocated:tensorboard.Event.summary)
}
void Event::clear_summary() {
  if (what_case() == kSummary) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.what_.summary_;
    }
    clear_has_what();
  }
}
void Event::set_allocated_log_message(::tensorboard::LogMessage* log_message) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_what();
  if (log_message) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(log_message);
    if (message_arena != submessage_arena) {
      log_message = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, log_message, submessage_arena);
    }
    set_has_log_message();
    _impl_.what_.log_message_ = log_message;
  }
  // @@protoc_insertion_point(field_set_allocated:tensorboard.Event.log_message)
}
void Event::set_allocated_session_log(::tensorboard::SessionLog* session_log) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_what();
  if (session_log) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(session_log);
    if (message_arena != submessage_arena) {
      session_log = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, session_log, submessage_arena);
    }
    set_has_session_log();
    _impl_.what_.session_log_ = session_log;
  }
  // @@protoc_insertion_point(field_set_allocated:tensorboard.Event.session_log)
}
void Event::set_allocated_tagged_run_metadata(::tensorboard::TaggedRunMetadata* tagged_run_metadata) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_what();
  if (tagged_run_metadata) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(tagged_run_metadata);
    if (message_arena != submessage_arena) {
      tagged_run_metadata = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, tagged_run_metadata, submessage_arena);
    }
    set_has_tagged_run_metadata();
    _impl_.what_.tagged_run_metadata_ = tagged_run_metadata;
  }
  // @@protoc_insertion_point(field_set_allocated:tensorboard.Event.tagged_run_metadata)
}
Event::Event(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.Event)
}
Event::Event(const Event& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Event* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.wall_time_) {}

    , decltype(_impl_.step_) {}

    , decltype(_impl_.what_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.wall_time_, &from._impl_.wall_time_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.step_) -
    reinterpret_cast<char*>(&_impl_.wall_time_)) + sizeof(_impl_.step_));
  clear_has_what();
  switch (from.what_case()) {
    case kFileVersion: {
      _this->_internal_set_file_version(from._internal_file_version());
      break;
    }
    case kGraphDef: {
      _this->_internal_set_graph_def(from._internal_graph_def());
      break;
    }
    case kSummary: {
      _this->_internal_mutable_summary()->::tensorboard::Summary::MergeFrom(
          from._internal_summary());
      break;
    }
    case kLogMessage: {
      _this->_internal_mutable_log_message()->::tensorboard::LogMessage::MergeFrom(
          from._internal_log_message());
      break;
    }
    case kSessionLog: {
      _this->_internal_mutable_session_log()->::tensorboard::SessionLog::MergeFrom(
          from._internal_session_log());
      break;
    }
    case kTaggedRunMetadata: {
      _this->_internal_mutable_tagged_run_metadata()->::tensorboard::TaggedRunMetadata::MergeFrom(
          from._internal_tagged_run_metadata());
      break;
    }
    case kMetaGraphDef: {
      _this->_internal_set_meta_graph_def(from._internal_meta_graph_def());
      break;
    }
    case WHAT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:tensorboard.Event)
}

inline void Event::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.wall_time_) { 0 }

    , decltype(_impl_.step_) { ::arc_i64{0} }

    , decltype(_impl_.what_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_what();
}

Event::~Event() {
  // @@protoc_insertion_point(destructor:tensorboard.Event)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Event::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_what()) {
    clear_what();
  }
}

void Event::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Event::clear_what() {
// @@protoc_insertion_point(one_of_clear_start:tensorboard.Event)
  switch (what_case()) {
    case kFileVersion: {
      _impl_.what_.file_version_.Destroy();
      break;
    }
    case kGraphDef: {
      _impl_.what_.graph_def_.Destroy();
      break;
    }
    case kSummary: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.what_.summary_;
      }
      break;
    }
    case kLogMessage: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.what_.log_message_;
      }
      break;
    }
    case kSessionLog: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.what_.session_log_;
      }
      break;
    }
    case kTaggedRunMetadata: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.what_.tagged_run_metadata_;
      }
      break;
    }
    case kMetaGraphDef: {
      _impl_.what_.meta_graph_def_.Destroy();
      break;
    }
    case WHAT_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = WHAT_NOT_SET;
}


void Event::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.Event)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.wall_time_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.step_) -
      reinterpret_cast<char*>(&_impl_.wall_time_)) + sizeof(_impl_.step_));
  clear_what();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Event::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // double wall_time = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 9)) {
          _impl_.wall_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // int64 step = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _impl_.step_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // string file_version = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_file_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.Event.file_version"));
        } else {
          goto handle_unusual;
        }
        continue;
      // bytes graph_def = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_graph_def();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .tensorboard.Summary summary = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_summary(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .tensorboard.LogMessage log_message = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_log_message(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .tensorboard.SessionLog session_log = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_session_log(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_tagged_run_metadata(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // bytes meta_graph_def = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_meta_graph_def();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Event::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.Event)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double wall_time = 1;
  static_assert(sizeof(::arc_ui64) == sizeof(double), "Code assumes ::arc_ui64 and double are the same size.");
  double tmp_wall_time = this->_internal_wall_time();
  ::arc_ui64 raw_wall_time;
  memcpy(&raw_wall_time, &tmp_wall_time, sizeof(tmp_wall_time));
  if (raw_wall_time != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(
        1, this->_internal_wall_time(), target);
  }

  // int64 step = 2;
  if (this->_internal_step() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        2, this->_internal_step(), target);
  }

  // string file_version = 3;
  if (what_case() == kFileVersion) {
    const TProtoStringType& _s = this->_internal_file_version();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.Event.file_version");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // bytes graph_def = 4;
  if (what_case() == kGraphDef) {
    const TProtoStringType& _s = this->_internal_graph_def();
    target = stream->WriteBytesMaybeAliased(4, _s, target);
  }

  // .tensorboard.Summary summary = 5;
  if (what_case() == kSummary) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::summary(this),
        _Internal::summary(this).GetCachedSize(), target, stream);
  }

  // .tensorboard.LogMessage log_message = 6;
  if (what_case() == kLogMessage) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::log_message(this),
        _Internal::log_message(this).GetCachedSize(), target, stream);
  }

  // .tensorboard.SessionLog session_log = 7;
  if (what_case() == kSessionLog) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::session_log(this),
        _Internal::session_log(this).GetCachedSize(), target, stream);
  }

  // .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;
  if (what_case() == kTaggedRunMetadata) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::tagged_run_metadata(this),
        _Internal::tagged_run_metadata(this).GetCachedSize(), target, stream);
  }

  // bytes meta_graph_def = 9;
  if (what_case() == kMetaGraphDef) {
    const TProtoStringType& _s = this->_internal_meta_graph_def();
    target = stream->WriteBytesMaybeAliased(9, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.Event)
  return target;
}

::size_t Event::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.Event)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // double wall_time = 1;
  static_assert(sizeof(::arc_ui64) == sizeof(double), "Code assumes ::arc_ui64 and double are the same size.");
  double tmp_wall_time = this->_internal_wall_time();
  ::arc_ui64 raw_wall_time;
  memcpy(&raw_wall_time, &tmp_wall_time, sizeof(tmp_wall_time));
  if (raw_wall_time != 0) {
    total_size += 9;
  }

  // int64 step = 2;
  if (this->_internal_step() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_step());
  }

  switch (what_case()) {
    // string file_version = 3;
    case kFileVersion: {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                      this->_internal_file_version());
      break;
    }
    // bytes graph_def = 4;
    case kGraphDef: {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
                                      this->_internal_graph_def());
      break;
    }
    // .tensorboard.Summary summary = 5;
    case kSummary: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.what_.summary_);
      break;
    }
    // .tensorboard.LogMessage log_message = 6;
    case kLogMessage: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.what_.log_message_);
      break;
    }
    // .tensorboard.SessionLog session_log = 7;
    case kSessionLog: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.what_.session_log_);
      break;
    }
    // .tensorboard.TaggedRunMetadata tagged_run_metadata = 8;
    case kTaggedRunMetadata: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.what_.tagged_run_metadata_);
      break;
    }
    // bytes meta_graph_def = 9;
    case kMetaGraphDef: {
      total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
                                      this->_internal_meta_graph_def());
      break;
    }
    case WHAT_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Event::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Event::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Event::GetClassData() const { return &_class_data_; }


void Event::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Event*>(&to_msg);
  auto& from = static_cast<const Event&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.Event)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(::arc_ui64) == sizeof(double), "Code assumes ::arc_ui64 and double are the same size.");
  double tmp_wall_time = from._internal_wall_time();
  ::arc_ui64 raw_wall_time;
  memcpy(&raw_wall_time, &tmp_wall_time, sizeof(tmp_wall_time));
  if (raw_wall_time != 0) {
    _this->_internal_set_wall_time(from._internal_wall_time());
  }
  if (from._internal_step() != 0) {
    _this->_internal_set_step(from._internal_step());
  }
  switch (from.what_case()) {
    case kFileVersion: {
      _this->_internal_set_file_version(from._internal_file_version());
      break;
    }
    case kGraphDef: {
      _this->_internal_set_graph_def(from._internal_graph_def());
      break;
    }
    case kSummary: {
      _this->_internal_mutable_summary()->::tensorboard::Summary::MergeFrom(
          from._internal_summary());
      break;
    }
    case kLogMessage: {
      _this->_internal_mutable_log_message()->::tensorboard::LogMessage::MergeFrom(
          from._internal_log_message());
      break;
    }
    case kSessionLog: {
      _this->_internal_mutable_session_log()->::tensorboard::SessionLog::MergeFrom(
          from._internal_session_log());
      break;
    }
    case kTaggedRunMetadata: {
      _this->_internal_mutable_tagged_run_metadata()->::tensorboard::TaggedRunMetadata::MergeFrom(
          from._internal_tagged_run_metadata());
      break;
    }
    case kMetaGraphDef: {
      _this->_internal_set_meta_graph_def(from._internal_meta_graph_def());
      break;
    }
    case WHAT_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Event::CopyFrom(const Event& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.Event)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Event::IsInitialized() const {
  return true;
}

void Event::InternalSwap(Event* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Event, _impl_.step_)
      + sizeof(Event::_impl_.step_)
      - PROTOBUF_FIELD_OFFSET(Event, _impl_.wall_time_)>(
          reinterpret_cast<char*>(&_impl_.wall_time_),
          reinterpret_cast<char*>(&other->_impl_.wall_time_));
  swap(_impl_.what_, other->_impl_.what_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Event::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2fevent_2eproto[0]);
}
// ===================================================================

class LogMessage::_Internal {
 public:
};

LogMessage::LogMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.LogMessage)
}
LogMessage::LogMessage(const LogMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  LogMessage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_) {}

    , decltype(_impl_.level_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), _this->GetArenaForAllocation());
  }
  _this->_impl_.level_ = from._impl_.level_;
  // @@protoc_insertion_point(copy_constructor:tensorboard.LogMessage)
}

inline void LogMessage::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.message_) {}

    , decltype(_impl_.level_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.message_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

LogMessage::~LogMessage() {
  // @@protoc_insertion_point(destructor:tensorboard.LogMessage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void LogMessage::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
}

void LogMessage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void LogMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.LogMessage)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.level_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LogMessage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tensorboard.LogMessage.Level level = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::arc_ui32 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_level(static_cast<::tensorboard::LogMessage_Level>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.LogMessage.message"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* LogMessage::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.LogMessage)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorboard.LogMessage.Level level = 1;
  if (this->_internal_level() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_level(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    const TProtoStringType& _s = this->_internal_message();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.LogMessage.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.LogMessage)
  return target;
}

::size_t LogMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.LogMessage)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  // .tensorboard.LogMessage.Level level = 1;
  if (this->_internal_level() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_level());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData LogMessage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    LogMessage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*LogMessage::GetClassData() const { return &_class_data_; }


void LogMessage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<LogMessage*>(&to_msg);
  auto& from = static_cast<const LogMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.LogMessage)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (from._internal_level() != 0) {
    _this->_internal_set_level(from._internal_level());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void LogMessage::CopyFrom(const LogMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.LogMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LogMessage::IsInitialized() const {
  return true;
}

void LogMessage::InternalSwap(LogMessage* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, lhs_arena,
                                       &other->_impl_.message_, rhs_arena);
  swap(_impl_.level_, other->_impl_.level_);
}

::PROTOBUF_NAMESPACE_ID::Metadata LogMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2fevent_2eproto[1]);
}
// ===================================================================

class SessionLog::_Internal {
 public:
};

SessionLog::SessionLog(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.SessionLog)
}
SessionLog::SessionLog(const SessionLog& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SessionLog* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.checkpoint_path_) {}

    , decltype(_impl_.msg_) {}

    , decltype(_impl_.status_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.checkpoint_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.checkpoint_path_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_checkpoint_path().empty()) {
    _this->_impl_.checkpoint_path_.Set(from._internal_checkpoint_path(), _this->GetArenaForAllocation());
  }
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.msg_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_msg().empty()) {
    _this->_impl_.msg_.Set(from._internal_msg(), _this->GetArenaForAllocation());
  }
  _this->_impl_.status_ = from._impl_.status_;
  // @@protoc_insertion_point(copy_constructor:tensorboard.SessionLog)
}

inline void SessionLog::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.checkpoint_path_) {}

    , decltype(_impl_.msg_) {}

    , decltype(_impl_.status_) { 0 }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.checkpoint_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.checkpoint_path_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.msg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.msg_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SessionLog::~SessionLog() {
  // @@protoc_insertion_point(destructor:tensorboard.SessionLog)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SessionLog::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.checkpoint_path_.Destroy();
  _impl_.msg_.Destroy();
}

void SessionLog::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SessionLog::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.SessionLog)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.checkpoint_path_.ClearToEmpty();
  _impl_.msg_.ClearToEmpty();
  _impl_.status_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SessionLog::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .tensorboard.SessionLog.SessionStatus status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          ::arc_ui32 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          _internal_set_status(static_cast<::tensorboard::SessionLog_SessionStatus>(val));
        } else {
          goto handle_unusual;
        }
        continue;
      // string checkpoint_path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_checkpoint_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.SessionLog.checkpoint_path"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string msg = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_msg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.SessionLog.msg"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* SessionLog::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.SessionLog)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorboard.SessionLog.SessionStatus status = 1;
  if (this->_internal_status() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_status(), target);
  }

  // string checkpoint_path = 2;
  if (!this->_internal_checkpoint_path().empty()) {
    const TProtoStringType& _s = this->_internal_checkpoint_path();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.SessionLog.checkpoint_path");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string msg = 3;
  if (!this->_internal_msg().empty()) {
    const TProtoStringType& _s = this->_internal_msg();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.SessionLog.msg");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.SessionLog)
  return target;
}

::size_t SessionLog::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.SessionLog)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string checkpoint_path = 2;
  if (!this->_internal_checkpoint_path().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_checkpoint_path());
  }

  // string msg = 3;
  if (!this->_internal_msg().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_msg());
  }

  // .tensorboard.SessionLog.SessionStatus status = 1;
  if (this->_internal_status() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_status());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SessionLog::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SessionLog::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SessionLog::GetClassData() const { return &_class_data_; }


void SessionLog::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SessionLog*>(&to_msg);
  auto& from = static_cast<const SessionLog&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.SessionLog)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_checkpoint_path().empty()) {
    _this->_internal_set_checkpoint_path(from._internal_checkpoint_path());
  }
  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_status() != 0) {
    _this->_internal_set_status(from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SessionLog::CopyFrom(const SessionLog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.SessionLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SessionLog::IsInitialized() const {
  return true;
}

void SessionLog::InternalSwap(SessionLog* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.checkpoint_path_, lhs_arena,
                                       &other->_impl_.checkpoint_path_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, lhs_arena,
                                       &other->_impl_.msg_, rhs_arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SessionLog::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2fevent_2eproto[2]);
}
// ===================================================================

class TaggedRunMetadata::_Internal {
 public:
};

TaggedRunMetadata::TaggedRunMetadata(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.TaggedRunMetadata)
}
TaggedRunMetadata::TaggedRunMetadata(const TaggedRunMetadata& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TaggedRunMetadata* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.tag_) {}

    , decltype(_impl_.run_metadata_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.tag_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.tag_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tag().empty()) {
    _this->_impl_.tag_.Set(from._internal_tag(), _this->GetArenaForAllocation());
  }
  _impl_.run_metadata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.run_metadata_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_run_metadata().empty()) {
    _this->_impl_.run_metadata_.Set(from._internal_run_metadata(), _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:tensorboard.TaggedRunMetadata)
}

inline void TaggedRunMetadata::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.tag_) {}

    , decltype(_impl_.run_metadata_) {}

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.tag_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.tag_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.run_metadata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.run_metadata_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TaggedRunMetadata::~TaggedRunMetadata() {
  // @@protoc_insertion_point(destructor:tensorboard.TaggedRunMetadata)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TaggedRunMetadata::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.tag_.Destroy();
  _impl_.run_metadata_.Destroy();
}

void TaggedRunMetadata::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TaggedRunMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.TaggedRunMetadata)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.tag_.ClearToEmpty();
  _impl_.run_metadata_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TaggedRunMetadata::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string tag = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_tag();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.TaggedRunMetadata.tag"));
        } else {
          goto handle_unusual;
        }
        continue;
      // bytes run_metadata = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_run_metadata();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TaggedRunMetadata::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.TaggedRunMetadata)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string tag = 1;
  if (!this->_internal_tag().empty()) {
    const TProtoStringType& _s = this->_internal_tag();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.TaggedRunMetadata.tag");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bytes run_metadata = 2;
  if (!this->_internal_run_metadata().empty()) {
    const TProtoStringType& _s = this->_internal_run_metadata();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.TaggedRunMetadata)
  return target;
}

::size_t TaggedRunMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.TaggedRunMetadata)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string tag = 1;
  if (!this->_internal_tag().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_tag());
  }

  // bytes run_metadata = 2;
  if (!this->_internal_run_metadata().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
                                    this->_internal_run_metadata());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TaggedRunMetadata::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TaggedRunMetadata::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TaggedRunMetadata::GetClassData() const { return &_class_data_; }


void TaggedRunMetadata::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TaggedRunMetadata*>(&to_msg);
  auto& from = static_cast<const TaggedRunMetadata&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.TaggedRunMetadata)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_tag().empty()) {
    _this->_internal_set_tag(from._internal_tag());
  }
  if (!from._internal_run_metadata().empty()) {
    _this->_internal_set_run_metadata(from._internal_run_metadata());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TaggedRunMetadata::CopyFrom(const TaggedRunMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.TaggedRunMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TaggedRunMetadata::IsInitialized() const {
  return true;
}

void TaggedRunMetadata::InternalSwap(TaggedRunMetadata* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.tag_, lhs_arena,
                                       &other->_impl_.tag_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.run_metadata_, lhs_arena,
                                       &other->_impl_.run_metadata_, rhs_arena);
}

::PROTOBUF_NAMESPACE_ID::Metadata TaggedRunMetadata::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2fevent_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2fevent_2eproto[3]);
}
// Yandex-specific extension
TProtoStringType Event::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void Event::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void Event::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::Event::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (Getwall_time()) {
    out << sep;
    out << "\"wall_time\":";
    out << Getwall_time();
    sep = ",";
  }
  if (Getstep()) {
    out << sep;
    out << "\"step\":";
    out << Getstep();
    sep = ",";
  }
  if (Hasfile_version()) {
    out << sep;
    out << "\"file_version\":";
    ::google::protobuf::io::PrintJSONString(out, Getfile_version());
    sep = ",";
  }
  if (Hasgraph_def()) {
    out << sep;
    out << "\"graph_def\":";
    ::google::protobuf::io::PrintJSONString(out, Getgraph_def());
    sep = ",";
  }
  if (Hassummary()) {
    out << sep;
    out << "\"summary\":";
    Getsummary().PrintJSON(out);
    sep = ",";
  }
  if (Haslog_message()) {
    out << sep;
    out << "\"log_message\":";
    Getlog_message().PrintJSON(out);
    sep = ",";
  }
  if (Hassession_log()) {
    out << sep;
    out << "\"session_log\":";
    Getsession_log().PrintJSON(out);
    sep = ",";
  }
  if (Hastagged_run_metadata()) {
    out << sep;
    out << "\"tagged_run_metadata\":";
    Gettagged_run_metadata().PrintJSON(out);
    sep = ",";
  }
  if (Hasmeta_graph_def()) {
    out << sep;
    out << "\"meta_graph_def\":";
    ::google::protobuf::io::PrintJSONString(out, Getmeta_graph_def());
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
TProtoStringType LogMessage::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void LogMessage::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void LogMessage::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::LogMessage::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (Getlevel()) {
    out << sep;
    out << "\"level\":";
    out << (int)Getlevel();
    sep = ",";
  }
  if (Getmessage()) {
    out << sep;
    out << "\"message\":";
    ::google::protobuf::io::PrintJSONString(out, Getmessage());
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
TProtoStringType SessionLog::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void SessionLog::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void SessionLog::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::SessionLog::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (Getstatus()) {
    out << sep;
    out << "\"status\":";
    out << (int)Getstatus();
    sep = ",";
  }
  if (Getcheckpoint_path()) {
    out << sep;
    out << "\"checkpoint_path\":";
    ::google::protobuf::io::PrintJSONString(out, Getcheckpoint_path());
    sep = ",";
  }
  if (Getmsg()) {
    out << sep;
    out << "\"msg\":";
    ::google::protobuf::io::PrintJSONString(out, Getmsg());
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
TProtoStringType TaggedRunMetadata::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void TaggedRunMetadata::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TaggedRunMetadata::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::TaggedRunMetadata::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (Gettag()) {
    out << sep;
    out << "\"tag\":";
    ::google::protobuf::io::PrintJSONString(out, Gettag());
    sep = ",";
  }
  if (Getrun_metadata()) {
    out << sep;
    out << "\"run_metadata\":";
    ::google::protobuf::io::PrintJSONString(out, Getrun_metadata());
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// @@protoc_insertion_point(namespace_scope)
}  // namespace tensorboard
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tensorboard::Event*
Arena::CreateMaybeMessage< ::tensorboard::Event >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::Event >(arena);
}
template<> PROTOBUF_NOINLINE ::tensorboard::LogMessage*
Arena::CreateMaybeMessage< ::tensorboard::LogMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::LogMessage >(arena);
}
template<> PROTOBUF_NOINLINE ::tensorboard::SessionLog*
Arena::CreateMaybeMessage< ::tensorboard::SessionLog >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::SessionLog >(arena);
}
template<> PROTOBUF_NOINLINE ::tensorboard::TaggedRunMetadata*
Arena::CreateMaybeMessage< ::tensorboard::TaggedRunMetadata >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::TaggedRunMetadata >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// Yandex debug output extension
template<>
void Out< ::tensorboard::Event>(IOutputStream& out, const ::tensorboard::Event& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::tensorboard::LogMessage>(IOutputStream& out, const ::tensorboard::LogMessage& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::tensorboard::SessionLog>(IOutputStream& out, const ::tensorboard::SessionLog& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::tensorboard::TaggedRunMetadata>(IOutputStream& out, const ::tensorboard::TaggedRunMetadata& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
