// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/tensorboard/resource_handle.proto

#include "contrib/libs/tensorboard/resource_handle.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include <google/protobuf/messagext.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace tensorboard {
PROTOBUF_CONSTEXPR ResourceHandle::ResourceHandle(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.device_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.container_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.name_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.maybe_type_name_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.hash_code_)*/ ::arc_ui64{0u}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ResourceHandleDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResourceHandleDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResourceHandleDefaultTypeInternal() {}
  union {
    ResourceHandle _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResourceHandleDefaultTypeInternal _ResourceHandle_default_instance_;
}  // namespace tensorboard
static ::_pb::Metadata file_level_metadata_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto = nullptr;
const ::arc_ui32 TableStruct_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::ResourceHandle, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::ResourceHandle, _impl_.device_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::ResourceHandle, _impl_.container_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::ResourceHandle, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::ResourceHandle, _impl_.hash_code_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::ResourceHandle, _impl_.maybe_type_name_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::tensorboard::ResourceHandle)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::tensorboard::_ResourceHandle_default_instance_._instance,
};
const char descriptor_table_protodef_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n.contrib/libs/tensorboard/resource_hand"
    "le.proto\022\013tensorboard\"m\n\016ResourceHandle\022"
    "\016\n\006device\030\001 \001(\t\022\021\n\tcontainer\030\002 \001(\t\022\014\n\004na"
    "me\030\003 \001(\t\022\021\n\thash_code\030\004 \001(\004\022\027\n\017maybe_typ"
    "e_name\030\005 \001(\tB4\n\030org.tensorflow.framework"
    "B\023ResourceHandleProtoP\001\370\001\001b\006proto3"
};
static ::y_absl::once_flag descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto = {
    false,
    false,
    234,
    descriptor_table_protodef_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto,
    "contrib/libs/tensorboard/resource_handle.proto",
    &descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto::offsets,
    file_level_metadata_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto,
    file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto,
    file_level_service_descriptors_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto_getter() {
  return &descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto(&descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto);
namespace tensorboard {
// ===================================================================

class ResourceHandle::_Internal {
 public:
};

ResourceHandle::ResourceHandle(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.ResourceHandle)
}
ResourceHandle::ResourceHandle(const ResourceHandle& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ResourceHandle* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.device_) {}

    , decltype(_impl_.container_) {}

    , decltype(_impl_.name_) {}

    , decltype(_impl_.maybe_type_name_) {}

    , decltype(_impl_.hash_code_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.device_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.device_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_device().empty()) {
    _this->_impl_.device_.Set(from._internal_device(), _this->GetArenaForAllocation());
  }
  _impl_.container_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.container_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_container().empty()) {
    _this->_impl_.container_.Set(from._internal_container(), _this->GetArenaForAllocation());
  }
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), _this->GetArenaForAllocation());
  }
  _impl_.maybe_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.maybe_type_name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_maybe_type_name().empty()) {
    _this->_impl_.maybe_type_name_.Set(from._internal_maybe_type_name(), _this->GetArenaForAllocation());
  }
  _this->_impl_.hash_code_ = from._impl_.hash_code_;
  // @@protoc_insertion_point(copy_constructor:tensorboard.ResourceHandle)
}

inline void ResourceHandle::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.device_) {}

    , decltype(_impl_.container_) {}

    , decltype(_impl_.name_) {}

    , decltype(_impl_.maybe_type_name_) {}

    , decltype(_impl_.hash_code_) { ::arc_ui64{0u} }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.device_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.device_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.container_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.container_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.maybe_type_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.maybe_type_name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ResourceHandle::~ResourceHandle() {
  // @@protoc_insertion_point(destructor:tensorboard.ResourceHandle)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResourceHandle::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.device_.Destroy();
  _impl_.container_.Destroy();
  _impl_.name_.Destroy();
  _impl_.maybe_type_name_.Destroy();
}

void ResourceHandle::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ResourceHandle::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.ResourceHandle)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_.ClearToEmpty();
  _impl_.container_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  _impl_.maybe_type_name_.ClearToEmpty();
  _impl_.hash_code_ = ::arc_ui64{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResourceHandle::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string device = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_device();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.ResourceHandle.device"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string container = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_container();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.ResourceHandle.container"));
        } else {
          goto handle_unusual;
        }
        continue;
      // string name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.ResourceHandle.name"));
        } else {
          goto handle_unusual;
        }
        continue;
      // uint64 hash_code = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 32)) {
          _impl_.hash_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // string maybe_type_name = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_maybe_type_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.ResourceHandle.maybe_type_name"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* ResourceHandle::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.ResourceHandle)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string device = 1;
  if (!this->_internal_device().empty()) {
    const TProtoStringType& _s = this->_internal_device();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.ResourceHandle.device");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string container = 2;
  if (!this->_internal_container().empty()) {
    const TProtoStringType& _s = this->_internal_container();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.ResourceHandle.container");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    const TProtoStringType& _s = this->_internal_name();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.ResourceHandle.name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // uint64 hash_code = 4;
  if (this->_internal_hash_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        4, this->_internal_hash_code(), target);
  }

  // string maybe_type_name = 5;
  if (!this->_internal_maybe_type_name().empty()) {
    const TProtoStringType& _s = this->_internal_maybe_type_name();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.ResourceHandle.maybe_type_name");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.ResourceHandle)
  return target;
}

::size_t ResourceHandle::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.ResourceHandle)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string device = 1;
  if (!this->_internal_device().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_device());
  }

  // string container = 2;
  if (!this->_internal_container().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_container());
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string maybe_type_name = 5;
  if (!this->_internal_maybe_type_name().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_maybe_type_name());
  }

  // uint64 hash_code = 4;
  if (this->_internal_hash_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_hash_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResourceHandle::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ResourceHandle::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResourceHandle::GetClassData() const { return &_class_data_; }


void ResourceHandle::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ResourceHandle*>(&to_msg);
  auto& from = static_cast<const ResourceHandle&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.ResourceHandle)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device().empty()) {
    _this->_internal_set_device(from._internal_device());
  }
  if (!from._internal_container().empty()) {
    _this->_internal_set_container(from._internal_container());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_maybe_type_name().empty()) {
    _this->_internal_set_maybe_type_name(from._internal_maybe_type_name());
  }
  if (from._internal_hash_code() != 0) {
    _this->_internal_set_hash_code(from._internal_hash_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResourceHandle::CopyFrom(const ResourceHandle& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.ResourceHandle)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResourceHandle::IsInitialized() const {
  return true;
}

void ResourceHandle::InternalSwap(ResourceHandle* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_, lhs_arena,
                                       &other->_impl_.device_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.container_, lhs_arena,
                                       &other->_impl_.container_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, lhs_arena,
                                       &other->_impl_.name_, rhs_arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.maybe_type_name_, lhs_arena,
                                       &other->_impl_.maybe_type_name_, rhs_arena);

  swap(_impl_.hash_code_, other->_impl_.hash_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResourceHandle::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2fresource_5fhandle_2eproto[0]);
}
// Yandex-specific extension
TProtoStringType ResourceHandle::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void ResourceHandle::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void ResourceHandle::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::ResourceHandle::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (Getdevice()) {
    out << sep;
    out << "\"device\":";
    ::google::protobuf::io::PrintJSONString(out, Getdevice());
    sep = ",";
  }
  if (Getcontainer()) {
    out << sep;
    out << "\"container\":";
    ::google::protobuf::io::PrintJSONString(out, Getcontainer());
    sep = ",";
  }
  if (Getname()) {
    out << sep;
    out << "\"name\":";
    ::google::protobuf::io::PrintJSONString(out, Getname());
    sep = ",";
  }
  if (Gethash_code()) {
    out << sep;
    out << "\"hash_code\":";
    out << Gethash_code();
    sep = ",";
  }
  if (Getmaybe_type_name()) {
    out << sep;
    out << "\"maybe_type_name\":";
    ::google::protobuf::io::PrintJSONString(out, Getmaybe_type_name());
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// @@protoc_insertion_point(namespace_scope)
}  // namespace tensorboard
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tensorboard::ResourceHandle*
Arena::CreateMaybeMessage< ::tensorboard::ResourceHandle >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::ResourceHandle >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// Yandex debug output extension
template<>
void Out< ::tensorboard::ResourceHandle>(IOutputStream& out, const ::tensorboard::ResourceHandle& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
