// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/tensorboard/tensor_shape.proto

#include "contrib/libs/tensorboard/tensor_shape.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include <google/protobuf/messagext.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace tensorboard {
PROTOBUF_CONSTEXPR TensorShapeProto_Dim::TensorShapeProto_Dim(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/ {
    &::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized {}
  }

  , /*decltype(_impl_.size_)*/ ::arc_i64{0}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TensorShapeProto_DimDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TensorShapeProto_DimDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TensorShapeProto_DimDefaultTypeInternal() {}
  union {
    TensorShapeProto_Dim _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TensorShapeProto_DimDefaultTypeInternal _TensorShapeProto_Dim_default_instance_;
PROTOBUF_CONSTEXPR TensorShapeProto::TensorShapeProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dim_)*/{}
  , /*decltype(_impl_.unknown_rank_)*/ false

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TensorShapeProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TensorShapeProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TensorShapeProtoDefaultTypeInternal() {}
  union {
    TensorShapeProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TensorShapeProtoDefaultTypeInternal _TensorShapeProto_default_instance_;
}  // namespace tensorboard
static ::_pb::Metadata file_level_metadata_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto = nullptr;
const ::arc_ui32 TableStruct_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::TensorShapeProto_Dim, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::TensorShapeProto_Dim, _impl_.size_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::TensorShapeProto_Dim, _impl_.name_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tensorboard::TensorShapeProto, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tensorboard::TensorShapeProto, _impl_.dim_),
    PROTOBUF_FIELD_OFFSET(::tensorboard::TensorShapeProto, _impl_.unknown_rank_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::tensorboard::TensorShapeProto_Dim)},
        { 10, -1, -1, sizeof(::tensorboard::TensorShapeProto)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::tensorboard::_TensorShapeProto_Dim_default_instance_._instance,
    &::tensorboard::_TensorShapeProto_default_instance_._instance,
};
const char descriptor_table_protodef_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n+contrib/libs/tensorboard/tensor_shape."
    "proto\022\013tensorboard\"{\n\020TensorShapeProto\022."
    "\n\003dim\030\002 \003(\0132!.tensorboard.TensorShapePro"
    "to.Dim\022\024\n\014unknown_rank\030\003 \001(\010\032!\n\003Dim\022\014\n\004s"
    "ize\030\001 \001(\003\022\014\n\004name\030\002 \001(\tB2\n\030org.tensorflo"
    "w.frameworkB\021TensorShapeProtosP\001\370\001\001b\006pro"
    "to3"
};
static ::y_absl::once_flag descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto = {
    false,
    false,
    243,
    descriptor_table_protodef_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto,
    "contrib/libs/tensorboard/tensor_shape.proto",
    &descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto::offsets,
    file_level_metadata_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto,
    file_level_enum_descriptors_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto,
    file_level_service_descriptors_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_getter() {
  return &descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto(&descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto);
namespace tensorboard {
// ===================================================================

class TensorShapeProto_Dim::_Internal {
 public:
};

TensorShapeProto_Dim::TensorShapeProto_Dim(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.TensorShapeProto.Dim)
}
TensorShapeProto_Dim::TensorShapeProto_Dim(const TensorShapeProto_Dim& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TensorShapeProto_Dim* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_) {}

    , decltype(_impl_.size_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), _this->GetArenaForAllocation());
  }
  _this->_impl_.size_ = from._impl_.size_;
  // @@protoc_insertion_point(copy_constructor:tensorboard.TensorShapeProto.Dim)
}

inline void TensorShapeProto_Dim::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.name_) {}

    , decltype(_impl_.size_) { ::arc_i64{0} }

    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TensorShapeProto_Dim::~TensorShapeProto_Dim() {
  // @@protoc_insertion_point(destructor:tensorboard.TensorShapeProto.Dim)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TensorShapeProto_Dim::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void TensorShapeProto_Dim::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TensorShapeProto_Dim::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.TensorShapeProto.Dim)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.size_ = ::arc_i64{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TensorShapeProto_Dim::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 size = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _impl_.size_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "tensorboard.TensorShapeProto.Dim.name"));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TensorShapeProto_Dim::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.TensorShapeProto.Dim)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 size = 1;
  if (this->_internal_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(
        1, this->_internal_size(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    const TProtoStringType& _s = this->_internal_name();
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE, "tensorboard.TensorShapeProto.Dim.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.TensorShapeProto.Dim)
  return target;
}

::size_t TensorShapeProto_Dim::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.TensorShapeProto.Dim)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // int64 size = 1;
  if (this->_internal_size() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TensorShapeProto_Dim::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TensorShapeProto_Dim::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TensorShapeProto_Dim::GetClassData() const { return &_class_data_; }


void TensorShapeProto_Dim::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TensorShapeProto_Dim*>(&to_msg);
  auto& from = static_cast<const TensorShapeProto_Dim&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.TensorShapeProto.Dim)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_size() != 0) {
    _this->_internal_set_size(from._internal_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TensorShapeProto_Dim::CopyFrom(const TensorShapeProto_Dim& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.TensorShapeProto.Dim)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TensorShapeProto_Dim::IsInitialized() const {
  return true;
}

void TensorShapeProto_Dim::InternalSwap(TensorShapeProto_Dim* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, lhs_arena,
                                       &other->_impl_.name_, rhs_arena);

  swap(_impl_.size_, other->_impl_.size_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TensorShapeProto_Dim::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto[0]);
}
// ===================================================================

class TensorShapeProto::_Internal {
 public:
};

TensorShapeProto::TensorShapeProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorboard.TensorShapeProto)
}
TensorShapeProto::TensorShapeProto(const TensorShapeProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TensorShapeProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dim_){from._impl_.dim_}
    , decltype(_impl_.unknown_rank_) {}

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.unknown_rank_ = from._impl_.unknown_rank_;
  // @@protoc_insertion_point(copy_constructor:tensorboard.TensorShapeProto)
}

inline void TensorShapeProto::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.dim_){arena}
    , decltype(_impl_.unknown_rank_) { false }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TensorShapeProto::~TensorShapeProto() {
  // @@protoc_insertion_point(destructor:tensorboard.TensorShapeProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TensorShapeProto::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.dim_.~RepeatedPtrField();
}

void TensorShapeProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TensorShapeProto::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorboard.TensorShapeProto)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dim_.Clear();
  _impl_.unknown_rank_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TensorShapeProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .tensorboard.TensorShapeProto.Dim dim = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_dim(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // bool unknown_rank = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 24)) {
          _impl_.unknown_rank_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TensorShapeProto::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tensorboard.TensorShapeProto)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tensorboard.TensorShapeProto.Dim dim = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dim_size()); i < n; i++) {
    const auto& repfield = this->_internal_dim(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  // bool unknown_rank = 3;
  if (this->_internal_unknown_rank() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_unknown_rank(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorboard.TensorShapeProto)
  return target;
}

::size_t TensorShapeProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorboard.TensorShapeProto)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tensorboard.TensorShapeProto.Dim dim = 2;
  total_size += 1UL * this->_internal_dim_size();
  for (const auto& msg : this->_impl_.dim_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // bool unknown_rank = 3;
  if (this->_internal_unknown_rank() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TensorShapeProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TensorShapeProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TensorShapeProto::GetClassData() const { return &_class_data_; }


void TensorShapeProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TensorShapeProto*>(&to_msg);
  auto& from = static_cast<const TensorShapeProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tensorboard.TensorShapeProto)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.dim_.MergeFrom(from._impl_.dim_);
  if (from._internal_unknown_rank() != 0) {
    _this->_internal_set_unknown_rank(from._internal_unknown_rank());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TensorShapeProto::CopyFrom(const TensorShapeProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorboard.TensorShapeProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TensorShapeProto::IsInitialized() const {
  return true;
}

void TensorShapeProto::InternalSwap(TensorShapeProto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dim_.InternalSwap(&other->_impl_.dim_);

  swap(_impl_.unknown_rank_, other->_impl_.unknown_rank_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TensorShapeProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_getter, &descriptor_table_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto_once,
      file_level_metadata_contrib_2flibs_2ftensorboard_2ftensor_5fshape_2eproto[1]);
}
// Yandex-specific extension
TProtoStringType TensorShapeProto::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
TProtoStringType TensorShapeProto_Dim::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void TensorShapeProto::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TensorShapeProto::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::TensorShapeProto::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (dimSize() > 0) {
    out << sep;
    out << "\"dim\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < dimSize(); ++_index) {
        out << separator;
        Getdim(_index).PrintJSON(out);
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  if (Getunknown_rank()) {
    out << sep;
    out << "\"unknown_rank\":";
    out << (Getunknown_rank() ? "true" : "false");
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
void TensorShapeProto_Dim::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TensorShapeProto_Dim::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::tensorboard::TensorShapeProto_Dim::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (Getsize()) {
    out << sep;
    out << "\"size\":";
    out << Getsize();
    sep = ",";
  }
  if (Getname()) {
    out << sep;
    out << "\"name\":";
    ::google::protobuf::io::PrintJSONString(out, Getname());
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// @@protoc_insertion_point(namespace_scope)
}  // namespace tensorboard
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tensorboard::TensorShapeProto_Dim*
Arena::CreateMaybeMessage< ::tensorboard::TensorShapeProto_Dim >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::TensorShapeProto_Dim >(arena);
}
template<> PROTOBUF_NOINLINE ::tensorboard::TensorShapeProto*
Arena::CreateMaybeMessage< ::tensorboard::TensorShapeProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tensorboard::TensorShapeProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// Yandex debug output extension
template<>
void Out< ::tensorboard::TensorShapeProto>(IOutputStream& out, const ::tensorboard::TensorShapeProto& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::tensorboard::TensorShapeProto_Dim>(IOutputStream& out, const ::tensorboard::TensorShapeProto_Dim& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
