# CMake generated Testfile for 
# Source directory: /home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut
# Build directory: /home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(util-generic-ut_0 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "0" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_0 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_1 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "1" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_1 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_2 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "2" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_2 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_3 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "3" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_3 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_4 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "4" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_4 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_5 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "5" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_5 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_6 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "6" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_6 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_7 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "7" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_7 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_8 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "8" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_8 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
add_test(util-generic-ut_9 "/home/artem/.pyenv/versions/3.12.12/bin/python3.12" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build/scripts/split_unittest.py" "--split-factor" "10" "--shard" "9" "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/build_cpu/util/generic/ut/util-generic-ut" "--print-before-suite" "--print-before-test" "--fork-tests" "--print-times" "--show-fails")
set_tests_properties(util-generic-ut_9 PROPERTIES  ENVIRONMENT "" LABELS "SMALL" PROCESSORS "1" _BACKTRACE_TRIPLES "/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/cmake/common.cmake;304;add_test;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;125;add_yunittest;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.linux-x86_64.txt;0;;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;16;include;/home/artem/Articles_and_Projects/gbdt_with_variable_learners/catboost_change/catboost/util/generic/ut/CMakeLists.txt;0;")
