// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catboost/idl/pool/proto/metainfo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022005 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include <google/protobuf/json_util.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto {
  static const ::arc_ui32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto;
namespace NCB {
namespace NIdl {
class TPoolMetainfo;
struct TPoolMetainfoDefaultTypeInternal;
extern TPoolMetainfoDefaultTypeInternal _TPoolMetainfo_default_instance_;
class TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse;
struct TPoolMetainfo_ColumnIndexToNameEntry_DoNotUseDefaultTypeInternal;
extern TPoolMetainfo_ColumnIndexToNameEntry_DoNotUseDefaultTypeInternal _TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse_default_instance_;
class TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse;
struct TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUseDefaultTypeInternal;
extern TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUseDefaultTypeInternal _TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse_default_instance_;
}  // namespace NIdl
}  // namespace NCB
PROTOBUF_NAMESPACE_OPEN
template <>
::NCB::NIdl::TPoolMetainfo* Arena::CreateMaybeMessage<::NCB::NIdl::TPoolMetainfo>(Arena*);
template <>
::NCB::NIdl::TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse* Arena::CreateMaybeMessage<::NCB::NIdl::TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse>(Arena*);
template <>
::NCB::NIdl::TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse* Arena::CreateMaybeMessage<::NCB::NIdl::TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace NCB {
namespace NIdl {
enum EColumnType : int {
  CT_UNKNOWN = 0,
  CT_NUMERIC = 1,
  CT_LABEL = 2,
  CT_WEIGHT = 3,
  CT_GROUP_WEIGHT = 4,
  CT_BASELINE = 5,
  CT_SUBGROUP_ID = 6,
  CT_DOCUMENT_ID = 7,
  CT_GROUP_ID = 8,
  CT_CATEGORICAL = 9,
  CT_SPARSE = 10,
  CT_TIMESTAMP = 11,
  CT_PREDICTION = 12,
  CT_AUXILIARY = 13,
};

bool EColumnType_IsValid(int value);
constexpr EColumnType EColumnType_MIN = static_cast<EColumnType>(0);
constexpr EColumnType EColumnType_MAX = static_cast<EColumnType>(13);
constexpr int EColumnType_ARRAYSIZE = 13 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
EColumnType_descriptor();
template <typename T>
const TProtoStringType& EColumnType_Name(T value) {
  static_assert(std::is_same<T, EColumnType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EColumnType_Name().");
  return EColumnType_Name(static_cast<EColumnType>(value));
}
template <>
inline const TProtoStringType& EColumnType_Name(EColumnType value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<EColumnType_descriptor,
                                                 0, 13>(
      static_cast<int>(value));
}
inline bool EColumnType_Parse(y_absl::string_view name, EColumnType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<EColumnType>(
      EColumnType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM> SuperType;
  TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse& other);
  static const TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse*>(&_TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto;
};
// -------------------------------------------------------------------

class TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse, 
    ::NProtoBuf::uint32, TProtoStringType,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse, 
    ::NProtoBuf::uint32, TProtoStringType,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse& other);
  static const TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse*>(&_TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(TProtoStringType* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "NCB.NIdl.TPoolMetainfo.ColumnIndexToNameEntry.value");
#else
    (void) s;
#endif
    return true;
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto;
};
// -------------------------------------------------------------------

class TPoolMetainfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NCB.NIdl.TPoolMetainfo) */ {
 public:
  inline TPoolMetainfo() : TPoolMetainfo(nullptr) {}
  ~TPoolMetainfo() override;
  explicit PROTOBUF_CONSTEXPR TPoolMetainfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TPoolMetainfo(const TPoolMetainfo& from);
  TPoolMetainfo(TPoolMetainfo&& from) noexcept
    : TPoolMetainfo() {
    *this = ::std::move(from);
  }

  inline TPoolMetainfo& operator=(const TPoolMetainfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline TPoolMetainfo& operator=(TPoolMetainfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TPoolMetainfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const TPoolMetainfo* internal_default_instance() {
    return reinterpret_cast<const TPoolMetainfo*>(
               &_TPoolMetainfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TPoolMetainfo& a, TPoolMetainfo& b) {
    a.Swap(&b);
  }
  inline void Swap(TPoolMetainfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TPoolMetainfo* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TPoolMetainfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TPoolMetainfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TPoolMetainfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TPoolMetainfo& from) {
    TPoolMetainfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TPoolMetainfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "NCB.NIdl.TPoolMetainfo";
  }
  protected:
  explicit TPoolMetainfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kColumnIndexToTypeFieldNumber = 1,
    kIgnoredColumnIndicesFieldNumber = 3,
    kColumnIndexToNameFieldNumber = 7,
    kDocumentCountFieldNumber = 2,
    kStringDocIdFakeColumnIndexFieldNumber = 4,
    kStringGroupIdFakeColumnIndexFieldNumber = 5,
    kMaxDocsInChunkFieldNumber = 8,
    kStringSubgroupIdFakeColumnIndexFieldNumber = 6,
  };
  // map<uint32, .NCB.NIdl.EColumnType> ColumnIndexToType = 1;
  int columnindextotype_size() const;
  private:
  int _internal_columnindextotype_size() const;

  public:
  void clear_columnindextotype() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >&
      _internal_columnindextotype() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >*
      _internal_mutable_columnindextotype();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >&
      columnindextotype() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >*
      mutable_columnindextotype();
  // repeated uint32 IgnoredColumnIndices = 3;
  int ignoredcolumnindices_size() const;
  private:
  int _internal_ignoredcolumnindices_size() const;

  public:
  void clear_ignoredcolumnindices() ;
  ::NProtoBuf::uint32 ignoredcolumnindices(int index) const;
  void set_ignoredcolumnindices(int index, ::NProtoBuf::uint32 value);
  void add_ignoredcolumnindices(::NProtoBuf::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>& ignoredcolumnindices() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>* mutable_ignoredcolumnindices();

  private:
  ::NProtoBuf::uint32 _internal_ignoredcolumnindices(int index) const;
  void _internal_add_ignoredcolumnindices(::NProtoBuf::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>& _internal_ignoredcolumnindices() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>* _internal_mutable_ignoredcolumnindices();

  public:
  // map<uint32, string> ColumnIndexToName = 7;
  int columnindextoname_size() const;
  private:
  int _internal_columnindextoname_size() const;

  public:
  void clear_columnindextoname() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >&
      _internal_columnindextoname() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >*
      _internal_mutable_columnindextoname();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >&
      columnindextoname() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >*
      mutable_columnindextoname();
  // optional uint64 DocumentCount = 2;
  bool has_documentcount() const;
  void clear_documentcount() ;
  ::NProtoBuf::uint64 documentcount() const;
  void set_documentcount(::NProtoBuf::uint64 value);

  private:
  ::NProtoBuf::uint64 _internal_documentcount() const;
  void _internal_set_documentcount(::NProtoBuf::uint64 value);

  public:
  // optional uint32 StringDocIdFakeColumnIndex = 4;
  bool has_stringdocidfakecolumnindex() const;
  void clear_stringdocidfakecolumnindex() ;
  ::NProtoBuf::uint32 stringdocidfakecolumnindex() const;
  void set_stringdocidfakecolumnindex(::NProtoBuf::uint32 value);

  private:
  ::NProtoBuf::uint32 _internal_stringdocidfakecolumnindex() const;
  void _internal_set_stringdocidfakecolumnindex(::NProtoBuf::uint32 value);

  public:
  // optional uint32 StringGroupIdFakeColumnIndex = 5;
  bool has_stringgroupidfakecolumnindex() const;
  void clear_stringgroupidfakecolumnindex() ;
  ::NProtoBuf::uint32 stringgroupidfakecolumnindex() const;
  void set_stringgroupidfakecolumnindex(::NProtoBuf::uint32 value);

  private:
  ::NProtoBuf::uint32 _internal_stringgroupidfakecolumnindex() const;
  void _internal_set_stringgroupidfakecolumnindex(::NProtoBuf::uint32 value);

  public:
  // optional uint64 MaxDocsInChunk = 8;
  bool has_maxdocsinchunk() const;
  void clear_maxdocsinchunk() ;
  ::NProtoBuf::uint64 maxdocsinchunk() const;
  void set_maxdocsinchunk(::NProtoBuf::uint64 value);

  private:
  ::NProtoBuf::uint64 _internal_maxdocsinchunk() const;
  void _internal_set_maxdocsinchunk(::NProtoBuf::uint64 value);

  public:
  // optional uint32 StringSubgroupIdFakeColumnIndex = 6;
  bool has_stringsubgroupidfakecolumnindex() const;
  void clear_stringsubgroupidfakecolumnindex() ;
  ::NProtoBuf::uint32 stringsubgroupidfakecolumnindex() const;
  void set_stringsubgroupidfakecolumnindex(::NProtoBuf::uint32 value);

  private:
  ::NProtoBuf::uint32 _internal_stringsubgroupidfakecolumnindex() const;
  void _internal_set_stringsubgroupidfakecolumnindex(::NProtoBuf::uint32 value);

  public:
  // Yandex cpp-styleguide extension
  inline size_t ColumnIndexToTypeSize() const { return (size_t)columnindextotype_size(); }
  inline void ClearColumnIndexToType() { clear_columnindextotype(); }
  inline const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::EColumnType>& GetColumnIndexToType() const { return columnindextotype(); }
  inline ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::EColumnType>* MutableColumnIndexToType() { return mutable_columnindextotype(); }
  
  inline size_t ColumnIndexToNameSize() const { return (size_t)columnindextoname_size(); }
  inline void ClearColumnIndexToName() { clear_columnindextoname(); }
  inline const ::google::protobuf::Map<::arc_ui32, TProtoStringType>& GetColumnIndexToName() const { return columnindextoname(); }
  inline ::google::protobuf::Map<::arc_ui32, TProtoStringType>* MutableColumnIndexToName() { return mutable_columnindextoname(); }
  
  inline bool HasDocumentCount() const { return has_documentcount(); }
  inline void ClearDocumentCount() { clear_documentcount(); }
  inline ::arc_ui64 GetDocumentCount() const { return documentcount();}
  inline void SetDocumentCount(::arc_ui64 value) { set_documentcount(value); }
  
  inline bool HasMaxDocsInChunk() const { return has_maxdocsinchunk(); }
  inline void ClearMaxDocsInChunk() { clear_maxdocsinchunk(); }
  inline ::arc_ui64 GetMaxDocsInChunk() const { return maxdocsinchunk();}
  inline void SetMaxDocsInChunk(::arc_ui64 value) { set_maxdocsinchunk(value); }
  
  inline size_t IgnoredColumnIndicesSize() const { return (size_t)ignoredcolumnindices_size(); }
  inline void ClearIgnoredColumnIndices() { clear_ignoredcolumnindices(); }
  inline ::arc_ui32 GetIgnoredColumnIndices(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return ignoredcolumnindices(_index); }
  inline void SetIgnoredColumnIndices(size_t _index, ::arc_ui32 value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_ignoredcolumnindices(_index, value); }
  inline void AddIgnoredColumnIndices(::arc_ui32 value) { add_ignoredcolumnindices(value); }
  inline ::arc_ui32 get_idx_ignoredcolumnindices(int _index) const { return ignoredcolumnindices(_index); }
  inline const ::google::protobuf::RepeatedField< ::arc_ui32 >&
      get_arr_ignoredcolumnindices() const { return ignoredcolumnindices(); }
  inline const ::google::protobuf::RepeatedField< ::arc_ui32 >&
      GetIgnoredColumnIndices() const { return ignoredcolumnindices(); }
  inline ::google::protobuf::RepeatedField< ::arc_ui32 >*
      MutableIgnoredColumnIndices() { return mutable_ignoredcolumnindices(); }
  
  inline bool HasStringDocIdFakeColumnIndex() const { return has_stringdocidfakecolumnindex(); }
  inline void ClearStringDocIdFakeColumnIndex() { clear_stringdocidfakecolumnindex(); }
  inline ::arc_ui32 GetStringDocIdFakeColumnIndex() const { return stringdocidfakecolumnindex();}
  inline void SetStringDocIdFakeColumnIndex(::arc_ui32 value) { set_stringdocidfakecolumnindex(value); }
  
  inline bool HasStringGroupIdFakeColumnIndex() const { return has_stringgroupidfakecolumnindex(); }
  inline void ClearStringGroupIdFakeColumnIndex() { clear_stringgroupidfakecolumnindex(); }
  inline ::arc_ui32 GetStringGroupIdFakeColumnIndex() const { return stringgroupidfakecolumnindex();}
  inline void SetStringGroupIdFakeColumnIndex(::arc_ui32 value) { set_stringgroupidfakecolumnindex(value); }
  
  inline bool HasStringSubgroupIdFakeColumnIndex() const { return has_stringsubgroupidfakecolumnindex(); }
  inline void ClearStringSubgroupIdFakeColumnIndex() { clear_stringsubgroupidfakecolumnindex(); }
  inline ::arc_ui32 GetStringSubgroupIdFakeColumnIndex() const { return stringsubgroupidfakecolumnindex();}
  inline void SetStringSubgroupIdFakeColumnIndex(::arc_ui32 value) { set_stringsubgroupidfakecolumnindex(value); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<TPoolMetainfo> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<TPoolMetainfo>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:NCB.NIdl.TPoolMetainfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TPoolMetainfo_ColumnIndexToTypeEntry_DoNotUse,
        ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_ENUM> columnindextotype_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32> ignoredcolumnindices_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TPoolMetainfo_ColumnIndexToNameEntry_DoNotUse,
        ::NProtoBuf::uint32, TProtoStringType,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> columnindextoname_;
    ::NProtoBuf::uint64 documentcount_;
    ::NProtoBuf::uint32 stringdocidfakecolumnindex_;
    ::NProtoBuf::uint32 stringgroupidfakecolumnindex_;
    ::NProtoBuf::uint64 maxdocsinchunk_;
    ::NProtoBuf::uint32 stringsubgroupidfakecolumnindex_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TPoolMetainfo

// map<uint32, .NCB.NIdl.EColumnType> ColumnIndexToType = 1;
inline int TPoolMetainfo::_internal_columnindextotype_size() const {
  return _impl_.columnindextotype_.size();
}
inline int TPoolMetainfo::columnindextotype_size() const {
  return _internal_columnindextotype_size();
}
inline void TPoolMetainfo::clear_columnindextotype() {
  _impl_.columnindextotype_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >&
TPoolMetainfo::_internal_columnindextotype() const {
  return _impl_.columnindextotype_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >&
TPoolMetainfo::columnindextotype() const {
  // @@protoc_insertion_point(field_map:NCB.NIdl.TPoolMetainfo.ColumnIndexToType)
  return _internal_columnindextotype();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >*
TPoolMetainfo::_internal_mutable_columnindextotype() {
  return _impl_.columnindextotype_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::EColumnType >*
TPoolMetainfo::mutable_columnindextotype() {
  // @@protoc_insertion_point(field_mutable_map:NCB.NIdl.TPoolMetainfo.ColumnIndexToType)
  return _internal_mutable_columnindextotype();
}

// map<uint32, string> ColumnIndexToName = 7;
inline int TPoolMetainfo::_internal_columnindextoname_size() const {
  return _impl_.columnindextoname_.size();
}
inline int TPoolMetainfo::columnindextoname_size() const {
  return _internal_columnindextoname_size();
}
inline void TPoolMetainfo::clear_columnindextoname() {
  _impl_.columnindextoname_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >&
TPoolMetainfo::_internal_columnindextoname() const {
  return _impl_.columnindextoname_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >&
TPoolMetainfo::columnindextoname() const {
  // @@protoc_insertion_point(field_map:NCB.NIdl.TPoolMetainfo.ColumnIndexToName)
  return _internal_columnindextoname();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >*
TPoolMetainfo::_internal_mutable_columnindextoname() {
  return _impl_.columnindextoname_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, TProtoStringType >*
TPoolMetainfo::mutable_columnindextoname() {
  // @@protoc_insertion_point(field_mutable_map:NCB.NIdl.TPoolMetainfo.ColumnIndexToName)
  return _internal_mutable_columnindextoname();
}

// optional uint64 DocumentCount = 2;
inline bool TPoolMetainfo::has_documentcount() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void TPoolMetainfo::clear_documentcount() {
  _impl_.documentcount_ = ::arc_ui64{0u};
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::NProtoBuf::uint64 TPoolMetainfo::documentcount() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolMetainfo.DocumentCount)
  return _internal_documentcount();
}
inline void TPoolMetainfo::set_documentcount(::NProtoBuf::uint64 value) {
  _internal_set_documentcount(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolMetainfo.DocumentCount)
}
inline ::NProtoBuf::uint64 TPoolMetainfo::_internal_documentcount() const {
  return _impl_.documentcount_;
}
inline void TPoolMetainfo::_internal_set_documentcount(::NProtoBuf::uint64 value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.documentcount_ = value;
}

// optional uint64 MaxDocsInChunk = 8;
inline bool TPoolMetainfo::has_maxdocsinchunk() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void TPoolMetainfo::clear_maxdocsinchunk() {
  _impl_.maxdocsinchunk_ = ::arc_ui64{0u};
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::NProtoBuf::uint64 TPoolMetainfo::maxdocsinchunk() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolMetainfo.MaxDocsInChunk)
  return _internal_maxdocsinchunk();
}
inline void TPoolMetainfo::set_maxdocsinchunk(::NProtoBuf::uint64 value) {
  _internal_set_maxdocsinchunk(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolMetainfo.MaxDocsInChunk)
}
inline ::NProtoBuf::uint64 TPoolMetainfo::_internal_maxdocsinchunk() const {
  return _impl_.maxdocsinchunk_;
}
inline void TPoolMetainfo::_internal_set_maxdocsinchunk(::NProtoBuf::uint64 value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.maxdocsinchunk_ = value;
}

// repeated uint32 IgnoredColumnIndices = 3;
inline int TPoolMetainfo::_internal_ignoredcolumnindices_size() const {
  return _impl_.ignoredcolumnindices_.size();
}
inline int TPoolMetainfo::ignoredcolumnindices_size() const {
  return _internal_ignoredcolumnindices_size();
}
inline void TPoolMetainfo::clear_ignoredcolumnindices() {
  _impl_.ignoredcolumnindices_.Clear();
}
inline ::NProtoBuf::uint32 TPoolMetainfo::ignoredcolumnindices(int index) const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolMetainfo.IgnoredColumnIndices)
  return _internal_ignoredcolumnindices(index);
}
inline void TPoolMetainfo::set_ignoredcolumnindices(int index, ::NProtoBuf::uint32 value) {
  _impl_.ignoredcolumnindices_.Set(index, value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolMetainfo.IgnoredColumnIndices)
}
inline void TPoolMetainfo::add_ignoredcolumnindices(::NProtoBuf::uint32 value) {
  _internal_add_ignoredcolumnindices(value);
  // @@protoc_insertion_point(field_add:NCB.NIdl.TPoolMetainfo.IgnoredColumnIndices)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>& TPoolMetainfo::ignoredcolumnindices() const {
  // @@protoc_insertion_point(field_list:NCB.NIdl.TPoolMetainfo.IgnoredColumnIndices)
  return _internal_ignoredcolumnindices();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>* TPoolMetainfo::mutable_ignoredcolumnindices() {
  // @@protoc_insertion_point(field_mutable_list:NCB.NIdl.TPoolMetainfo.IgnoredColumnIndices)
  return _internal_mutable_ignoredcolumnindices();
}

inline ::NProtoBuf::uint32 TPoolMetainfo::_internal_ignoredcolumnindices(int index) const {
  return _impl_.ignoredcolumnindices_.Get(index);
}
inline void TPoolMetainfo::_internal_add_ignoredcolumnindices(::NProtoBuf::uint32 value) { _impl_.ignoredcolumnindices_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>& TPoolMetainfo::_internal_ignoredcolumnindices() const {
  return _impl_.ignoredcolumnindices_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::uint32>* TPoolMetainfo::_internal_mutable_ignoredcolumnindices() {
  return &_impl_.ignoredcolumnindices_;
}

// optional uint32 StringDocIdFakeColumnIndex = 4;
inline bool TPoolMetainfo::has_stringdocidfakecolumnindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void TPoolMetainfo::clear_stringdocidfakecolumnindex() {
  _impl_.stringdocidfakecolumnindex_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::NProtoBuf::uint32 TPoolMetainfo::stringdocidfakecolumnindex() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolMetainfo.StringDocIdFakeColumnIndex)
  return _internal_stringdocidfakecolumnindex();
}
inline void TPoolMetainfo::set_stringdocidfakecolumnindex(::NProtoBuf::uint32 value) {
  _internal_set_stringdocidfakecolumnindex(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolMetainfo.StringDocIdFakeColumnIndex)
}
inline ::NProtoBuf::uint32 TPoolMetainfo::_internal_stringdocidfakecolumnindex() const {
  return _impl_.stringdocidfakecolumnindex_;
}
inline void TPoolMetainfo::_internal_set_stringdocidfakecolumnindex(::NProtoBuf::uint32 value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.stringdocidfakecolumnindex_ = value;
}

// optional uint32 StringGroupIdFakeColumnIndex = 5;
inline bool TPoolMetainfo::has_stringgroupidfakecolumnindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void TPoolMetainfo::clear_stringgroupidfakecolumnindex() {
  _impl_.stringgroupidfakecolumnindex_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::NProtoBuf::uint32 TPoolMetainfo::stringgroupidfakecolumnindex() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolMetainfo.StringGroupIdFakeColumnIndex)
  return _internal_stringgroupidfakecolumnindex();
}
inline void TPoolMetainfo::set_stringgroupidfakecolumnindex(::NProtoBuf::uint32 value) {
  _internal_set_stringgroupidfakecolumnindex(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolMetainfo.StringGroupIdFakeColumnIndex)
}
inline ::NProtoBuf::uint32 TPoolMetainfo::_internal_stringgroupidfakecolumnindex() const {
  return _impl_.stringgroupidfakecolumnindex_;
}
inline void TPoolMetainfo::_internal_set_stringgroupidfakecolumnindex(::NProtoBuf::uint32 value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.stringgroupidfakecolumnindex_ = value;
}

// optional uint32 StringSubgroupIdFakeColumnIndex = 6;
inline bool TPoolMetainfo::has_stringsubgroupidfakecolumnindex() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void TPoolMetainfo::clear_stringsubgroupidfakecolumnindex() {
  _impl_.stringsubgroupidfakecolumnindex_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::NProtoBuf::uint32 TPoolMetainfo::stringsubgroupidfakecolumnindex() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolMetainfo.StringSubgroupIdFakeColumnIndex)
  return _internal_stringsubgroupidfakecolumnindex();
}
inline void TPoolMetainfo::set_stringsubgroupidfakecolumnindex(::NProtoBuf::uint32 value) {
  _internal_set_stringsubgroupidfakecolumnindex(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolMetainfo.StringSubgroupIdFakeColumnIndex)
}
inline ::NProtoBuf::uint32 TPoolMetainfo::_internal_stringsubgroupidfakecolumnindex() const {
  return _impl_.stringsubgroupidfakecolumnindex_;
}
inline void TPoolMetainfo::_internal_set_stringsubgroupidfakecolumnindex(::NProtoBuf::uint32 value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.stringsubgroupidfakecolumnindex_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NIdl
}  // namespace NCB


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::NCB::NIdl::EColumnType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NCB::NIdl::EColumnType>() {
  return ::NCB::NIdl::EColumnType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_catboost_2fidl_2fpool_2fproto_2fmetainfo_2eproto_2epb_2eh
