// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catboost/idl/pool/proto/quantization_schema.proto

#include "catboost/idl/pool/proto/quantization_schema.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include <google/protobuf/messagext.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace NCB {
namespace NIdl {
PROTOBUF_CONSTEXPR TFeatureQuantizationSchema::TFeatureQuantizationSchema(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.borders_)*/ {}

  , /*decltype(_impl_.nanmode_)*/ 0
} {}
struct TFeatureQuantizationSchemaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TFeatureQuantizationSchemaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TFeatureQuantizationSchemaDefaultTypeInternal() {}
  union {
    TFeatureQuantizationSchema _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TFeatureQuantizationSchemaDefaultTypeInternal _TFeatureQuantizationSchema_default_instance_;
PROTOBUF_CONSTEXPR TValueWithCount::TValueWithCount(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.value_)*/ 0u

  , /*decltype(_impl_.count_)*/ 0u
} {}
struct TValueWithCountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TValueWithCountDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TValueWithCountDefaultTypeInternal() {}
  union {
    TValueWithCount _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TValueWithCountDefaultTypeInternal _TValueWithCount_default_instance_;
PROTOBUF_CONSTEXPR TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUseDefaultTypeInternal _TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR TCatFeatureQuantizationSchema::TCatFeatureQuantizationSchema(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.perfecthashes_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TCatFeatureQuantizationSchemaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TCatFeatureQuantizationSchemaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TCatFeatureQuantizationSchemaDefaultTypeInternal() {}
  union {
    TCatFeatureQuantizationSchema _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TCatFeatureQuantizationSchemaDefaultTypeInternal _TCatFeatureQuantizationSchema_default_instance_;
PROTOBUF_CONSTEXPR TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal _TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse(
    ::_pbi::ConstantInitialized) {}
struct TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal() {}
  union {
    TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal _TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse_default_instance_;
PROTOBUF_CONSTEXPR TPoolQuantizationSchema::TPoolQuantizationSchema(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.featureindextoschema_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.classnames_)*/{}
  , /*decltype(_impl_.catfeatureindextoschema_)*/{::_pbi::ConstantInitialized()}
  , /*decltype(_impl_.integerclasslabels_)*/ {}

  , /*decltype(_impl_.floatclasslabels_)*/ {}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TPoolQuantizationSchemaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TPoolQuantizationSchemaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TPoolQuantizationSchemaDefaultTypeInternal() {}
  union {
    TPoolQuantizationSchema _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TPoolQuantizationSchemaDefaultTypeInternal _TPoolQuantizationSchema_default_instance_;
}  // namespace NIdl
}  // namespace NCB
static ::_pb::Metadata file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[7];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto = nullptr;
const ::arc_ui32 TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TFeatureQuantizationSchema, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TFeatureQuantizationSchema, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TFeatureQuantizationSchema, _impl_.borders_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TFeatureQuantizationSchema, _impl_.nanmode_),
    ~0u,
    0,
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TValueWithCount, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TValueWithCount, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TValueWithCount, _impl_.value_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TValueWithCount, _impl_.count_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TCatFeatureQuantizationSchema, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TCatFeatureQuantizationSchema, _impl_.perfecthashes_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse, value_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema, _impl_.featureindextoschema_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema, _impl_.catfeatureindextoschema_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema, _impl_.integerclasslabels_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema, _impl_.floatclasslabels_),
    PROTOBUF_FIELD_OFFSET(::NCB::NIdl::TPoolQuantizationSchema, _impl_.classnames_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, 10, -1, sizeof(::NCB::NIdl::TFeatureQuantizationSchema)},
        { 12, 22, -1, sizeof(::NCB::NIdl::TValueWithCount)},
        { 24, 34, -1, sizeof(::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse)},
        { 36, -1, -1, sizeof(::NCB::NIdl::TCatFeatureQuantizationSchema)},
        { 45, 55, -1, sizeof(::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse)},
        { 57, 67, -1, sizeof(::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse)},
        { 69, -1, -1, sizeof(::NCB::NIdl::TPoolQuantizationSchema)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::NCB::NIdl::_TFeatureQuantizationSchema_default_instance_._instance,
    &::NCB::NIdl::_TValueWithCount_default_instance_._instance,
    &::NCB::NIdl::_TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse_default_instance_._instance,
    &::NCB::NIdl::_TCatFeatureQuantizationSchema_default_instance_._instance,
    &::NCB::NIdl::_TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse_default_instance_._instance,
    &::NCB::NIdl::_TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse_default_instance_._instance,
    &::NCB::NIdl::_TPoolQuantizationSchema_default_instance_._instance,
};
const char descriptor_table_protodef_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n1catboost/idl/pool/proto/quantization_s"
    "chema.proto\022\010NCB.NIdl\"R\n\032TFeatureQuantiz"
    "ationSchema\022\017\n\007Borders\030\001 \003(\002\022#\n\007NanMode\030"
    "\002 \001(\0162\022.NCB.NIdl.ENanMode\"/\n\017TValueWithC"
    "ount\022\r\n\005Value\030\001 \001(\r\022\r\n\005Count\030\002 \001(\r\"\303\001\n\035T"
    "CatFeatureQuantizationSchema\022Q\n\rPerfectH"
    "ashes\030\001 \003(\0132:.NCB.NIdl.TCatFeatureQuanti"
    "zationSchema.PerfectHashesEntry\032O\n\022Perfe"
    "ctHashesEntry\022\013\n\003key\030\001 \001(\r\022(\n\005value\030\002 \001("
    "\0132\031.NCB.NIdl.TValueWithCount:\0028\001\"\353\003\n\027TPo"
    "olQuantizationSchema\022Y\n\024FeatureIndexToSc"
    "hema\030\001 \003(\0132;.NCB.NIdl.TPoolQuantizationS"
    "chema.FeatureIndexToSchemaEntry\022_\n\027CatFe"
    "atureIndexToSchema\030\003 \003(\0132>.NCB.NIdl.TPoo"
    "lQuantizationSchema.CatFeatureIndexToSch"
    "emaEntry\022\032\n\022IntegerClassLabels\030\005 \003(\005\022\030\n\020"
    "FloatClassLabels\030\006 \003(\002\022\022\n\nClassNames\030\002 \003"
    "(\t\032a\n\031FeatureIndexToSchemaEntry\022\013\n\003key\030\001"
    " \001(\r\0223\n\005value\030\002 \001(\0132$.NCB.NIdl.TFeatureQ"
    "uantizationSchema:\0028\001\032g\n\034CatFeatureIndex"
    "ToSchemaEntry\022\013\n\003key\030\001 \001(\r\0226\n\005value\030\002 \001("
    "\0132\'.NCB.NIdl.TCatFeatureQuantizationSche"
    "ma:\0028\001*D\n\010ENanMode\022\016\n\nNM_UNKNOWN\020\000\022\n\n\006NM"
    "_MIN\020\001\022\n\n\006NM_MAX\020\002\022\020\n\014NM_FORBIDDEN\020\003"
};
static ::y_absl::once_flag descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto = {
    false,
    false,
    956,
    descriptor_table_protodef_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto,
    "catboost/idl/pool/proto/quantization_schema.proto",
    &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto::offsets,
    file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto,
    file_level_enum_descriptors_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto,
    file_level_service_descriptors_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter() {
  return &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto(&descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto);
namespace NCB {
namespace NIdl {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ENanMode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto);
  return file_level_enum_descriptors_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[0];
}
bool ENanMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}
// ===================================================================

class TFeatureQuantizationSchema::_Internal {
 public:
  using HasBits = decltype(std::declval<TFeatureQuantizationSchema>()._impl_._has_bits_);
  static constexpr ::arc_i32 kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(TFeatureQuantizationSchema, _impl_._has_bits_);
  static void set_has_nanmode(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

TFeatureQuantizationSchema::TFeatureQuantizationSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NCB.NIdl.TFeatureQuantizationSchema)
}
TFeatureQuantizationSchema::TFeatureQuantizationSchema(const TFeatureQuantizationSchema& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TFeatureQuantizationSchema* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.borders_) { from._impl_.borders_ }

    , decltype(_impl_.nanmode_) {}
  };

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.nanmode_ = from._impl_.nanmode_;
  // @@protoc_insertion_point(copy_constructor:NCB.NIdl.TFeatureQuantizationSchema)
}

inline void TFeatureQuantizationSchema::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.borders_) { arena }

    , decltype(_impl_.nanmode_) { 0 }

  };
}

TFeatureQuantizationSchema::~TFeatureQuantizationSchema() {
  // @@protoc_insertion_point(destructor:NCB.NIdl.TFeatureQuantizationSchema)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TFeatureQuantizationSchema::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.borders_.~RepeatedField();
}

void TFeatureQuantizationSchema::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TFeatureQuantizationSchema::Clear() {
// @@protoc_insertion_point(message_clear_start:NCB.NIdl.TFeatureQuantizationSchema)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.borders_.Clear();
  _impl_.nanmode_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TFeatureQuantizationSchema::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float Borders = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 13)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_borders(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
            ptr += sizeof(float);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<13>(ptr));
        } else if (static_cast<::uint8_t>(tag) == 10) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_borders(), ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional .NCB.NIdl.ENanMode NanMode = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          ::arc_ui32 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::NCB::NIdl::ENanMode_IsValid(static_cast<int>(val)))) {
            _internal_set_nanmode(static_cast<::NCB::NIdl::ENanMode>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(2, val, mutable_unknown_fields());
          }
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TFeatureQuantizationSchema::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NCB.NIdl.TFeatureQuantizationSchema)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float Borders = 1;
  for (int i = 0, n = this->_internal_borders_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this->_internal_borders(i), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // optional .NCB.NIdl.ENanMode NanMode = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        2, this->_internal_nanmode(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NCB.NIdl.TFeatureQuantizationSchema)
  return target;
}

::size_t TFeatureQuantizationSchema::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NCB.NIdl.TFeatureQuantizationSchema)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float Borders = 1;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_borders_size())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_borders_size());
    ;
    total_size += tag_size + data_size;
  }

  // optional .NCB.NIdl.ENanMode NanMode = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_nanmode());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TFeatureQuantizationSchema::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TFeatureQuantizationSchema::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TFeatureQuantizationSchema::GetClassData() const { return &_class_data_; }


void TFeatureQuantizationSchema::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TFeatureQuantizationSchema*>(&to_msg);
  auto& from = static_cast<const TFeatureQuantizationSchema&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NCB.NIdl.TFeatureQuantizationSchema)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.borders_.MergeFrom(from._impl_.borders_);
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_nanmode(from._internal_nanmode());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TFeatureQuantizationSchema::CopyFrom(const TFeatureQuantizationSchema& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NCB.NIdl.TFeatureQuantizationSchema)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TFeatureQuantizationSchema::IsInitialized() const {
  return true;
}

void TFeatureQuantizationSchema::InternalSwap(TFeatureQuantizationSchema* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.borders_.InternalSwap(&other->_impl_.borders_);
  swap(_impl_.nanmode_, other->_impl_.nanmode_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TFeatureQuantizationSchema::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[0]);
}
// ===================================================================

class TValueWithCount::_Internal {
 public:
  using HasBits = decltype(std::declval<TValueWithCount>()._impl_._has_bits_);
  static constexpr ::arc_i32 kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(TValueWithCount, _impl_._has_bits_);
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_count(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

TValueWithCount::TValueWithCount(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NCB.NIdl.TValueWithCount)
}
TValueWithCount::TValueWithCount(const TValueWithCount& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(), _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(
      from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:NCB.NIdl.TValueWithCount)
}

inline void TValueWithCount::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.value_) { 0u }

    , decltype(_impl_.count_) { 0u }

  };
}

TValueWithCount::~TValueWithCount() {
  // @@protoc_insertion_point(destructor:NCB.NIdl.TValueWithCount)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TValueWithCount::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
}

void TValueWithCount::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TValueWithCount::Clear() {
// @@protoc_insertion_point(message_clear_start:NCB.NIdl.TValueWithCount)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    ::memset(&_impl_.value_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.count_) -
        reinterpret_cast<char*>(&_impl_.value_)) + sizeof(_impl_.count_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TValueWithCount::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 Value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 8)) {
          _Internal::set_has_value(&has_bits);
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // optional uint32 Count = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 16)) {
          _Internal::set_has_count(&has_bits);
          _impl_.count_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TValueWithCount::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NCB.NIdl.TValueWithCount)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional uint32 Value = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_value(), target);
  }

  // optional uint32 Count = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_count(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NCB.NIdl.TValueWithCount)
  return target;
}

::size_t TValueWithCount::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NCB.NIdl.TValueWithCount)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional uint32 Value = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_value());
    }

    // optional uint32 Count = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_count());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TValueWithCount::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TValueWithCount::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TValueWithCount::GetClassData() const { return &_class_data_; }


void TValueWithCount::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TValueWithCount*>(&to_msg);
  auto& from = static_cast<const TValueWithCount&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NCB.NIdl.TValueWithCount)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.value_ = from._impl_.value_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.count_ = from._impl_.count_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TValueWithCount::CopyFrom(const TValueWithCount& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NCB.NIdl.TValueWithCount)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TValueWithCount::IsInitialized() const {
  return true;
}

void TValueWithCount::InternalSwap(TValueWithCount* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TValueWithCount, _impl_.count_)
      + sizeof(TValueWithCount::_impl_.count_)
      - PROTOBUF_FIELD_OFFSET(TValueWithCount, _impl_.value_)>(
          reinterpret_cast<char*>(&_impl_.value_),
          reinterpret_cast<char*>(&other->_impl_.value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TValueWithCount::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[1]);
}
// ===================================================================

TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse() {}
TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::MergeFrom(const TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[2]);
}
// ===================================================================

class TCatFeatureQuantizationSchema::_Internal {
 public:
};

TCatFeatureQuantizationSchema::TCatFeatureQuantizationSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &TCatFeatureQuantizationSchema::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:NCB.NIdl.TCatFeatureQuantizationSchema)
}
TCatFeatureQuantizationSchema::TCatFeatureQuantizationSchema(const TCatFeatureQuantizationSchema& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TCatFeatureQuantizationSchema* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.perfecthashes_)*/{}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.perfecthashes_.MergeFrom(from._impl_.perfecthashes_);
  // @@protoc_insertion_point(copy_constructor:NCB.NIdl.TCatFeatureQuantizationSchema)
}

inline void TCatFeatureQuantizationSchema::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      /*decltype(_impl_.perfecthashes_)*/{::_pbi::ArenaInitialized(), arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TCatFeatureQuantizationSchema::~TCatFeatureQuantizationSchema() {
  // @@protoc_insertion_point(destructor:NCB.NIdl.TCatFeatureQuantizationSchema)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void TCatFeatureQuantizationSchema::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.perfecthashes_.Destruct();
  _impl_.perfecthashes_.~MapField();
}

void TCatFeatureQuantizationSchema::ArenaDtor(void* object) {
  TCatFeatureQuantizationSchema* _this = reinterpret_cast< TCatFeatureQuantizationSchema* >(object);
  _this->_impl_.perfecthashes_.Destruct();
}
void TCatFeatureQuantizationSchema::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TCatFeatureQuantizationSchema::Clear() {
// @@protoc_insertion_point(message_clear_start:NCB.NIdl.TCatFeatureQuantizationSchema)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.perfecthashes_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TCatFeatureQuantizationSchema::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<uint32, .NCB.NIdl.TValueWithCount> PerfectHashes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.perfecthashes_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TCatFeatureQuantizationSchema::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NCB.NIdl.TCatFeatureQuantizationSchema)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<uint32, .NCB.NIdl.TValueWithCount> PerfectHashes = 1;
  if (!this->_internal_perfecthashes().empty()) {
    using MapType = ::_pb::Map<::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount>;
    using WireHelper = TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_perfecthashes();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NCB.NIdl.TCatFeatureQuantizationSchema)
  return target;
}

::size_t TCatFeatureQuantizationSchema::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NCB.NIdl.TCatFeatureQuantizationSchema)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint32, .NCB.NIdl.TValueWithCount> PerfectHashes = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_perfecthashes_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >::const_iterator
      it = this->_internal_perfecthashes().begin();
      it != this->_internal_perfecthashes().end(); ++it) {
    total_size += TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TCatFeatureQuantizationSchema::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TCatFeatureQuantizationSchema::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TCatFeatureQuantizationSchema::GetClassData() const { return &_class_data_; }


void TCatFeatureQuantizationSchema::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TCatFeatureQuantizationSchema*>(&to_msg);
  auto& from = static_cast<const TCatFeatureQuantizationSchema&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NCB.NIdl.TCatFeatureQuantizationSchema)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.perfecthashes_.MergeFrom(from._impl_.perfecthashes_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TCatFeatureQuantizationSchema::CopyFrom(const TCatFeatureQuantizationSchema& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NCB.NIdl.TCatFeatureQuantizationSchema)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TCatFeatureQuantizationSchema::IsInitialized() const {
  return true;
}

void TCatFeatureQuantizationSchema::InternalSwap(TCatFeatureQuantizationSchema* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.perfecthashes_.InternalSwap(&other->_impl_.perfecthashes_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TCatFeatureQuantizationSchema::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[3]);
}
// ===================================================================

TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse() {}
TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::MergeFrom(const TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[4]);
}
// ===================================================================

TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse() {}
TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::MergeFrom(const TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[5]);
}
// ===================================================================

class TPoolQuantizationSchema::_Internal {
 public:
};

TPoolQuantizationSchema::TPoolQuantizationSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &TPoolQuantizationSchema::ArenaDtor);
  }
  // @@protoc_insertion_point(arena_constructor:NCB.NIdl.TPoolQuantizationSchema)
}
TPoolQuantizationSchema::TPoolQuantizationSchema(const TPoolQuantizationSchema& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TPoolQuantizationSchema* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      /*decltype(_impl_.featureindextoschema_)*/{}
    , decltype(_impl_.classnames_){from._impl_.classnames_}
    , /*decltype(_impl_.catfeatureindextoschema_)*/{}
    , decltype(_impl_.integerclasslabels_) { from._impl_.integerclasslabels_ }

    , decltype(_impl_.floatclasslabels_) { from._impl_.floatclasslabels_ }

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.featureindextoschema_.MergeFrom(from._impl_.featureindextoschema_);
  _this->_impl_.catfeatureindextoschema_.MergeFrom(from._impl_.catfeatureindextoschema_);
  // @@protoc_insertion_point(copy_constructor:NCB.NIdl.TPoolQuantizationSchema)
}

inline void TPoolQuantizationSchema::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      /*decltype(_impl_.featureindextoschema_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.classnames_){arena}
    , /*decltype(_impl_.catfeatureindextoschema_)*/{::_pbi::ArenaInitialized(), arena}
    , decltype(_impl_.integerclasslabels_) { arena }

    , decltype(_impl_.floatclasslabels_) { arena }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TPoolQuantizationSchema::~TPoolQuantizationSchema() {
  // @@protoc_insertion_point(destructor:NCB.NIdl.TPoolQuantizationSchema)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    ArenaDtor(this);
    return;
  }
  SharedDtor();
}

inline void TPoolQuantizationSchema::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.featureindextoschema_.Destruct();
  _impl_.featureindextoschema_.~MapField();
  _impl_.classnames_.~RepeatedPtrField();
  _impl_.catfeatureindextoschema_.Destruct();
  _impl_.catfeatureindextoschema_.~MapField();
  _impl_.integerclasslabels_.~RepeatedField();
  _impl_.floatclasslabels_.~RepeatedField();
}

void TPoolQuantizationSchema::ArenaDtor(void* object) {
  TPoolQuantizationSchema* _this = reinterpret_cast< TPoolQuantizationSchema* >(object);
  _this->_impl_.featureindextoschema_.Destruct();
  _this->_impl_.catfeatureindextoschema_.Destruct();
}
void TPoolQuantizationSchema::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TPoolQuantizationSchema::Clear() {
// @@protoc_insertion_point(message_clear_start:NCB.NIdl.TPoolQuantizationSchema)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.featureindextoschema_.Clear();
  _impl_.classnames_.Clear();
  _impl_.catfeatureindextoschema_.Clear();
  _impl_.integerclasslabels_.Clear();
  _impl_.floatclasslabels_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TPoolQuantizationSchema::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<uint32, .NCB.NIdl.TFeatureQuantizationSchema> FeatureIndexToSchema = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.featureindextoschema_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated string ClassNames = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_classnames();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            #ifndef NDEBUG
            ::_pbi::VerifyUTF8(str, "NCB.NIdl.TPoolQuantizationSchema.ClassNames");
            #endif  // !NDEBUG
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // map<uint32, .NCB.NIdl.TCatFeatureQuantizationSchema> CatFeatureIndexToSchema = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&_impl_.catfeatureindextoschema_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated int32 IntegerClassLabels = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 40)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_integerclasslabels(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<40>(ptr));
        } else if (static_cast<::uint8_t>(tag) == 42) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_integerclasslabels(), ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated float FloatClassLabels = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 53)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_floatclasslabels(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
            ptr += sizeof(float);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<53>(ptr));
        } else if (static_cast<::uint8_t>(tag) == 50) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_floatclasslabels(), ptr, ctx);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* TPoolQuantizationSchema::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NCB.NIdl.TPoolQuantizationSchema)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<uint32, .NCB.NIdl.TFeatureQuantizationSchema> FeatureIndexToSchema = 1;
  if (!this->_internal_featureindextoschema().empty()) {
    using MapType = ::_pb::Map<::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema>;
    using WireHelper = TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_featureindextoschema();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(1, entry.first, entry.second, target, stream);
      }
    }
  }

  // repeated string ClassNames = 2;
  for (int i = 0, n = this->_internal_classnames_size(); i < n; ++i) {
    const auto& s = this->_internal_classnames(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(s.data(), static_cast<int>(s.length()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
                                "NCB.NIdl.TPoolQuantizationSchema.ClassNames");
    target = stream->WriteString(2, s, target);
  }

  // map<uint32, .NCB.NIdl.TCatFeatureQuantizationSchema> CatFeatureIndexToSchema = 3;
  if (!this->_internal_catfeatureindextoschema().empty()) {
    using MapType = ::_pb::Map<::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema>;
    using WireHelper = TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::Funcs;
    const auto& map_field = this->_internal_catfeatureindextoschema();

    if (stream->IsSerializationDeterministic() && map_field.size() > 1) {
      for (const auto& entry : ::_pbi::MapSorterFlat<MapType>(map_field)) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
      }
    } else {
      for (const auto& entry : map_field) {
        target = WireHelper::InternalSerialize(3, entry.first, entry.second, target, stream);
      }
    }
  }

  // repeated int32 IntegerClassLabels = 5;
  for (int i = 0, n = this->_internal_integerclasslabels_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(
        5, this->_internal_integerclasslabels(i), target);
  }

  // repeated float FloatClassLabels = 6;
  for (int i = 0, n = this->_internal_floatclasslabels_size(); i < n; ++i) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        6, this->_internal_floatclasslabels(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NCB.NIdl.TPoolQuantizationSchema)
  return target;
}

::size_t TPoolQuantizationSchema::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NCB.NIdl.TPoolQuantizationSchema)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<uint32, .NCB.NIdl.TFeatureQuantizationSchema> FeatureIndexToSchema = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_featureindextoschema_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >::const_iterator
      it = this->_internal_featureindextoschema().begin();
      it != this->_internal_featureindextoschema().end(); ++it) {
    total_size += TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // repeated string ClassNames = 2;
  total_size += 1 * ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.classnames_.size());
  for (int i = 0, n = _impl_.classnames_.size(); i < n; ++i) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(_impl_.classnames_.Get(i));
  }

  // map<uint32, .NCB.NIdl.TCatFeatureQuantizationSchema> CatFeatureIndexToSchema = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_catfeatureindextoschema_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >::const_iterator
      it = this->_internal_catfeatureindextoschema().begin();
      it != this->_internal_catfeatureindextoschema().end(); ++it) {
    total_size += TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // repeated int32 IntegerClassLabels = 5;
  {
    std::size_t data_size = ::_pbi::WireFormatLite::Int32Size(this->_impl_.integerclasslabels_)
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_integerclasslabels_size());
    ;
    total_size += tag_size + data_size;
  }

  // repeated float FloatClassLabels = 6;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_floatclasslabels_size())
    ;
    std::size_t tag_size = std::size_t{1} *
        ::_pbi::FromIntSize(this->_internal_floatclasslabels_size());
    ;
    total_size += tag_size + data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TPoolQuantizationSchema::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TPoolQuantizationSchema::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TPoolQuantizationSchema::GetClassData() const { return &_class_data_; }


void TPoolQuantizationSchema::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TPoolQuantizationSchema*>(&to_msg);
  auto& from = static_cast<const TPoolQuantizationSchema&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NCB.NIdl.TPoolQuantizationSchema)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.featureindextoschema_.MergeFrom(from._impl_.featureindextoschema_);
  _this->_impl_.classnames_.MergeFrom(from._impl_.classnames_);
  _this->_impl_.catfeatureindextoschema_.MergeFrom(from._impl_.catfeatureindextoschema_);
  _this->_impl_.integerclasslabels_.MergeFrom(from._impl_.integerclasslabels_);
  _this->_impl_.floatclasslabels_.MergeFrom(from._impl_.floatclasslabels_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TPoolQuantizationSchema::CopyFrom(const TPoolQuantizationSchema& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NCB.NIdl.TPoolQuantizationSchema)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TPoolQuantizationSchema::IsInitialized() const {
  return true;
}

void TPoolQuantizationSchema::InternalSwap(TPoolQuantizationSchema* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.featureindextoschema_.InternalSwap(&other->_impl_.featureindextoschema_);
  _impl_.classnames_.InternalSwap(&other->_impl_.classnames_);
  _impl_.catfeatureindextoschema_.InternalSwap(&other->_impl_.catfeatureindextoschema_);
  _impl_.integerclasslabels_.InternalSwap(&other->_impl_.integerclasslabels_);
  _impl_.floatclasslabels_.InternalSwap(&other->_impl_.floatclasslabels_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TPoolQuantizationSchema::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_getter, &descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_once,
      file_level_metadata_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto[6]);
}
// Yandex-specific extension
TProtoStringType TFeatureQuantizationSchema::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void TFeatureQuantizationSchema::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TFeatureQuantizationSchema::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::NCB::NIdl::TFeatureQuantizationSchema::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (BordersSize() > 0) {
    out << sep;
    out << "\"Borders\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < BordersSize(); ++_index) {
        out << separator;
        out << double(GetBorders(_index));
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  if (HasNanMode()) {
    out << sep;
    out << "\"NanMode\":";
    out << (int)GetNanMode();
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
TProtoStringType TValueWithCount::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void TValueWithCount::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TValueWithCount::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::NCB::NIdl::TValueWithCount::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (HasValue()) {
    out << sep;
    out << "\"Value\":";
    out << GetValue();
    sep = ",";
  }
  if (HasCount()) {
    out << sep;
    out << "\"Count\":";
    out << GetCount();
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
TProtoStringType TCatFeatureQuantizationSchema::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void TCatFeatureQuantizationSchema::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TCatFeatureQuantizationSchema::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::NCB::NIdl::TCatFeatureQuantizationSchema::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (PerfectHashesSize() > 0) {
    out << sep;
    out << "\"PerfectHashes\":";
    out << '{';
    const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TValueWithCount>& map = GetPerfectHashes();
    for (auto it = map.begin(); it != map.end(); ++it) {
      if (it != map.begin()) { out << ','; }
      out << '"' << it->first << '"';
      out << ':';
      it->second.PrintJSON(out);
    }
    out << '}';
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// Yandex-specific extension
TProtoStringType TPoolQuantizationSchema::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void TPoolQuantizationSchema::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void TPoolQuantizationSchema::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::NCB::NIdl::TPoolQuantizationSchema::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (FeatureIndexToSchemaSize() > 0) {
    out << sep;
    out << "\"FeatureIndexToSchema\":";
    out << '{';
    const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TFeatureQuantizationSchema>& map = GetFeatureIndexToSchema();
    for (auto it = map.begin(); it != map.end(); ++it) {
      if (it != map.begin()) { out << ','; }
      out << '"' << it->first << '"';
      out << ':';
      it->second.PrintJSON(out);
    }
    out << '}';
    sep = ",";
  }
  if (CatFeatureIndexToSchemaSize() > 0) {
    out << sep;
    out << "\"CatFeatureIndexToSchema\":";
    out << '{';
    const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TCatFeatureQuantizationSchema>& map = GetCatFeatureIndexToSchema();
    for (auto it = map.begin(); it != map.end(); ++it) {
      if (it != map.begin()) { out << ','; }
      out << '"' << it->first << '"';
      out << ':';
      it->second.PrintJSON(out);
    }
    out << '}';
    sep = ",";
  }
  if (IntegerClassLabelsSize() > 0) {
    out << sep;
    out << "\"IntegerClassLabels\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < IntegerClassLabelsSize(); ++_index) {
        out << separator;
        out << GetIntegerClassLabels(_index);
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  if (FloatClassLabelsSize() > 0) {
    out << sep;
    out << "\"FloatClassLabels\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < FloatClassLabelsSize(); ++_index) {
        out << separator;
        out << double(GetFloatClassLabels(_index));
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  if (ClassNamesSize() > 0) {
    out << sep;
    out << "\"ClassNames\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < ClassNamesSize(); ++_index) {
        out << separator;
        ::google::protobuf::io::PrintJSONString(out, GetClassNames(_index));
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// @@protoc_insertion_point(namespace_scope)
}  // namespace NIdl
}  // namespace NCB
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TFeatureQuantizationSchema*
Arena::CreateMaybeMessage< ::NCB::NIdl::TFeatureQuantizationSchema >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TFeatureQuantizationSchema >(arena);
}
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TValueWithCount*
Arena::CreateMaybeMessage< ::NCB::NIdl::TValueWithCount >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TValueWithCount >(arena);
}
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse*
Arena::CreateMaybeMessage< ::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TCatFeatureQuantizationSchema*
Arena::CreateMaybeMessage< ::NCB::NIdl::TCatFeatureQuantizationSchema >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TCatFeatureQuantizationSchema >(arena);
}
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse*
Arena::CreateMaybeMessage< ::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse*
Arena::CreateMaybeMessage< ::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::NCB::NIdl::TPoolQuantizationSchema*
Arena::CreateMaybeMessage< ::NCB::NIdl::TPoolQuantizationSchema >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NCB::NIdl::TPoolQuantizationSchema >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// Yandex debug output extension
template<>
void Out< ::NCB::NIdl::TFeatureQuantizationSchema>(IOutputStream& out, const ::NCB::NIdl::TFeatureQuantizationSchema& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::NCB::NIdl::TValueWithCount>(IOutputStream& out, const ::NCB::NIdl::TValueWithCount& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::NCB::NIdl::TCatFeatureQuantizationSchema>(IOutputStream& out, const ::NCB::NIdl::TCatFeatureQuantizationSchema& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// Yandex debug output extension
template<>
void Out< ::NCB::NIdl::TPoolQuantizationSchema>(IOutputStream& out, const ::NCB::NIdl::TPoolQuantizationSchema& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
