// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catboost/idl/pool/proto/quantization_schema.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022005 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/map.h"  // IWYU pragma: export
#include "google/protobuf/map_entry.h"
#include "google/protobuf/map_field_inl.h"
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include <google/protobuf/json_util.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto {
  static const ::arc_ui32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
namespace NCB {
namespace NIdl {
class TCatFeatureQuantizationSchema;
struct TCatFeatureQuantizationSchemaDefaultTypeInternal;
extern TCatFeatureQuantizationSchemaDefaultTypeInternal _TCatFeatureQuantizationSchema_default_instance_;
class TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse;
struct TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUseDefaultTypeInternal;
extern TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUseDefaultTypeInternal _TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse_default_instance_;
class TFeatureQuantizationSchema;
struct TFeatureQuantizationSchemaDefaultTypeInternal;
extern TFeatureQuantizationSchemaDefaultTypeInternal _TFeatureQuantizationSchema_default_instance_;
class TPoolQuantizationSchema;
struct TPoolQuantizationSchemaDefaultTypeInternal;
extern TPoolQuantizationSchemaDefaultTypeInternal _TPoolQuantizationSchema_default_instance_;
class TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse;
struct TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal;
extern TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal _TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse_default_instance_;
class TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse;
struct TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal;
extern TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUseDefaultTypeInternal _TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse_default_instance_;
class TValueWithCount;
struct TValueWithCountDefaultTypeInternal;
extern TValueWithCountDefaultTypeInternal _TValueWithCount_default_instance_;
}  // namespace NIdl
}  // namespace NCB
PROTOBUF_NAMESPACE_OPEN
template <>
::NCB::NIdl::TCatFeatureQuantizationSchema* Arena::CreateMaybeMessage<::NCB::NIdl::TCatFeatureQuantizationSchema>(Arena*);
template <>
::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse* Arena::CreateMaybeMessage<::NCB::NIdl::TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse>(Arena*);
template <>
::NCB::NIdl::TFeatureQuantizationSchema* Arena::CreateMaybeMessage<::NCB::NIdl::TFeatureQuantizationSchema>(Arena*);
template <>
::NCB::NIdl::TPoolQuantizationSchema* Arena::CreateMaybeMessage<::NCB::NIdl::TPoolQuantizationSchema>(Arena*);
template <>
::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse* Arena::CreateMaybeMessage<::NCB::NIdl::TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse>(Arena*);
template <>
::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse* Arena::CreateMaybeMessage<::NCB::NIdl::TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse>(Arena*);
template <>
::NCB::NIdl::TValueWithCount* Arena::CreateMaybeMessage<::NCB::NIdl::TValueWithCount>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace NCB {
namespace NIdl {
enum ENanMode : int {
  NM_UNKNOWN = 0,
  NM_MIN = 1,
  NM_MAX = 2,
  NM_FORBIDDEN = 3,
};

bool ENanMode_IsValid(int value);
constexpr ENanMode ENanMode_MIN = static_cast<ENanMode>(0);
constexpr ENanMode ENanMode_MAX = static_cast<ENanMode>(3);
constexpr int ENanMode_ARRAYSIZE = 3 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
ENanMode_descriptor();
template <typename T>
const TProtoStringType& ENanMode_Name(T value) {
  static_assert(std::is_same<T, ENanMode>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ENanMode_Name().");
  return ENanMode_Name(static_cast<ENanMode>(value));
}
template <>
inline const TProtoStringType& ENanMode_Name(ENanMode value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<ENanMode_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool ENanMode_Parse(y_absl::string_view name, ENanMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ENanMode>(
      ENanMode_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class TFeatureQuantizationSchema :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NCB.NIdl.TFeatureQuantizationSchema) */ {
 public:
  inline TFeatureQuantizationSchema() : TFeatureQuantizationSchema(nullptr) {}
  ~TFeatureQuantizationSchema() override;
  explicit PROTOBUF_CONSTEXPR TFeatureQuantizationSchema(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TFeatureQuantizationSchema(const TFeatureQuantizationSchema& from);
  TFeatureQuantizationSchema(TFeatureQuantizationSchema&& from) noexcept
    : TFeatureQuantizationSchema() {
    *this = ::std::move(from);
  }

  inline TFeatureQuantizationSchema& operator=(const TFeatureQuantizationSchema& from) {
    CopyFrom(from);
    return *this;
  }
  inline TFeatureQuantizationSchema& operator=(TFeatureQuantizationSchema&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TFeatureQuantizationSchema& default_instance() {
    return *internal_default_instance();
  }
  static inline const TFeatureQuantizationSchema* internal_default_instance() {
    return reinterpret_cast<const TFeatureQuantizationSchema*>(
               &_TFeatureQuantizationSchema_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TFeatureQuantizationSchema& a, TFeatureQuantizationSchema& b) {
    a.Swap(&b);
  }
  inline void Swap(TFeatureQuantizationSchema* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TFeatureQuantizationSchema* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TFeatureQuantizationSchema* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TFeatureQuantizationSchema>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TFeatureQuantizationSchema& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TFeatureQuantizationSchema& from) {
    TFeatureQuantizationSchema::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TFeatureQuantizationSchema* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "NCB.NIdl.TFeatureQuantizationSchema";
  }
  protected:
  explicit TFeatureQuantizationSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBordersFieldNumber = 1,
    kNanModeFieldNumber = 2,
  };
  // repeated float Borders = 1;
  int borders_size() const;
  private:
  int _internal_borders_size() const;

  public:
  void clear_borders() ;
  float borders(int index) const;
  void set_borders(int index, float value);
  void add_borders(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& borders() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* mutable_borders();

  private:
  float _internal_borders(int index) const;
  void _internal_add_borders(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& _internal_borders() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* _internal_mutable_borders();

  public:
  // optional .NCB.NIdl.ENanMode NanMode = 2;
  bool has_nanmode() const;
  void clear_nanmode() ;
  ::NCB::NIdl::ENanMode nanmode() const;
  void set_nanmode(::NCB::NIdl::ENanMode value);

  private:
  ::NCB::NIdl::ENanMode _internal_nanmode() const;
  void _internal_set_nanmode(::NCB::NIdl::ENanMode value);

  public:
  // Yandex cpp-styleguide extension
  inline size_t BordersSize() const { return (size_t)borders_size(); }
  inline void ClearBorders() { clear_borders(); }
  inline float GetBorders(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return borders(_index); }
  inline void SetBorders(size_t _index, float value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_borders(_index, value); }
  inline void AddBorders(float value) { add_borders(value); }
  inline float get_idx_borders(int _index) const { return borders(_index); }
  inline const ::google::protobuf::RepeatedField< float >&
      get_arr_borders() const { return borders(); }
  inline const ::google::protobuf::RepeatedField< float >&
      GetBorders() const { return borders(); }
  inline ::google::protobuf::RepeatedField< float >*
      MutableBorders() { return mutable_borders(); }
  
  inline bool HasNanMode() const { return has_nanmode(); }
  inline void ClearNanMode() { clear_nanmode(); }
  inline ::NCB::NIdl::ENanMode GetNanMode() const { return nanmode(); }
  inline void SetNanMode(::NCB::NIdl::ENanMode value) { set_nanmode(value); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<TFeatureQuantizationSchema> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<TFeatureQuantizationSchema>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:NCB.NIdl.TFeatureQuantizationSchema)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<float> borders_;
    int nanmode_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};// -------------------------------------------------------------------

class TValueWithCount :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NCB.NIdl.TValueWithCount) */ {
 public:
  inline TValueWithCount() : TValueWithCount(nullptr) {}
  ~TValueWithCount() override;
  explicit PROTOBUF_CONSTEXPR TValueWithCount(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TValueWithCount(const TValueWithCount& from);
  TValueWithCount(TValueWithCount&& from) noexcept
    : TValueWithCount() {
    *this = ::std::move(from);
  }

  inline TValueWithCount& operator=(const TValueWithCount& from) {
    CopyFrom(from);
    return *this;
  }
  inline TValueWithCount& operator=(TValueWithCount&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TValueWithCount& default_instance() {
    return *internal_default_instance();
  }
  static inline const TValueWithCount* internal_default_instance() {
    return reinterpret_cast<const TValueWithCount*>(
               &_TValueWithCount_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(TValueWithCount& a, TValueWithCount& b) {
    a.Swap(&b);
  }
  inline void Swap(TValueWithCount* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TValueWithCount* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TValueWithCount* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TValueWithCount>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TValueWithCount& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TValueWithCount& from) {
    TValueWithCount::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TValueWithCount* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "NCB.NIdl.TValueWithCount";
  }
  protected:
  explicit TValueWithCount(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
    kCountFieldNumber = 2,
  };
  // optional uint32 Value = 1;
  bool has_value() const;
  void clear_value() ;
  ::NProtoBuf::uint32 value() const;
  void set_value(::NProtoBuf::uint32 value);

  private:
  ::NProtoBuf::uint32 _internal_value() const;
  void _internal_set_value(::NProtoBuf::uint32 value);

  public:
  // optional uint32 Count = 2;
  bool has_count() const;
  void clear_count() ;
  ::NProtoBuf::uint32 count() const;
  void set_count(::NProtoBuf::uint32 value);

  private:
  ::NProtoBuf::uint32 _internal_count() const;
  void _internal_set_count(::NProtoBuf::uint32 value);

  public:
  // Yandex cpp-styleguide extension
  inline bool HasValue() const { return has_value(); }
  inline void ClearValue() { clear_value(); }
  inline ::arc_ui32 GetValue() const { return value();}
  inline void SetValue(::arc_ui32 value) { set_value(value); }
  
  inline bool HasCount() const { return has_count(); }
  inline void ClearCount() { clear_count(); }
  inline ::arc_ui32 GetCount() const { return count();}
  inline void SetCount(::arc_ui32 value) { set_count(value); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<TValueWithCount> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<TValueWithCount>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:NCB.NIdl.TValueWithCount)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::NProtoBuf::uint32 value_;
    ::NProtoBuf::uint32 count_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};// -------------------------------------------------------------------

class TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse& other);
  static const TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse*>(&_TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};
// -------------------------------------------------------------------

class TCatFeatureQuantizationSchema :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NCB.NIdl.TCatFeatureQuantizationSchema) */ {
 public:
  inline TCatFeatureQuantizationSchema() : TCatFeatureQuantizationSchema(nullptr) {}
  ~TCatFeatureQuantizationSchema() override;
  explicit PROTOBUF_CONSTEXPR TCatFeatureQuantizationSchema(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TCatFeatureQuantizationSchema(const TCatFeatureQuantizationSchema& from);
  TCatFeatureQuantizationSchema(TCatFeatureQuantizationSchema&& from) noexcept
    : TCatFeatureQuantizationSchema() {
    *this = ::std::move(from);
  }

  inline TCatFeatureQuantizationSchema& operator=(const TCatFeatureQuantizationSchema& from) {
    CopyFrom(from);
    return *this;
  }
  inline TCatFeatureQuantizationSchema& operator=(TCatFeatureQuantizationSchema&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TCatFeatureQuantizationSchema& default_instance() {
    return *internal_default_instance();
  }
  static inline const TCatFeatureQuantizationSchema* internal_default_instance() {
    return reinterpret_cast<const TCatFeatureQuantizationSchema*>(
               &_TCatFeatureQuantizationSchema_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TCatFeatureQuantizationSchema& a, TCatFeatureQuantizationSchema& b) {
    a.Swap(&b);
  }
  inline void Swap(TCatFeatureQuantizationSchema* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TCatFeatureQuantizationSchema* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TCatFeatureQuantizationSchema* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TCatFeatureQuantizationSchema>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TCatFeatureQuantizationSchema& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TCatFeatureQuantizationSchema& from) {
    TCatFeatureQuantizationSchema::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TCatFeatureQuantizationSchema* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "NCB.NIdl.TCatFeatureQuantizationSchema";
  }
  protected:
  explicit TCatFeatureQuantizationSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kPerfectHashesFieldNumber = 1,
  };
  // map<uint32, .NCB.NIdl.TValueWithCount> PerfectHashes = 1;
  int perfecthashes_size() const;
  private:
  int _internal_perfecthashes_size() const;

  public:
  void clear_perfecthashes() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >&
      _internal_perfecthashes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >*
      _internal_mutable_perfecthashes();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >&
      perfecthashes() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >*
      mutable_perfecthashes();
  // Yandex cpp-styleguide extension
  inline size_t PerfectHashesSize() const { return (size_t)perfecthashes_size(); }
  inline void ClearPerfectHashes() { clear_perfecthashes(); }
  inline const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TValueWithCount>& GetPerfectHashes() const { return perfecthashes(); }
  inline ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TValueWithCount>* MutablePerfectHashes() { return mutable_perfecthashes(); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<TCatFeatureQuantizationSchema> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<TCatFeatureQuantizationSchema>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:NCB.NIdl.TCatFeatureQuantizationSchema)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TCatFeatureQuantizationSchema_PerfectHashesEntry_DoNotUse,
        ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> perfecthashes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};// -------------------------------------------------------------------

class TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse& other);
  static const TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse*>(&_TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};
// -------------------------------------------------------------------

class TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse, 
    ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse& other);
  static const TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse*>(&_TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};
// -------------------------------------------------------------------

class TPoolQuantizationSchema :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NCB.NIdl.TPoolQuantizationSchema) */ {
 public:
  inline TPoolQuantizationSchema() : TPoolQuantizationSchema(nullptr) {}
  ~TPoolQuantizationSchema() override;
  explicit PROTOBUF_CONSTEXPR TPoolQuantizationSchema(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TPoolQuantizationSchema(const TPoolQuantizationSchema& from);
  TPoolQuantizationSchema(TPoolQuantizationSchema&& from) noexcept
    : TPoolQuantizationSchema() {
    *this = ::std::move(from);
  }

  inline TPoolQuantizationSchema& operator=(const TPoolQuantizationSchema& from) {
    CopyFrom(from);
    return *this;
  }
  inline TPoolQuantizationSchema& operator=(TPoolQuantizationSchema&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TPoolQuantizationSchema& default_instance() {
    return *internal_default_instance();
  }
  static inline const TPoolQuantizationSchema* internal_default_instance() {
    return reinterpret_cast<const TPoolQuantizationSchema*>(
               &_TPoolQuantizationSchema_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(TPoolQuantizationSchema& a, TPoolQuantizationSchema& b) {
    a.Swap(&b);
  }
  inline void Swap(TPoolQuantizationSchema* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TPoolQuantizationSchema* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TPoolQuantizationSchema* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TPoolQuantizationSchema>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TPoolQuantizationSchema& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TPoolQuantizationSchema& from) {
    TPoolQuantizationSchema::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TPoolQuantizationSchema* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "NCB.NIdl.TPoolQuantizationSchema";
  }
  protected:
  explicit TPoolQuantizationSchema(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kFeatureIndexToSchemaFieldNumber = 1,
    kClassNamesFieldNumber = 2,
    kCatFeatureIndexToSchemaFieldNumber = 3,
    kIntegerClassLabelsFieldNumber = 5,
    kFloatClassLabelsFieldNumber = 6,
  };
  // map<uint32, .NCB.NIdl.TFeatureQuantizationSchema> FeatureIndexToSchema = 1;
  int featureindextoschema_size() const;
  private:
  int _internal_featureindextoschema_size() const;

  public:
  void clear_featureindextoschema() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >&
      _internal_featureindextoschema() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >*
      _internal_mutable_featureindextoschema();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >&
      featureindextoschema() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >*
      mutable_featureindextoschema();
  // repeated string ClassNames = 2;
  int classnames_size() const;
  private:
  int _internal_classnames_size() const;

  public:
  void clear_classnames() ;
  const TProtoStringType& classnames(int index) const;
  TProtoStringType* mutable_classnames(int index);
  void set_classnames(int index, const TProtoStringType& value);
  void set_classnames(int index, TProtoStringType&& value);
  void set_classnames(int index, const char* value);
  void set_classnames(int index, const char* value, std::size_t size);
  void set_classnames(int index, y_absl::string_view value);
  void set_classnames(int index, std::string&& value) {
    return set_classnames(index, TProtoStringType(std::move(value)));
  }
  TProtoStringType* add_classnames();
  void add_classnames(const TProtoStringType& value);
  void add_classnames(TProtoStringType&& value);
  void add_classnames(const char* value);
  void add_classnames(const char* value, std::size_t size);
  void add_classnames(y_absl::string_view value);
  void add_classnames(std::string&& value) {
    return add_classnames(TProtoStringType(std::move(value)));
  }
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<TProtoStringType>& classnames() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<TProtoStringType>* mutable_classnames();

  private:
  const TProtoStringType& _internal_classnames(int index) const;
  TProtoStringType* _internal_add_classnames();

  public:
  // map<uint32, .NCB.NIdl.TCatFeatureQuantizationSchema> CatFeatureIndexToSchema = 3;
  int catfeatureindextoschema_size() const;
  private:
  int _internal_catfeatureindextoschema_size() const;

  public:
  void clear_catfeatureindextoschema() ;
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >&
      _internal_catfeatureindextoschema() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >*
      _internal_mutable_catfeatureindextoschema();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >&
      catfeatureindextoschema() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >*
      mutable_catfeatureindextoschema();
  // repeated int32 IntegerClassLabels = 5;
  int integerclasslabels_size() const;
  private:
  int _internal_integerclasslabels_size() const;

  public:
  void clear_integerclasslabels() ;
  ::NProtoBuf::int32 integerclasslabels(int index) const;
  void set_integerclasslabels(int index, ::NProtoBuf::int32 value);
  void add_integerclasslabels(::NProtoBuf::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>& integerclasslabels() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>* mutable_integerclasslabels();

  private:
  ::NProtoBuf::int32 _internal_integerclasslabels(int index) const;
  void _internal_add_integerclasslabels(::NProtoBuf::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>& _internal_integerclasslabels() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>* _internal_mutable_integerclasslabels();

  public:
  // repeated float FloatClassLabels = 6;
  int floatclasslabels_size() const;
  private:
  int _internal_floatclasslabels_size() const;

  public:
  void clear_floatclasslabels() ;
  float floatclasslabels(int index) const;
  void set_floatclasslabels(int index, float value);
  void add_floatclasslabels(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& floatclasslabels() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* mutable_floatclasslabels();

  private:
  float _internal_floatclasslabels(int index) const;
  void _internal_add_floatclasslabels(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& _internal_floatclasslabels() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* _internal_mutable_floatclasslabels();

  public:
  // Yandex cpp-styleguide extension
  inline size_t FeatureIndexToSchemaSize() const { return (size_t)featureindextoschema_size(); }
  inline void ClearFeatureIndexToSchema() { clear_featureindextoschema(); }
  inline const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TFeatureQuantizationSchema>& GetFeatureIndexToSchema() const { return featureindextoschema(); }
  inline ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TFeatureQuantizationSchema>* MutableFeatureIndexToSchema() { return mutable_featureindextoschema(); }
  
  inline size_t CatFeatureIndexToSchemaSize() const { return (size_t)catfeatureindextoschema_size(); }
  inline void ClearCatFeatureIndexToSchema() { clear_catfeatureindextoschema(); }
  inline const ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TCatFeatureQuantizationSchema>& GetCatFeatureIndexToSchema() const { return catfeatureindextoschema(); }
  inline ::google::protobuf::Map<::arc_ui32, ::NCB::NIdl::TCatFeatureQuantizationSchema>* MutableCatFeatureIndexToSchema() { return mutable_catfeatureindextoschema(); }
  
  inline size_t IntegerClassLabelsSize() const { return (size_t)integerclasslabels_size(); }
  inline void ClearIntegerClassLabels() { clear_integerclasslabels(); }
  inline ::arc_i32 GetIntegerClassLabels(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return integerclasslabels(_index); }
  inline void SetIntegerClassLabels(size_t _index, ::arc_i32 value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_integerclasslabels(_index, value); }
  inline void AddIntegerClassLabels(::arc_i32 value) { add_integerclasslabels(value); }
  inline ::arc_i32 get_idx_integerclasslabels(int _index) const { return integerclasslabels(_index); }
  inline const ::google::protobuf::RepeatedField< ::arc_i32 >&
      get_arr_integerclasslabels() const { return integerclasslabels(); }
  inline const ::google::protobuf::RepeatedField< ::arc_i32 >&
      GetIntegerClassLabels() const { return integerclasslabels(); }
  inline ::google::protobuf::RepeatedField< ::arc_i32 >*
      MutableIntegerClassLabels() { return mutable_integerclasslabels(); }
  
  inline size_t FloatClassLabelsSize() const { return (size_t)floatclasslabels_size(); }
  inline void ClearFloatClassLabels() { clear_floatclasslabels(); }
  inline float GetFloatClassLabels(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return floatclasslabels(_index); }
  inline void SetFloatClassLabels(size_t _index, float value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_floatclasslabels(_index, value); }
  inline void AddFloatClassLabels(float value) { add_floatclasslabels(value); }
  inline float get_idx_floatclasslabels(int _index) const { return floatclasslabels(_index); }
  inline const ::google::protobuf::RepeatedField< float >&
      get_arr_floatclasslabels() const { return floatclasslabels(); }
  inline const ::google::protobuf::RepeatedField< float >&
      GetFloatClassLabels() const { return floatclasslabels(); }
  inline ::google::protobuf::RepeatedField< float >*
      MutableFloatClassLabels() { return mutable_floatclasslabels(); }
  
  inline size_t ClassNamesSize() const { return (size_t)classnames_size(); }
  inline void ClearClassNames() { clear_classnames(); }
  inline const TProtoStringType& GetClassNames(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return classnames(_index); }
  inline TProtoStringType* MutableClassNames(size_t _index) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return mutable_classnames(_index); }
  inline void SetClassNames(size_t _index, const TProtoStringType& value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_classnames(_index, value); }
  inline void SetClassNames(size_t _index, TProtoStringType&& value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_classnames(_index, std::move(value)); }
  inline void SetClassNames(size_t _index, const char* value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_classnames(_index, value); }
  inline void SetClassNames(size_t _index, const char* value, size_t size) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_classnames(_index, value, size); }
  inline TProtoStringType* AddClassNames() { return add_classnames(); }
  inline void AddClassNames(const TProtoStringType& value) { add_classnames(value); }
  inline void AddClassNames(TProtoStringType&& value) { add_classnames(std::move(value)); }
  inline void AddClassNames(const char* value) { add_classnames(value); }
  inline void AddClassNames(const char* value, size_t size) { add_classnames(value, size); }
  inline const TProtoStringType& get_idx_classnames(int _index) const { return classnames(_index); }
  inline const ::google::protobuf::RepeatedPtrField<TProtoStringType>& get_arr_classnames() const{ return classnames(); }
  inline const ::google::protobuf::RepeatedPtrField<TProtoStringType>& GetClassNames() const{ return classnames(); }
  inline ::google::protobuf::RepeatedPtrField<TProtoStringType>* MutableClassNames(){ return mutable_classnames(); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<TPoolQuantizationSchema> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<TPoolQuantizationSchema>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:NCB.NIdl.TPoolQuantizationSchema)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TPoolQuantizationSchema_FeatureIndexToSchemaEntry_DoNotUse,
        ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> featureindextoschema_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<TProtoStringType> classnames_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        TPoolQuantizationSchema_CatFeatureIndexToSchemaEntry_DoNotUse,
        ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_UINT32,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> catfeatureindextoschema_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32> integerclasslabels_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<float> floatclasslabels_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// TFeatureQuantizationSchema

// repeated float Borders = 1;
inline int TFeatureQuantizationSchema::_internal_borders_size() const {
  return _impl_.borders_.size();
}
inline int TFeatureQuantizationSchema::borders_size() const {
  return _internal_borders_size();
}
inline void TFeatureQuantizationSchema::clear_borders() {
  _impl_.borders_.Clear();
}
inline float TFeatureQuantizationSchema::borders(int index) const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TFeatureQuantizationSchema.Borders)
  return _internal_borders(index);
}
inline void TFeatureQuantizationSchema::set_borders(int index, float value) {
  _impl_.borders_.Set(index, value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TFeatureQuantizationSchema.Borders)
}
inline void TFeatureQuantizationSchema::add_borders(float value) {
  _internal_add_borders(value);
  // @@protoc_insertion_point(field_add:NCB.NIdl.TFeatureQuantizationSchema.Borders)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& TFeatureQuantizationSchema::borders() const {
  // @@protoc_insertion_point(field_list:NCB.NIdl.TFeatureQuantizationSchema.Borders)
  return _internal_borders();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* TFeatureQuantizationSchema::mutable_borders() {
  // @@protoc_insertion_point(field_mutable_list:NCB.NIdl.TFeatureQuantizationSchema.Borders)
  return _internal_mutable_borders();
}

inline float TFeatureQuantizationSchema::_internal_borders(int index) const {
  return _impl_.borders_.Get(index);
}
inline void TFeatureQuantizationSchema::_internal_add_borders(float value) { _impl_.borders_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& TFeatureQuantizationSchema::_internal_borders() const {
  return _impl_.borders_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* TFeatureQuantizationSchema::_internal_mutable_borders() {
  return &_impl_.borders_;
}

// optional .NCB.NIdl.ENanMode NanMode = 2;
inline bool TFeatureQuantizationSchema::has_nanmode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void TFeatureQuantizationSchema::clear_nanmode() {
  _impl_.nanmode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::NCB::NIdl::ENanMode TFeatureQuantizationSchema::nanmode() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TFeatureQuantizationSchema.NanMode)
  return _internal_nanmode();
}
inline void TFeatureQuantizationSchema::set_nanmode(::NCB::NIdl::ENanMode value) {
   _internal_set_nanmode(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TFeatureQuantizationSchema.NanMode)
}
inline ::NCB::NIdl::ENanMode TFeatureQuantizationSchema::_internal_nanmode() const {
  return static_cast<::NCB::NIdl::ENanMode>(_impl_.nanmode_);
}
inline void TFeatureQuantizationSchema::_internal_set_nanmode(::NCB::NIdl::ENanMode value) {
  assert(::NCB::NIdl::ENanMode_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.nanmode_ = value;
}

// -------------------------------------------------------------------

// TValueWithCount

// optional uint32 Value = 1;
inline bool TValueWithCount::has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void TValueWithCount::clear_value() {
  _impl_.value_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::NProtoBuf::uint32 TValueWithCount::value() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TValueWithCount.Value)
  return _internal_value();
}
inline void TValueWithCount::set_value(::NProtoBuf::uint32 value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TValueWithCount.Value)
}
inline ::NProtoBuf::uint32 TValueWithCount::_internal_value() const {
  return _impl_.value_;
}
inline void TValueWithCount::_internal_set_value(::NProtoBuf::uint32 value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.value_ = value;
}

// optional uint32 Count = 2;
inline bool TValueWithCount::has_count() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void TValueWithCount::clear_count() {
  _impl_.count_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::NProtoBuf::uint32 TValueWithCount::count() const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TValueWithCount.Count)
  return _internal_count();
}
inline void TValueWithCount::set_count(::NProtoBuf::uint32 value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TValueWithCount.Count)
}
inline ::NProtoBuf::uint32 TValueWithCount::_internal_count() const {
  return _impl_.count_;
}
inline void TValueWithCount::_internal_set_count(::NProtoBuf::uint32 value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.count_ = value;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TCatFeatureQuantizationSchema

// map<uint32, .NCB.NIdl.TValueWithCount> PerfectHashes = 1;
inline int TCatFeatureQuantizationSchema::_internal_perfecthashes_size() const {
  return _impl_.perfecthashes_.size();
}
inline int TCatFeatureQuantizationSchema::perfecthashes_size() const {
  return _internal_perfecthashes_size();
}
inline void TCatFeatureQuantizationSchema::clear_perfecthashes() {
  _impl_.perfecthashes_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >&
TCatFeatureQuantizationSchema::_internal_perfecthashes() const {
  return _impl_.perfecthashes_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >&
TCatFeatureQuantizationSchema::perfecthashes() const {
  // @@protoc_insertion_point(field_map:NCB.NIdl.TCatFeatureQuantizationSchema.PerfectHashes)
  return _internal_perfecthashes();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >*
TCatFeatureQuantizationSchema::_internal_mutable_perfecthashes() {
  return _impl_.perfecthashes_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TValueWithCount >*
TCatFeatureQuantizationSchema::mutable_perfecthashes() {
  // @@protoc_insertion_point(field_mutable_map:NCB.NIdl.TCatFeatureQuantizationSchema.PerfectHashes)
  return _internal_mutable_perfecthashes();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TPoolQuantizationSchema

// map<uint32, .NCB.NIdl.TFeatureQuantizationSchema> FeatureIndexToSchema = 1;
inline int TPoolQuantizationSchema::_internal_featureindextoschema_size() const {
  return _impl_.featureindextoschema_.size();
}
inline int TPoolQuantizationSchema::featureindextoschema_size() const {
  return _internal_featureindextoschema_size();
}
inline void TPoolQuantizationSchema::clear_featureindextoschema() {
  _impl_.featureindextoschema_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >&
TPoolQuantizationSchema::_internal_featureindextoschema() const {
  return _impl_.featureindextoschema_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >&
TPoolQuantizationSchema::featureindextoschema() const {
  // @@protoc_insertion_point(field_map:NCB.NIdl.TPoolQuantizationSchema.FeatureIndexToSchema)
  return _internal_featureindextoschema();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >*
TPoolQuantizationSchema::_internal_mutable_featureindextoschema() {
  return _impl_.featureindextoschema_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TFeatureQuantizationSchema >*
TPoolQuantizationSchema::mutable_featureindextoschema() {
  // @@protoc_insertion_point(field_mutable_map:NCB.NIdl.TPoolQuantizationSchema.FeatureIndexToSchema)
  return _internal_mutable_featureindextoschema();
}

// map<uint32, .NCB.NIdl.TCatFeatureQuantizationSchema> CatFeatureIndexToSchema = 3;
inline int TPoolQuantizationSchema::_internal_catfeatureindextoschema_size() const {
  return _impl_.catfeatureindextoschema_.size();
}
inline int TPoolQuantizationSchema::catfeatureindextoschema_size() const {
  return _internal_catfeatureindextoschema_size();
}
inline void TPoolQuantizationSchema::clear_catfeatureindextoschema() {
  _impl_.catfeatureindextoschema_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >&
TPoolQuantizationSchema::_internal_catfeatureindextoschema() const {
  return _impl_.catfeatureindextoschema_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >&
TPoolQuantizationSchema::catfeatureindextoschema() const {
  // @@protoc_insertion_point(field_map:NCB.NIdl.TPoolQuantizationSchema.CatFeatureIndexToSchema)
  return _internal_catfeatureindextoschema();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >*
TPoolQuantizationSchema::_internal_mutable_catfeatureindextoschema() {
  return _impl_.catfeatureindextoschema_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::NProtoBuf::uint32, ::NCB::NIdl::TCatFeatureQuantizationSchema >*
TPoolQuantizationSchema::mutable_catfeatureindextoschema() {
  // @@protoc_insertion_point(field_mutable_map:NCB.NIdl.TPoolQuantizationSchema.CatFeatureIndexToSchema)
  return _internal_mutable_catfeatureindextoschema();
}

// repeated int32 IntegerClassLabels = 5;
inline int TPoolQuantizationSchema::_internal_integerclasslabels_size() const {
  return _impl_.integerclasslabels_.size();
}
inline int TPoolQuantizationSchema::integerclasslabels_size() const {
  return _internal_integerclasslabels_size();
}
inline void TPoolQuantizationSchema::clear_integerclasslabels() {
  _impl_.integerclasslabels_.Clear();
}
inline ::NProtoBuf::int32 TPoolQuantizationSchema::integerclasslabels(int index) const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolQuantizationSchema.IntegerClassLabels)
  return _internal_integerclasslabels(index);
}
inline void TPoolQuantizationSchema::set_integerclasslabels(int index, ::NProtoBuf::int32 value) {
  _impl_.integerclasslabels_.Set(index, value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolQuantizationSchema.IntegerClassLabels)
}
inline void TPoolQuantizationSchema::add_integerclasslabels(::NProtoBuf::int32 value) {
  _internal_add_integerclasslabels(value);
  // @@protoc_insertion_point(field_add:NCB.NIdl.TPoolQuantizationSchema.IntegerClassLabels)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>& TPoolQuantizationSchema::integerclasslabels() const {
  // @@protoc_insertion_point(field_list:NCB.NIdl.TPoolQuantizationSchema.IntegerClassLabels)
  return _internal_integerclasslabels();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>* TPoolQuantizationSchema::mutable_integerclasslabels() {
  // @@protoc_insertion_point(field_mutable_list:NCB.NIdl.TPoolQuantizationSchema.IntegerClassLabels)
  return _internal_mutable_integerclasslabels();
}

inline ::NProtoBuf::int32 TPoolQuantizationSchema::_internal_integerclasslabels(int index) const {
  return _impl_.integerclasslabels_.Get(index);
}
inline void TPoolQuantizationSchema::_internal_add_integerclasslabels(::NProtoBuf::int32 value) { _impl_.integerclasslabels_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>& TPoolQuantizationSchema::_internal_integerclasslabels() const {
  return _impl_.integerclasslabels_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<::NProtoBuf::int32>* TPoolQuantizationSchema::_internal_mutable_integerclasslabels() {
  return &_impl_.integerclasslabels_;
}

// repeated float FloatClassLabels = 6;
inline int TPoolQuantizationSchema::_internal_floatclasslabels_size() const {
  return _impl_.floatclasslabels_.size();
}
inline int TPoolQuantizationSchema::floatclasslabels_size() const {
  return _internal_floatclasslabels_size();
}
inline void TPoolQuantizationSchema::clear_floatclasslabels() {
  _impl_.floatclasslabels_.Clear();
}
inline float TPoolQuantizationSchema::floatclasslabels(int index) const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolQuantizationSchema.FloatClassLabels)
  return _internal_floatclasslabels(index);
}
inline void TPoolQuantizationSchema::set_floatclasslabels(int index, float value) {
  _impl_.floatclasslabels_.Set(index, value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolQuantizationSchema.FloatClassLabels)
}
inline void TPoolQuantizationSchema::add_floatclasslabels(float value) {
  _internal_add_floatclasslabels(value);
  // @@protoc_insertion_point(field_add:NCB.NIdl.TPoolQuantizationSchema.FloatClassLabels)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& TPoolQuantizationSchema::floatclasslabels() const {
  // @@protoc_insertion_point(field_list:NCB.NIdl.TPoolQuantizationSchema.FloatClassLabels)
  return _internal_floatclasslabels();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* TPoolQuantizationSchema::mutable_floatclasslabels() {
  // @@protoc_insertion_point(field_mutable_list:NCB.NIdl.TPoolQuantizationSchema.FloatClassLabels)
  return _internal_mutable_floatclasslabels();
}

inline float TPoolQuantizationSchema::_internal_floatclasslabels(int index) const {
  return _impl_.floatclasslabels_.Get(index);
}
inline void TPoolQuantizationSchema::_internal_add_floatclasslabels(float value) { _impl_.floatclasslabels_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>& TPoolQuantizationSchema::_internal_floatclasslabels() const {
  return _impl_.floatclasslabels_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<float>* TPoolQuantizationSchema::_internal_mutable_floatclasslabels() {
  return &_impl_.floatclasslabels_;
}

// repeated string ClassNames = 2;
inline int TPoolQuantizationSchema::_internal_classnames_size() const {
  return _impl_.classnames_.size();
}
inline int TPoolQuantizationSchema::classnames_size() const {
  return _internal_classnames_size();
}
inline void TPoolQuantizationSchema::clear_classnames() {
  _impl_.classnames_.Clear();
}
inline TProtoStringType* TPoolQuantizationSchema::add_classnames() {
  TProtoStringType* _s = _internal_add_classnames();
  // @@protoc_insertion_point(field_add_mutable:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
  return _s;
}
inline const TProtoStringType& TPoolQuantizationSchema::_internal_classnames(int index) const {
  return _impl_.classnames_.Get(index);
}
inline const TProtoStringType& TPoolQuantizationSchema::classnames(int index) const {
  // @@protoc_insertion_point(field_get:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
  return _internal_classnames(index);
}
inline TProtoStringType* TPoolQuantizationSchema::mutable_classnames(int index) {
  // @@protoc_insertion_point(field_mutable:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
  return _impl_.classnames_.Mutable(index);
}
inline void TPoolQuantizationSchema::set_classnames(int index, const TProtoStringType& value) {
  _impl_.classnames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::set_classnames(int index, TProtoStringType&& value) {
  _impl_.classnames_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::set_classnames(int index, const char* value) {
  Y_ABSL_DCHECK(value != nullptr);
  _impl_.classnames_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::set_classnames(int index, const char* value,
                              std::size_t size) {
  _impl_.classnames_.Mutable(index)->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::set_classnames(int index, y_absl::string_view value) {
  _impl_.classnames_.Mutable(index)->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_set_string_piece:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline TProtoStringType* TPoolQuantizationSchema::_internal_add_classnames() { return _impl_.classnames_.Add(); }
inline void TPoolQuantizationSchema::add_classnames(const TProtoStringType& value) {
  _impl_.classnames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::add_classnames(TProtoStringType&& value) {
  _impl_.classnames_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::add_classnames(const char* value) {
  Y_ABSL_DCHECK(value != nullptr);
  _impl_.classnames_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::add_classnames(const char* value, std::size_t size) {
  _impl_.classnames_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline void TPoolQuantizationSchema::add_classnames(y_absl::string_view value) {
  _impl_.classnames_.Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<TProtoStringType>&
TPoolQuantizationSchema::classnames() const {
  // @@protoc_insertion_point(field_list:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
  return _impl_.classnames_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<TProtoStringType>* TPoolQuantizationSchema::mutable_classnames() {
  // @@protoc_insertion_point(field_mutable_list:NCB.NIdl.TPoolQuantizationSchema.ClassNames)
  return &_impl_.classnames_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace NIdl
}  // namespace NCB


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::NCB::NIdl::ENanMode> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::NCB::NIdl::ENanMode>() {
  return ::NCB::NIdl::ENanMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_catboost_2fidl_2fpool_2fproto_2fquantization_5fschema_2eproto_2epb_2eh
