// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/coreml/DictVectorizer.proto

#include "contrib/libs/coreml/DictVectorizer.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include <google/protobuf/messagext.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace CoreML {
namespace Specification {
PROTOBUF_CONSTEXPR DictVectorizer::DictVectorizer(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.Map_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct DictVectorizerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DictVectorizerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DictVectorizerDefaultTypeInternal() {}
  union {
    DictVectorizer _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DictVectorizerDefaultTypeInternal _DictVectorizer_default_instance_;
}  // namespace Specification
}  // namespace CoreML
static ::_pb::Metadata file_level_metadata_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto = nullptr;
const ::arc_ui32 TableStruct_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::DictVectorizer, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::DictVectorizer, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::DictVectorizer, _impl_.Map_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::CoreML::Specification::DictVectorizer)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::CoreML::Specification::_DictVectorizer_default_instance_._instance,
};
const char descriptor_table_protodef_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n(contrib/libs/coreml/DictVectorizer.pro"
    "to\022\024CoreML.Specification\032(contrib/libs/c"
    "oreml/DataStructures.proto\"\217\001\n\016DictVecto"
    "rizer\022;\n\rstringToIndex\030\001 \001(\0132\".CoreML.Sp"
    "ecification.StringVectorH\000\0229\n\014int64ToInd"
    "ex\030\002 \001(\0132!.CoreML.Specification.Int64Vec"
    "torH\000B\005\n\003MapP\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_deps[1] =
    {
        &::descriptor_table_contrib_2flibs_2fcoreml_2fDataStructures_2eproto,
};
static ::y_absl::once_flag descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto = {
    false,
    false,
    262,
    descriptor_table_protodef_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto,
    "contrib/libs/coreml/DictVectorizer.proto",
    &descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_once,
    descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto::offsets,
    file_level_metadata_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto,
    file_level_enum_descriptors_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto,
    file_level_service_descriptors_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_getter() {
  return &descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto(&descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto);
namespace CoreML {
namespace Specification {
// ===================================================================

class DictVectorizer::_Internal {
 public:
  static constexpr ::arc_i32 kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::DictVectorizer, _impl_._oneof_case_);
  static const ::CoreML::Specification::StringVector& stringtoindex(const DictVectorizer* msg);
  static const ::CoreML::Specification::Int64Vector& int64toindex(const DictVectorizer* msg);
};

const ::CoreML::Specification::StringVector&
DictVectorizer::_Internal::stringtoindex(const DictVectorizer* msg) {
  return *msg->_impl_.Map_.stringtoindex_;
}
const ::CoreML::Specification::Int64Vector&
DictVectorizer::_Internal::int64toindex(const DictVectorizer* msg) {
  return *msg->_impl_.Map_.int64toindex_;
}
void DictVectorizer::set_allocated_stringtoindex(::CoreML::Specification::StringVector* stringtoindex) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Map();
  if (stringtoindex) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stringtoindex));
    if (message_arena != submessage_arena) {
      stringtoindex = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stringtoindex, submessage_arena);
    }
    set_has_stringtoindex();
    _impl_.Map_.stringtoindex_ = stringtoindex;
  }
  // @@protoc_insertion_point(field_set_allocated:CoreML.Specification.DictVectorizer.stringToIndex)
}
void DictVectorizer::clear_stringtoindex() {
  if (Map_case() == kStringToIndex) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.Map_.stringtoindex_;
    }
    clear_has_Map();
  }
}
void DictVectorizer::set_allocated_int64toindex(::CoreML::Specification::Int64Vector* int64toindex) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_Map();
  if (int64toindex) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(int64toindex));
    if (message_arena != submessage_arena) {
      int64toindex = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, int64toindex, submessage_arena);
    }
    set_has_int64toindex();
    _impl_.Map_.int64toindex_ = int64toindex;
  }
  // @@protoc_insertion_point(field_set_allocated:CoreML.Specification.DictVectorizer.int64ToIndex)
}
void DictVectorizer::clear_int64toindex() {
  if (Map_case() == kInt64ToIndex) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.Map_.int64toindex_;
    }
    clear_has_Map();
  }
}
DictVectorizer::DictVectorizer(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CoreML.Specification.DictVectorizer)
}
DictVectorizer::DictVectorizer(const DictVectorizer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DictVectorizer* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.Map_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_Map();
  switch (from.Map_case()) {
    case kStringToIndex: {
      _this->_internal_mutable_stringtoindex()->::CoreML::Specification::StringVector::MergeFrom(
          from._internal_stringtoindex());
      break;
    }
    case kInt64ToIndex: {
      _this->_internal_mutable_int64toindex()->::CoreML::Specification::Int64Vector::MergeFrom(
          from._internal_int64toindex());
      break;
    }
    case MAP_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:CoreML.Specification.DictVectorizer)
}

inline void DictVectorizer::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.Map_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_Map();
}

DictVectorizer::~DictVectorizer() {
  // @@protoc_insertion_point(destructor:CoreML.Specification.DictVectorizer)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DictVectorizer::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_Map()) {
    clear_Map();
  }
}

void DictVectorizer::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DictVectorizer::clear_Map() {
// @@protoc_insertion_point(one_of_clear_start:CoreML.Specification.DictVectorizer)
  switch (Map_case()) {
    case kStringToIndex: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.Map_.stringtoindex_;
      }
      break;
    }
    case kInt64ToIndex: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.Map_.int64toindex_;
      }
      break;
    }
    case MAP_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = MAP_NOT_SET;
}


void DictVectorizer::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreML.Specification.DictVectorizer)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_Map();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DictVectorizer::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .CoreML.Specification.StringVector stringToIndex = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_stringtoindex(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .CoreML.Specification.Int64Vector int64ToIndex = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_int64toindex(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* DictVectorizer::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CoreML.Specification.DictVectorizer)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .CoreML.Specification.StringVector stringToIndex = 1;
  if (Map_case() == kStringToIndex) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::stringtoindex(this),
        _Internal::stringtoindex(this).GetCachedSize(), target, stream);
  }

  // .CoreML.Specification.Int64Vector int64ToIndex = 2;
  if (Map_case() == kInt64ToIndex) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::int64toindex(this),
        _Internal::int64toindex(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreML.Specification.DictVectorizer)
  return target;
}

::size_t DictVectorizer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreML.Specification.DictVectorizer)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (Map_case()) {
    // .CoreML.Specification.StringVector stringToIndex = 1;
    case kStringToIndex: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.Map_.stringtoindex_);
      break;
    }
    // .CoreML.Specification.Int64Vector int64ToIndex = 2;
    case kInt64ToIndex: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.Map_.int64toindex_);
      break;
    }
    case MAP_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DictVectorizer::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DictVectorizer::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DictVectorizer::GetClassData() const { return &_class_data_; }


void DictVectorizer::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DictVectorizer*>(&to_msg);
  auto& from = static_cast<const DictVectorizer&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CoreML.Specification.DictVectorizer)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.Map_case()) {
    case kStringToIndex: {
      _this->_internal_mutable_stringtoindex()->::CoreML::Specification::StringVector::MergeFrom(
          from._internal_stringtoindex());
      break;
    }
    case kInt64ToIndex: {
      _this->_internal_mutable_int64toindex()->::CoreML::Specification::Int64Vector::MergeFrom(
          from._internal_int64toindex());
      break;
    }
    case MAP_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DictVectorizer::CopyFrom(const DictVectorizer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreML.Specification.DictVectorizer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DictVectorizer::IsInitialized() const {
  return true;
}

void DictVectorizer::InternalSwap(DictVectorizer* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.Map_, other->_impl_.Map_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata DictVectorizer::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_getter, &descriptor_table_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto_once,
      file_level_metadata_contrib_2flibs_2fcoreml_2fDictVectorizer_2eproto[0]);
}
// Yandex-specific extension
TProtoStringType DictVectorizer::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void DictVectorizer::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void DictVectorizer::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::CoreML::Specification::DictVectorizer::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (HasstringToIndex()) {
    out << sep;
    out << "\"stringToIndex\":";
    GetstringToIndex().PrintJSON(out);
    sep = ",";
  }
  if (Hasint64ToIndex()) {
    out << sep;
    out << "\"int64ToIndex\":";
    Getint64ToIndex().PrintJSON(out);
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// @@protoc_insertion_point(namespace_scope)
}  // namespace Specification
}  // namespace CoreML
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CoreML::Specification::DictVectorizer*
Arena::CreateMaybeMessage< ::CoreML::Specification::DictVectorizer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CoreML::Specification::DictVectorizer >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// Yandex debug output extension
template<>
void Out< ::CoreML::Specification::DictVectorizer>(IOutputStream& out, const ::CoreML::Specification::DictVectorizer& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
