// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/coreml/GLMClassifier.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022005 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include"contrib/libs/coreml/DataStructures.pb.h"
#include <google/protobuf/json_util.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto {
  static const ::arc_ui32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto;
namespace CoreML {
namespace Specification {
class GLMClassifier;
struct GLMClassifierDefaultTypeInternal;
extern GLMClassifierDefaultTypeInternal _GLMClassifier_default_instance_;
class GLMClassifier_DoubleArray;
struct GLMClassifier_DoubleArrayDefaultTypeInternal;
extern GLMClassifier_DoubleArrayDefaultTypeInternal _GLMClassifier_DoubleArray_default_instance_;
}  // namespace Specification
}  // namespace CoreML
PROTOBUF_NAMESPACE_OPEN
template <>
::CoreML::Specification::GLMClassifier* Arena::CreateMaybeMessage<::CoreML::Specification::GLMClassifier>(Arena*);
template <>
::CoreML::Specification::GLMClassifier_DoubleArray* Arena::CreateMaybeMessage<::CoreML::Specification::GLMClassifier_DoubleArray>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace CoreML {
namespace Specification {
enum GLMClassifier_PostEvaluationTransform : int {
  GLMClassifier_PostEvaluationTransform_Logit = 0,
  GLMClassifier_PostEvaluationTransform_Probit = 1,
  GLMClassifier_PostEvaluationTransform_GLMClassifier_PostEvaluationTransform_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::arc_i32>::min(),
  GLMClassifier_PostEvaluationTransform_GLMClassifier_PostEvaluationTransform_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::arc_i32>::max(),
};

bool GLMClassifier_PostEvaluationTransform_IsValid(int value);
constexpr GLMClassifier_PostEvaluationTransform GLMClassifier_PostEvaluationTransform_PostEvaluationTransform_MIN = static_cast<GLMClassifier_PostEvaluationTransform>(0);
constexpr GLMClassifier_PostEvaluationTransform GLMClassifier_PostEvaluationTransform_PostEvaluationTransform_MAX = static_cast<GLMClassifier_PostEvaluationTransform>(1);
constexpr int GLMClassifier_PostEvaluationTransform_PostEvaluationTransform_ARRAYSIZE = 1 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
GLMClassifier_PostEvaluationTransform_descriptor();
template <typename T>
const TProtoStringType& GLMClassifier_PostEvaluationTransform_Name(T value) {
  static_assert(std::is_same<T, GLMClassifier_PostEvaluationTransform>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PostEvaluationTransform_Name().");
  return GLMClassifier_PostEvaluationTransform_Name(static_cast<GLMClassifier_PostEvaluationTransform>(value));
}
template <>
inline const TProtoStringType& GLMClassifier_PostEvaluationTransform_Name(GLMClassifier_PostEvaluationTransform value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<GLMClassifier_PostEvaluationTransform_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool GLMClassifier_PostEvaluationTransform_Parse(y_absl::string_view name, GLMClassifier_PostEvaluationTransform* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GLMClassifier_PostEvaluationTransform>(
      GLMClassifier_PostEvaluationTransform_descriptor(), name, value);
}
enum GLMClassifier_ClassEncoding : int {
  GLMClassifier_ClassEncoding_ReferenceClass = 0,
  GLMClassifier_ClassEncoding_OneVsRest = 1,
  GLMClassifier_ClassEncoding_GLMClassifier_ClassEncoding_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::arc_i32>::min(),
  GLMClassifier_ClassEncoding_GLMClassifier_ClassEncoding_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::arc_i32>::max(),
};

bool GLMClassifier_ClassEncoding_IsValid(int value);
constexpr GLMClassifier_ClassEncoding GLMClassifier_ClassEncoding_ClassEncoding_MIN = static_cast<GLMClassifier_ClassEncoding>(0);
constexpr GLMClassifier_ClassEncoding GLMClassifier_ClassEncoding_ClassEncoding_MAX = static_cast<GLMClassifier_ClassEncoding>(1);
constexpr int GLMClassifier_ClassEncoding_ClassEncoding_ARRAYSIZE = 1 + 1;
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
GLMClassifier_ClassEncoding_descriptor();
template <typename T>
const TProtoStringType& GLMClassifier_ClassEncoding_Name(T value) {
  static_assert(std::is_same<T, GLMClassifier_ClassEncoding>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to ClassEncoding_Name().");
  return GLMClassifier_ClassEncoding_Name(static_cast<GLMClassifier_ClassEncoding>(value));
}
template <>
inline const TProtoStringType& GLMClassifier_ClassEncoding_Name(GLMClassifier_ClassEncoding value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfDenseEnum<GLMClassifier_ClassEncoding_descriptor,
                                                 0, 1>(
      static_cast<int>(value));
}
inline bool GLMClassifier_ClassEncoding_Parse(y_absl::string_view name, GLMClassifier_ClassEncoding* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<GLMClassifier_ClassEncoding>(
      GLMClassifier_ClassEncoding_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class GLMClassifier_DoubleArray :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CoreML.Specification.GLMClassifier.DoubleArray) */ {
 public:
  inline GLMClassifier_DoubleArray() : GLMClassifier_DoubleArray(nullptr) {}
  ~GLMClassifier_DoubleArray() override;
  explicit PROTOBUF_CONSTEXPR GLMClassifier_DoubleArray(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GLMClassifier_DoubleArray(const GLMClassifier_DoubleArray& from);
  GLMClassifier_DoubleArray(GLMClassifier_DoubleArray&& from) noexcept
    : GLMClassifier_DoubleArray() {
    *this = ::std::move(from);
  }

  inline GLMClassifier_DoubleArray& operator=(const GLMClassifier_DoubleArray& from) {
    CopyFrom(from);
    return *this;
  }
  inline GLMClassifier_DoubleArray& operator=(GLMClassifier_DoubleArray&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GLMClassifier_DoubleArray& default_instance() {
    return *internal_default_instance();
  }
  static inline const GLMClassifier_DoubleArray* internal_default_instance() {
    return reinterpret_cast<const GLMClassifier_DoubleArray*>(
               &_GLMClassifier_DoubleArray_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(GLMClassifier_DoubleArray& a, GLMClassifier_DoubleArray& b) {
    a.Swap(&b);
  }
  inline void Swap(GLMClassifier_DoubleArray* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GLMClassifier_DoubleArray* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GLMClassifier_DoubleArray* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GLMClassifier_DoubleArray>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GLMClassifier_DoubleArray& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GLMClassifier_DoubleArray& from) {
    GLMClassifier_DoubleArray::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GLMClassifier_DoubleArray* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "CoreML.Specification.GLMClassifier.DoubleArray";
  }
  protected:
  explicit GLMClassifier_DoubleArray(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // repeated double value = 1;
  int value_size() const;
  private:
  int _internal_value_size() const;

  public:
  void clear_value() ;
  double value(int index) const;
  void set_value(int index, double value);
  void add_value(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_value();

  private:
  double _internal_value(int index) const;
  void _internal_add_value(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_value() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_value();

  public:
  // Yandex cpp-styleguide extension
  inline size_t valueSize() const { return (size_t)value_size(); }
  inline void Clearvalue() { clear_value(); }
  inline double Getvalue(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return value(_index); }
  inline void Setvalue(size_t _index, double value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_value(_index, value); }
  inline void Addvalue(double value) { add_value(value); }
  inline double get_idx_value(int _index) const { return value(_index); }
  inline const ::google::protobuf::RepeatedField< double >&
      get_arr_value() const { return value(); }
  inline const ::google::protobuf::RepeatedField< double >&
      Getvalue() const { return value(); }
  inline ::google::protobuf::RepeatedField< double >*
      Mutablevalue() { return mutable_value(); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<GLMClassifier_DoubleArray> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<GLMClassifier_DoubleArray>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:CoreML.Specification.GLMClassifier.DoubleArray)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> value_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto;
};// -------------------------------------------------------------------

class GLMClassifier :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CoreML.Specification.GLMClassifier) */ {
 public:
  inline GLMClassifier() : GLMClassifier(nullptr) {}
  ~GLMClassifier() override;
  explicit PROTOBUF_CONSTEXPR GLMClassifier(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GLMClassifier(const GLMClassifier& from);
  GLMClassifier(GLMClassifier&& from) noexcept
    : GLMClassifier() {
    *this = ::std::move(from);
  }

  inline GLMClassifier& operator=(const GLMClassifier& from) {
    CopyFrom(from);
    return *this;
  }
  inline GLMClassifier& operator=(GLMClassifier&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GLMClassifier& default_instance() {
    return *internal_default_instance();
  }
  enum ClassLabelsCase {
    kStringClassLabels = 100,
    kInt64ClassLabels = 101,
    CLASSLABELS_NOT_SET = 0,
  };

  static inline const GLMClassifier* internal_default_instance() {
    return reinterpret_cast<const GLMClassifier*>(
               &_GLMClassifier_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GLMClassifier& a, GLMClassifier& b) {
    a.Swap(&b);
  }
  inline void Swap(GLMClassifier* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GLMClassifier* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GLMClassifier* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GLMClassifier>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GLMClassifier& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GLMClassifier& from) {
    GLMClassifier::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GLMClassifier* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "CoreML.Specification.GLMClassifier";
  }
  protected:
  explicit GLMClassifier(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef GLMClassifier_DoubleArray DoubleArray;

  using PostEvaluationTransform = GLMClassifier_PostEvaluationTransform;
  static constexpr PostEvaluationTransform Logit = GLMClassifier_PostEvaluationTransform_Logit;
  static constexpr PostEvaluationTransform Probit = GLMClassifier_PostEvaluationTransform_Probit;
  static inline bool PostEvaluationTransform_IsValid(int value) {
    return GLMClassifier_PostEvaluationTransform_IsValid(value);
  }
  static constexpr PostEvaluationTransform PostEvaluationTransform_MIN = GLMClassifier_PostEvaluationTransform_PostEvaluationTransform_MIN;
  static constexpr PostEvaluationTransform PostEvaluationTransform_MAX = GLMClassifier_PostEvaluationTransform_PostEvaluationTransform_MAX;
  static constexpr int PostEvaluationTransform_ARRAYSIZE = GLMClassifier_PostEvaluationTransform_PostEvaluationTransform_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PostEvaluationTransform_descriptor() {
    return GLMClassifier_PostEvaluationTransform_descriptor();
  }
  template <typename T>
  static inline const TProtoStringType& PostEvaluationTransform_Name(T value) {
    return GLMClassifier_PostEvaluationTransform_Name(value);
  }
  static inline bool PostEvaluationTransform_Parse(y_absl::string_view name, PostEvaluationTransform* value) {
    return GLMClassifier_PostEvaluationTransform_Parse(name, value);
  }

  using ClassEncoding = GLMClassifier_ClassEncoding;
  static constexpr ClassEncoding ReferenceClass = GLMClassifier_ClassEncoding_ReferenceClass;
  static constexpr ClassEncoding OneVsRest = GLMClassifier_ClassEncoding_OneVsRest;
  static inline bool ClassEncoding_IsValid(int value) {
    return GLMClassifier_ClassEncoding_IsValid(value);
  }
  static constexpr ClassEncoding ClassEncoding_MIN = GLMClassifier_ClassEncoding_ClassEncoding_MIN;
  static constexpr ClassEncoding ClassEncoding_MAX = GLMClassifier_ClassEncoding_ClassEncoding_MAX;
  static constexpr int ClassEncoding_ARRAYSIZE = GLMClassifier_ClassEncoding_ClassEncoding_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ClassEncoding_descriptor() {
    return GLMClassifier_ClassEncoding_descriptor();
  }
  template <typename T>
  static inline const TProtoStringType& ClassEncoding_Name(T value) {
    return GLMClassifier_ClassEncoding_Name(value);
  }
  static inline bool ClassEncoding_Parse(y_absl::string_view name, ClassEncoding* value) {
    return GLMClassifier_ClassEncoding_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kWeightsFieldNumber = 1,
    kOffsetFieldNumber = 2,
    kPostEvaluationTransformFieldNumber = 3,
    kClassEncodingFieldNumber = 4,
    kStringClassLabelsFieldNumber = 100,
    kInt64ClassLabelsFieldNumber = 101,
  };
  // repeated .CoreML.Specification.GLMClassifier.DoubleArray weights = 1;
  int weights_size() const;
  private:
  int _internal_weights_size() const;

  public:
  void clear_weights() ;
  ::CoreML::Specification::GLMClassifier_DoubleArray* mutable_weights(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >*
      mutable_weights();
  private:
  const ::CoreML::Specification::GLMClassifier_DoubleArray& _internal_weights(int index) const;
  ::CoreML::Specification::GLMClassifier_DoubleArray* _internal_add_weights();
  public:
  const ::CoreML::Specification::GLMClassifier_DoubleArray& weights(int index) const;
  ::CoreML::Specification::GLMClassifier_DoubleArray* add_weights();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >&
      weights() const;
  // repeated double offset = 2;
  int offset_size() const;
  private:
  int _internal_offset_size() const;

  public:
  void clear_offset() ;
  double offset(int index) const;
  void set_offset(int index, double value);
  void add_offset(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& offset() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_offset();

  private:
  double _internal_offset(int index) const;
  void _internal_add_offset(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_offset() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_offset();

  public:
  // .CoreML.Specification.GLMClassifier.PostEvaluationTransform postEvaluationTransform = 3;
  void clear_postevaluationtransform() ;
  ::CoreML::Specification::GLMClassifier_PostEvaluationTransform postevaluationtransform() const;
  void set_postevaluationtransform(::CoreML::Specification::GLMClassifier_PostEvaluationTransform value);

  private:
  ::CoreML::Specification::GLMClassifier_PostEvaluationTransform _internal_postevaluationtransform() const;
  void _internal_set_postevaluationtransform(::CoreML::Specification::GLMClassifier_PostEvaluationTransform value);

  public:
  // .CoreML.Specification.GLMClassifier.ClassEncoding classEncoding = 4;
  void clear_classencoding() ;
  ::CoreML::Specification::GLMClassifier_ClassEncoding classencoding() const;
  void set_classencoding(::CoreML::Specification::GLMClassifier_ClassEncoding value);

  private:
  ::CoreML::Specification::GLMClassifier_ClassEncoding _internal_classencoding() const;
  void _internal_set_classencoding(::CoreML::Specification::GLMClassifier_ClassEncoding value);

  public:
  // .CoreML.Specification.StringVector stringClassLabels = 100;
  bool has_stringclasslabels() const;
  private:
  bool _internal_has_stringclasslabels() const;

  public:
  void clear_stringclasslabels() ;
  const ::CoreML::Specification::StringVector& stringclasslabels() const;
  PROTOBUF_NODISCARD ::CoreML::Specification::StringVector* release_stringclasslabels();
  ::CoreML::Specification::StringVector* mutable_stringclasslabels();
  void set_allocated_stringclasslabels(::CoreML::Specification::StringVector* stringclasslabels);
  private:
  const ::CoreML::Specification::StringVector& _internal_stringclasslabels() const;
  ::CoreML::Specification::StringVector* _internal_mutable_stringclasslabels();
  public:
  void unsafe_arena_set_allocated_stringclasslabels(
      ::CoreML::Specification::StringVector* stringclasslabels);
  ::CoreML::Specification::StringVector* unsafe_arena_release_stringclasslabels();
  // .CoreML.Specification.Int64Vector int64ClassLabels = 101;
  bool has_int64classlabels() const;
  private:
  bool _internal_has_int64classlabels() const;

  public:
  void clear_int64classlabels() ;
  const ::CoreML::Specification::Int64Vector& int64classlabels() const;
  PROTOBUF_NODISCARD ::CoreML::Specification::Int64Vector* release_int64classlabels();
  ::CoreML::Specification::Int64Vector* mutable_int64classlabels();
  void set_allocated_int64classlabels(::CoreML::Specification::Int64Vector* int64classlabels);
  private:
  const ::CoreML::Specification::Int64Vector& _internal_int64classlabels() const;
  ::CoreML::Specification::Int64Vector* _internal_mutable_int64classlabels();
  public:
  void unsafe_arena_set_allocated_int64classlabels(
      ::CoreML::Specification::Int64Vector* int64classlabels);
  ::CoreML::Specification::Int64Vector* unsafe_arena_release_int64classlabels();
  void clear_ClassLabels();
  ClassLabelsCase ClassLabels_case() const;
  // Yandex cpp-styleguide extension
  inline size_t weightsSize() const { return (size_t)weights_size(); }
  inline void Clearweights() { clear_weights(); }
  inline const ::CoreML::Specification::GLMClassifier_DoubleArray& Getweights(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return weights(int(_index)); }
  inline ::CoreML::Specification::GLMClassifier_DoubleArray* Mutableweights(size_t _index) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return mutable_weights(int(_index)); }
  inline ::CoreML::Specification::GLMClassifier_DoubleArray* Addweights() { return add_weights(); }
  inline const ::CoreML::Specification::GLMClassifier_DoubleArray& get_idx_weights(int _index) const { return weights(_index); }
  inline const ::google::protobuf::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >&
      get_arr_weights() const { return weights(); }
  inline const ::google::protobuf::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >&
      Getweights() const { return weights(); }
  inline ::google::protobuf::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >*
      Mutableweights() { return mutable_weights(); }
  
  inline size_t offsetSize() const { return (size_t)offset_size(); }
  inline void Clearoffset() { clear_offset(); }
  inline double Getoffset(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return offset(_index); }
  inline void Setoffset(size_t _index, double value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_offset(_index, value); }
  inline void Addoffset(double value) { add_offset(value); }
  inline double get_idx_offset(int _index) const { return offset(_index); }
  inline const ::google::protobuf::RepeatedField< double >&
      get_arr_offset() const { return offset(); }
  inline const ::google::protobuf::RepeatedField< double >&
      Getoffset() const { return offset(); }
  inline ::google::protobuf::RepeatedField< double >*
      Mutableoffset() { return mutable_offset(); }
  
  inline void ClearpostEvaluationTransform() { clear_postevaluationtransform(); }
  inline ::CoreML::Specification::GLMClassifier_PostEvaluationTransform GetpostEvaluationTransform() const { return postevaluationtransform(); }
  inline void SetpostEvaluationTransform(::CoreML::Specification::GLMClassifier_PostEvaluationTransform value) { set_postevaluationtransform(value); }
  
  inline void ClearclassEncoding() { clear_classencoding(); }
  inline ::CoreML::Specification::GLMClassifier_ClassEncoding GetclassEncoding() const { return classencoding(); }
  inline void SetclassEncoding(::CoreML::Specification::GLMClassifier_ClassEncoding value) { set_classencoding(value); }
  
  inline bool HasstringClassLabels() const { return has_stringclasslabels(); }
  inline void ClearstringClassLabels() { clear_stringclasslabels(); }
  inline const ::CoreML::Specification::StringVector& GetstringClassLabels() const { return stringclasslabels(); }
  inline ::CoreML::Specification::StringVector* MutablestringClassLabels() { return mutable_stringclasslabels(); }
  
  inline bool Hasint64ClassLabels() const { return has_int64classlabels(); }
  inline void Clearint64ClassLabels() { clear_int64classlabels(); }
  inline const ::CoreML::Specification::Int64Vector& Getint64ClassLabels() const { return int64classlabels(); }
  inline ::CoreML::Specification::Int64Vector* Mutableint64ClassLabels() { return mutable_int64classlabels(); }
  
  ClassLabelsCase GetClassLabelsCase() const { return ClassLabels_case(); }
  void ClearClassLabels() { clear_ClassLabels(); }
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<GLMClassifier> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<GLMClassifier>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:CoreML.Specification.GLMClassifier)
 private:
  class _Internal;
  void set_has_stringclasslabels();
  void set_has_int64classlabels();

  inline bool has_ClassLabels() const;
  inline void clear_has_ClassLabels();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray > weights_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> offset_;
    int postevaluationtransform_;
    int classencoding_;
    union ClassLabelsUnion {
      constexpr ClassLabelsUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::CoreML::Specification::StringVector* stringclasslabels_;
      ::CoreML::Specification::Int64Vector* int64classlabels_;
    } ClassLabels_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::arc_ui32 _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// GLMClassifier_DoubleArray

// repeated double value = 1;
inline int GLMClassifier_DoubleArray::_internal_value_size() const {
  return _impl_.value_.size();
}
inline int GLMClassifier_DoubleArray::value_size() const {
  return _internal_value_size();
}
inline void GLMClassifier_DoubleArray::clear_value() {
  _impl_.value_.Clear();
}
inline double GLMClassifier_DoubleArray::value(int index) const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.DoubleArray.value)
  return _internal_value(index);
}
inline void GLMClassifier_DoubleArray::set_value(int index, double value) {
  _impl_.value_.Set(index, value);
  // @@protoc_insertion_point(field_set:CoreML.Specification.GLMClassifier.DoubleArray.value)
}
inline void GLMClassifier_DoubleArray::add_value(double value) {
  _internal_add_value(value);
  // @@protoc_insertion_point(field_add:CoreML.Specification.GLMClassifier.DoubleArray.value)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& GLMClassifier_DoubleArray::value() const {
  // @@protoc_insertion_point(field_list:CoreML.Specification.GLMClassifier.DoubleArray.value)
  return _internal_value();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* GLMClassifier_DoubleArray::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:CoreML.Specification.GLMClassifier.DoubleArray.value)
  return _internal_mutable_value();
}

inline double GLMClassifier_DoubleArray::_internal_value(int index) const {
  return _impl_.value_.Get(index);
}
inline void GLMClassifier_DoubleArray::_internal_add_value(double value) { _impl_.value_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& GLMClassifier_DoubleArray::_internal_value() const {
  return _impl_.value_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* GLMClassifier_DoubleArray::_internal_mutable_value() {
  return &_impl_.value_;
}

// -------------------------------------------------------------------

// GLMClassifier

// repeated .CoreML.Specification.GLMClassifier.DoubleArray weights = 1;
inline int GLMClassifier::_internal_weights_size() const {
  return _impl_.weights_.size();
}
inline int GLMClassifier::weights_size() const {
  return _internal_weights_size();
}
inline void GLMClassifier::clear_weights() {
  _impl_.weights_.Clear();
}
inline ::CoreML::Specification::GLMClassifier_DoubleArray* GLMClassifier::mutable_weights(int index) {
  // @@protoc_insertion_point(field_mutable:CoreML.Specification.GLMClassifier.weights)
  return _impl_.weights_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >*
GLMClassifier::mutable_weights() {
  // @@protoc_insertion_point(field_mutable_list:CoreML.Specification.GLMClassifier.weights)
  return &_impl_.weights_;
}
inline const ::CoreML::Specification::GLMClassifier_DoubleArray& GLMClassifier::_internal_weights(int index) const {
  return _impl_.weights_.Get(index);
}
inline const ::CoreML::Specification::GLMClassifier_DoubleArray& GLMClassifier::weights(int index) const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.weights)
  return _internal_weights(index);
}
inline ::CoreML::Specification::GLMClassifier_DoubleArray* GLMClassifier::_internal_add_weights() {
  return _impl_.weights_.Add();
}
inline ::CoreML::Specification::GLMClassifier_DoubleArray* GLMClassifier::add_weights() {
  ::CoreML::Specification::GLMClassifier_DoubleArray* _add = _internal_add_weights();
  // @@protoc_insertion_point(field_add:CoreML.Specification.GLMClassifier.weights)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::CoreML::Specification::GLMClassifier_DoubleArray >&
GLMClassifier::weights() const {
  // @@protoc_insertion_point(field_list:CoreML.Specification.GLMClassifier.weights)
  return _impl_.weights_;
}

// repeated double offset = 2;
inline int GLMClassifier::_internal_offset_size() const {
  return _impl_.offset_.size();
}
inline int GLMClassifier::offset_size() const {
  return _internal_offset_size();
}
inline void GLMClassifier::clear_offset() {
  _impl_.offset_.Clear();
}
inline double GLMClassifier::offset(int index) const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.offset)
  return _internal_offset(index);
}
inline void GLMClassifier::set_offset(int index, double value) {
  _impl_.offset_.Set(index, value);
  // @@protoc_insertion_point(field_set:CoreML.Specification.GLMClassifier.offset)
}
inline void GLMClassifier::add_offset(double value) {
  _internal_add_offset(value);
  // @@protoc_insertion_point(field_add:CoreML.Specification.GLMClassifier.offset)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& GLMClassifier::offset() const {
  // @@protoc_insertion_point(field_list:CoreML.Specification.GLMClassifier.offset)
  return _internal_offset();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* GLMClassifier::mutable_offset() {
  // @@protoc_insertion_point(field_mutable_list:CoreML.Specification.GLMClassifier.offset)
  return _internal_mutable_offset();
}

inline double GLMClassifier::_internal_offset(int index) const {
  return _impl_.offset_.Get(index);
}
inline void GLMClassifier::_internal_add_offset(double value) { _impl_.offset_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& GLMClassifier::_internal_offset() const {
  return _impl_.offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* GLMClassifier::_internal_mutable_offset() {
  return &_impl_.offset_;
}

// .CoreML.Specification.GLMClassifier.PostEvaluationTransform postEvaluationTransform = 3;
inline void GLMClassifier::clear_postevaluationtransform() {
  _impl_.postevaluationtransform_ = 0;
}
inline ::CoreML::Specification::GLMClassifier_PostEvaluationTransform GLMClassifier::postevaluationtransform() const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.postEvaluationTransform)
  return _internal_postevaluationtransform();
}
inline void GLMClassifier::set_postevaluationtransform(::CoreML::Specification::GLMClassifier_PostEvaluationTransform value) {
   _internal_set_postevaluationtransform(value);
  // @@protoc_insertion_point(field_set:CoreML.Specification.GLMClassifier.postEvaluationTransform)
}
inline ::CoreML::Specification::GLMClassifier_PostEvaluationTransform GLMClassifier::_internal_postevaluationtransform() const {
  return static_cast<::CoreML::Specification::GLMClassifier_PostEvaluationTransform>(_impl_.postevaluationtransform_);
}
inline void GLMClassifier::_internal_set_postevaluationtransform(::CoreML::Specification::GLMClassifier_PostEvaluationTransform value) {
  ;
  _impl_.postevaluationtransform_ = value;
}

// .CoreML.Specification.GLMClassifier.ClassEncoding classEncoding = 4;
inline void GLMClassifier::clear_classencoding() {
  _impl_.classencoding_ = 0;
}
inline ::CoreML::Specification::GLMClassifier_ClassEncoding GLMClassifier::classencoding() const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.classEncoding)
  return _internal_classencoding();
}
inline void GLMClassifier::set_classencoding(::CoreML::Specification::GLMClassifier_ClassEncoding value) {
   _internal_set_classencoding(value);
  // @@protoc_insertion_point(field_set:CoreML.Specification.GLMClassifier.classEncoding)
}
inline ::CoreML::Specification::GLMClassifier_ClassEncoding GLMClassifier::_internal_classencoding() const {
  return static_cast<::CoreML::Specification::GLMClassifier_ClassEncoding>(_impl_.classencoding_);
}
inline void GLMClassifier::_internal_set_classencoding(::CoreML::Specification::GLMClassifier_ClassEncoding value) {
  ;
  _impl_.classencoding_ = value;
}

// .CoreML.Specification.StringVector stringClassLabels = 100;
inline bool GLMClassifier::has_stringclasslabels() const {
  return ClassLabels_case() == kStringClassLabels;
}
inline bool GLMClassifier::_internal_has_stringclasslabels() const {
  return ClassLabels_case() == kStringClassLabels;
}
inline void GLMClassifier::set_has_stringclasslabels() {
  _impl_._oneof_case_[0] = kStringClassLabels;
}
inline ::CoreML::Specification::StringVector* GLMClassifier::release_stringclasslabels() {
  // @@protoc_insertion_point(field_release:CoreML.Specification.GLMClassifier.stringClassLabels)
  if (ClassLabels_case() == kStringClassLabels) {
    clear_has_ClassLabels();
    ::CoreML::Specification::StringVector* temp = _impl_.ClassLabels_.stringclasslabels_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.ClassLabels_.stringclasslabels_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::CoreML::Specification::StringVector& GLMClassifier::_internal_stringclasslabels() const {
  return ClassLabels_case() == kStringClassLabels
      ? *_impl_.ClassLabels_.stringclasslabels_
      : reinterpret_cast< ::CoreML::Specification::StringVector&>(::CoreML::Specification::_StringVector_default_instance_);
}
inline const ::CoreML::Specification::StringVector& GLMClassifier::stringclasslabels() const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.stringClassLabels)
  return _internal_stringclasslabels();
}
inline ::CoreML::Specification::StringVector* GLMClassifier::unsafe_arena_release_stringclasslabels() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CoreML.Specification.GLMClassifier.stringClassLabels)
  if (ClassLabels_case() == kStringClassLabels) {
    clear_has_ClassLabels();
    ::CoreML::Specification::StringVector* temp = _impl_.ClassLabels_.stringclasslabels_;
    _impl_.ClassLabels_.stringclasslabels_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GLMClassifier::unsafe_arena_set_allocated_stringclasslabels(::CoreML::Specification::StringVector* stringclasslabels) {
  clear_ClassLabels();
  if (stringclasslabels) {
    set_has_stringclasslabels();
    _impl_.ClassLabels_.stringclasslabels_ = stringclasslabels;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CoreML.Specification.GLMClassifier.stringClassLabels)
}
inline ::CoreML::Specification::StringVector* GLMClassifier::_internal_mutable_stringclasslabels() {
  if (ClassLabels_case() != kStringClassLabels) {
    clear_ClassLabels();
    set_has_stringclasslabels();
    _impl_.ClassLabels_.stringclasslabels_ = CreateMaybeMessage< ::CoreML::Specification::StringVector >(GetArenaForAllocation());
  }
  return _impl_.ClassLabels_.stringclasslabels_;
}
inline ::CoreML::Specification::StringVector* GLMClassifier::mutable_stringclasslabels() {
  ::CoreML::Specification::StringVector* _msg = _internal_mutable_stringclasslabels();
  // @@protoc_insertion_point(field_mutable:CoreML.Specification.GLMClassifier.stringClassLabels)
  return _msg;
}

// .CoreML.Specification.Int64Vector int64ClassLabels = 101;
inline bool GLMClassifier::has_int64classlabels() const {
  return ClassLabels_case() == kInt64ClassLabels;
}
inline bool GLMClassifier::_internal_has_int64classlabels() const {
  return ClassLabels_case() == kInt64ClassLabels;
}
inline void GLMClassifier::set_has_int64classlabels() {
  _impl_._oneof_case_[0] = kInt64ClassLabels;
}
inline ::CoreML::Specification::Int64Vector* GLMClassifier::release_int64classlabels() {
  // @@protoc_insertion_point(field_release:CoreML.Specification.GLMClassifier.int64ClassLabels)
  if (ClassLabels_case() == kInt64ClassLabels) {
    clear_has_ClassLabels();
    ::CoreML::Specification::Int64Vector* temp = _impl_.ClassLabels_.int64classlabels_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.ClassLabels_.int64classlabels_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::CoreML::Specification::Int64Vector& GLMClassifier::_internal_int64classlabels() const {
  return ClassLabels_case() == kInt64ClassLabels
      ? *_impl_.ClassLabels_.int64classlabels_
      : reinterpret_cast< ::CoreML::Specification::Int64Vector&>(::CoreML::Specification::_Int64Vector_default_instance_);
}
inline const ::CoreML::Specification::Int64Vector& GLMClassifier::int64classlabels() const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.GLMClassifier.int64ClassLabels)
  return _internal_int64classlabels();
}
inline ::CoreML::Specification::Int64Vector* GLMClassifier::unsafe_arena_release_int64classlabels() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CoreML.Specification.GLMClassifier.int64ClassLabels)
  if (ClassLabels_case() == kInt64ClassLabels) {
    clear_has_ClassLabels();
    ::CoreML::Specification::Int64Vector* temp = _impl_.ClassLabels_.int64classlabels_;
    _impl_.ClassLabels_.int64classlabels_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void GLMClassifier::unsafe_arena_set_allocated_int64classlabels(::CoreML::Specification::Int64Vector* int64classlabels) {
  clear_ClassLabels();
  if (int64classlabels) {
    set_has_int64classlabels();
    _impl_.ClassLabels_.int64classlabels_ = int64classlabels;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CoreML.Specification.GLMClassifier.int64ClassLabels)
}
inline ::CoreML::Specification::Int64Vector* GLMClassifier::_internal_mutable_int64classlabels() {
  if (ClassLabels_case() != kInt64ClassLabels) {
    clear_ClassLabels();
    set_has_int64classlabels();
    _impl_.ClassLabels_.int64classlabels_ = CreateMaybeMessage< ::CoreML::Specification::Int64Vector >(GetArenaForAllocation());
  }
  return _impl_.ClassLabels_.int64classlabels_;
}
inline ::CoreML::Specification::Int64Vector* GLMClassifier::mutable_int64classlabels() {
  ::CoreML::Specification::Int64Vector* _msg = _internal_mutable_int64classlabels();
  // @@protoc_insertion_point(field_mutable:CoreML.Specification.GLMClassifier.int64ClassLabels)
  return _msg;
}

inline bool GLMClassifier::has_ClassLabels() const {
  return ClassLabels_case() != CLASSLABELS_NOT_SET;
}
inline void GLMClassifier::clear_has_ClassLabels() {
  _impl_._oneof_case_[0] = CLASSLABELS_NOT_SET;
}
inline GLMClassifier::ClassLabelsCase GLMClassifier::ClassLabels_case() const {
  return GLMClassifier::ClassLabelsCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Specification
}  // namespace CoreML


PROTOBUF_NAMESPACE_OPEN

template <>
struct is_proto_enum<::CoreML::Specification::GLMClassifier_PostEvaluationTransform> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::CoreML::Specification::GLMClassifier_PostEvaluationTransform>() {
  return ::CoreML::Specification::GLMClassifier_PostEvaluationTransform_descriptor();
}
template <>
struct is_proto_enum<::CoreML::Specification::GLMClassifier_ClassEncoding> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::CoreML::Specification::GLMClassifier_ClassEncoding>() {
  return ::CoreML::Specification::GLMClassifier_ClassEncoding_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_contrib_2flibs_2fcoreml_2fGLMClassifier_2eproto_2epb_2eh
