// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/coreml/Scaler.proto

#include "contrib/libs/coreml/Scaler.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include <google/protobuf/messagext.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace CoreML {
namespace Specification {
PROTOBUF_CONSTEXPR Scaler::Scaler(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.shiftvalue_)*/ {}

  , /*decltype(_impl_.scalevalue_)*/ {}

  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ScalerDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ScalerDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ScalerDefaultTypeInternal() {}
  union {
    Scaler _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ScalerDefaultTypeInternal _Scaler_default_instance_;
}  // namespace Specification
}  // namespace CoreML
static ::_pb::Metadata file_level_metadata_contrib_2flibs_2fcoreml_2fScaler_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_contrib_2flibs_2fcoreml_2fScaler_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_contrib_2flibs_2fcoreml_2fScaler_2eproto = nullptr;
const ::arc_ui32 TableStruct_contrib_2flibs_2fcoreml_2fScaler_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::Scaler, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::Scaler, _impl_.shiftvalue_),
    PROTOBUF_FIELD_OFFSET(::CoreML::Specification::Scaler, _impl_.scalevalue_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::CoreML::Specification::Scaler)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::CoreML::Specification::_Scaler_default_instance_._instance,
};
const char descriptor_table_protodef_contrib_2flibs_2fcoreml_2fScaler_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n contrib/libs/coreml/Scaler.proto\022\024Core"
    "ML.Specification\"0\n\006Scaler\022\022\n\nshiftValue"
    "\030\001 \003(\001\022\022\n\nscaleValue\030\002 \003(\001b\006proto3"
};
static ::y_absl::once_flag descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto = {
    false,
    false,
    114,
    descriptor_table_protodef_contrib_2flibs_2fcoreml_2fScaler_2eproto,
    "contrib/libs/coreml/Scaler.proto",
    &descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_contrib_2flibs_2fcoreml_2fScaler_2eproto::offsets,
    file_level_metadata_contrib_2flibs_2fcoreml_2fScaler_2eproto,
    file_level_enum_descriptors_contrib_2flibs_2fcoreml_2fScaler_2eproto,
    file_level_service_descriptors_contrib_2flibs_2fcoreml_2fScaler_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto_getter() {
  return &descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_contrib_2flibs_2fcoreml_2fScaler_2eproto(&descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto);
namespace CoreML {
namespace Specification {
// ===================================================================

class Scaler::_Internal {
 public:
};

Scaler::Scaler(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CoreML.Specification.Scaler)
}
Scaler::Scaler(const Scaler& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Scaler* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.shiftvalue_) { from._impl_.shiftvalue_ }

    , decltype(_impl_.scalevalue_) { from._impl_.scalevalue_ }

    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:CoreML.Specification.Scaler)
}

inline void Scaler::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.shiftvalue_) { arena }

    , decltype(_impl_.scalevalue_) { arena }

    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Scaler::~Scaler() {
  // @@protoc_insertion_point(destructor:CoreML.Specification.Scaler)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Scaler::SharedDtor() {
  Y_ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.shiftvalue_.~RepeatedField();
  _impl_.scalevalue_.~RepeatedField();
}

void Scaler::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Scaler::Clear() {
// @@protoc_insertion_point(message_clear_start:CoreML.Specification.Scaler)
  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.shiftvalue_.Clear();
  _impl_.scalevalue_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Scaler::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::arc_ui32 tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated double shiftValue = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_shiftvalue(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::uint8_t>(tag) == 9) {
          _internal_add_shiftvalue(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      // repeated double scaleValue = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_scalevalue(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::uint8_t>(tag) == 17) {
          _internal_add_scalevalue(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Scaler::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:CoreML.Specification.Scaler)
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated double shiftValue = 1;
  if (this->_internal_shiftvalue_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_shiftvalue(), target);
  }

  // repeated double scaleValue = 2;
  if (this->_internal_scalevalue_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_scalevalue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CoreML.Specification.Scaler)
  return target;
}

::size_t Scaler::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CoreML.Specification.Scaler)
  ::size_t total_size = 0;

  ::arc_ui32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double shiftValue = 1;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_shiftvalue_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<arc_i32>(data_size))
    ;
    total_size += tag_size + data_size;
  }

  // repeated double scaleValue = 2;
  {
    std::size_t data_size = std::size_t{8} *
        ::_pbi::FromIntSize(this->_internal_scalevalue_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<arc_i32>(data_size))
    ;
    total_size += tag_size + data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Scaler::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Scaler::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Scaler::GetClassData() const { return &_class_data_; }


void Scaler::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Scaler*>(&to_msg);
  auto& from = static_cast<const Scaler&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:CoreML.Specification.Scaler)
  Y_ABSL_DCHECK_NE(&from, _this);
  ::arc_ui32 cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.shiftvalue_.MergeFrom(from._impl_.shiftvalue_);
  _this->_impl_.scalevalue_.MergeFrom(from._impl_.scalevalue_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Scaler::CopyFrom(const Scaler& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CoreML.Specification.Scaler)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Scaler::IsInitialized() const {
  return true;
}

void Scaler::InternalSwap(Scaler* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.shiftvalue_.InternalSwap(&other->_impl_.shiftvalue_);
  _impl_.scalevalue_.InternalSwap(&other->_impl_.scalevalue_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Scaler::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto_getter, &descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto_once,
      file_level_metadata_contrib_2flibs_2fcoreml_2fScaler_2eproto[0]);
}
// Yandex-specific extension
TProtoStringType Scaler::ShortUtf8DebugString() const {
    return ::ShortUtf8DebugString(*this);
}
// End of Yandex-specific extension
// Yandex-specific extension
void Scaler::Save(IOutputStream* output) const {
    ::Save(output, static_cast<const ::google::protobuf::Message&>(*this));
}
void Scaler::Load(IInputStream* input) {
    ::Load(input, static_cast<::google::protobuf::Message&>(*this));
}
// End of Yandex-specific extension
// Yandex JSON extension
inline void ::CoreML::Specification::Scaler::PrintJSON(IOutputStream& out) const {
  out << '{';
  const char* sep = "";
  if (shiftValueSize() > 0) {
    out << sep;
    out << "\"shiftValue\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < shiftValueSize(); ++_index) {
        out << separator;
        out << GetshiftValue(_index);
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  if (scaleValueSize() > 0) {
    out << sep;
    out << "\"scaleValue\":";
    out << '[';
    {
      const char* separator = "";
      for (size_t _index = 0; _index < scaleValueSize(); ++_index) {
        out << separator;
        out << GetscaleValue(_index);
        separator = ",";
      }
    }
    out << ']';
    sep = ",";
  }
  out << '}';
}
// End of Yandex JSON extension
// @@protoc_insertion_point(namespace_scope)
}  // namespace Specification
}  // namespace CoreML
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::CoreML::Specification::Scaler*
Arena::CreateMaybeMessage< ::CoreML::Specification::Scaler >(Arena* arena) {
  return Arena::CreateMessageInternal< ::CoreML::Specification::Scaler >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// Yandex debug output extension
template<>
void Out< ::CoreML::Specification::Scaler>(IOutputStream& out, const ::CoreML::Specification::Scaler& msg) {
    out << "{ " << msg.ShortUtf8DebugString() << " }";
}
// End of Yandex debug output extension
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
