// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contrib/libs/coreml/Scaler.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contrib_2flibs_2fcoreml_2fScaler_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_contrib_2flibs_2fcoreml_2fScaler_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022005 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include <google/protobuf/json_util.h>
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_contrib_2flibs_2fcoreml_2fScaler_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contrib_2flibs_2fcoreml_2fScaler_2eproto {
  static const ::arc_ui32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_contrib_2flibs_2fcoreml_2fScaler_2eproto;
namespace CoreML {
namespace Specification {
class Scaler;
struct ScalerDefaultTypeInternal;
extern ScalerDefaultTypeInternal _Scaler_default_instance_;
}  // namespace Specification
}  // namespace CoreML
PROTOBUF_NAMESPACE_OPEN
template <>
::CoreML::Specification::Scaler* Arena::CreateMaybeMessage<::CoreML::Specification::Scaler>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace CoreML {
namespace Specification {

// ===================================================================


// -------------------------------------------------------------------

class Scaler :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CoreML.Specification.Scaler) */ {
 public:
  inline Scaler() : Scaler(nullptr) {}
  ~Scaler() override;
  explicit PROTOBUF_CONSTEXPR Scaler(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Scaler(const Scaler& from);
  Scaler(Scaler&& from) noexcept
    : Scaler() {
    *this = ::std::move(from);
  }

  inline Scaler& operator=(const Scaler& from) {
    CopyFrom(from);
    return *this;
  }
  inline Scaler& operator=(Scaler&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Scaler& default_instance() {
    return *internal_default_instance();
  }
  static inline const Scaler* internal_default_instance() {
    return reinterpret_cast<const Scaler*>(
               &_Scaler_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Scaler& a, Scaler& b) {
    a.Swap(&b);
  }
  inline void Swap(Scaler* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Scaler* other) {
    if (other == this) return;
    Y_ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Scaler* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Scaler>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Scaler& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Scaler& from) {
    Scaler::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Scaler* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::y_absl::string_view FullMessageName() {
    return "CoreML.Specification.Scaler";
  }
  protected:
  explicit Scaler(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShiftValueFieldNumber = 1,
    kScaleValueFieldNumber = 2,
  };
  // repeated double shiftValue = 1;
  int shiftvalue_size() const;
  private:
  int _internal_shiftvalue_size() const;

  public:
  void clear_shiftvalue() ;
  double shiftvalue(int index) const;
  void set_shiftvalue(int index, double value);
  void add_shiftvalue(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& shiftvalue() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_shiftvalue();

  private:
  double _internal_shiftvalue(int index) const;
  void _internal_add_shiftvalue(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_shiftvalue() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_shiftvalue();

  public:
  // repeated double scaleValue = 2;
  int scalevalue_size() const;
  private:
  int _internal_scalevalue_size() const;

  public:
  void clear_scalevalue() ;
  double scalevalue(int index) const;
  void set_scalevalue(int index, double value);
  void add_scalevalue(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& scalevalue() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* mutable_scalevalue();

  private:
  double _internal_scalevalue(int index) const;
  void _internal_add_scalevalue(double value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& _internal_scalevalue() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* _internal_mutable_scalevalue();

  public:
  // Yandex cpp-styleguide extension
  inline size_t shiftValueSize() const { return (size_t)shiftvalue_size(); }
  inline void ClearshiftValue() { clear_shiftvalue(); }
  inline double GetshiftValue(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return shiftvalue(_index); }
  inline void SetshiftValue(size_t _index, double value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_shiftvalue(_index, value); }
  inline void AddshiftValue(double value) { add_shiftvalue(value); }
  inline double get_idx_shiftvalue(int _index) const { return shiftvalue(_index); }
  inline const ::google::protobuf::RepeatedField< double >&
      get_arr_shiftvalue() const { return shiftvalue(); }
  inline const ::google::protobuf::RepeatedField< double >&
      GetshiftValue() const { return shiftvalue(); }
  inline ::google::protobuf::RepeatedField< double >*
      MutableshiftValue() { return mutable_shiftvalue(); }
  
  inline size_t scaleValueSize() const { return (size_t)scalevalue_size(); }
  inline void ClearscaleValue() { clear_scalevalue(); }
  inline double GetscaleValue(size_t _index) const {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); return scalevalue(_index); }
  inline void SetscaleValue(size_t _index, double value) {Y_ASSERT(_index < static_cast<size_t>(::Max<int>())); set_scalevalue(_index, value); }
  inline void AddscaleValue(double value) { add_scalevalue(value); }
  inline double get_idx_scalevalue(int _index) const { return scalevalue(_index); }
  inline const ::google::protobuf::RepeatedField< double >&
      get_arr_scalevalue() const { return scalevalue(); }
  inline const ::google::protobuf::RepeatedField< double >&
      GetscaleValue() const { return scalevalue(); }
  inline ::google::protobuf::RepeatedField< double >*
      MutablescaleValue() { return mutable_scalevalue(); }
  
  TProtoStringType ShortUtf8DebugString() const;
  void PrintJSON(IOutputStream&) const override;
  ::google::protobuf::io::TAsJSON<Scaler> AsJSON() const {
      return ::google::protobuf::io::TAsJSON<Scaler>(*this);
  }
  void Save(IOutputStream* output) const;
  void Load(IInputStream* input);
  // End of Yandex-specific extension
  // @@protoc_insertion_point(class_scope:CoreML.Specification.Scaler)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> shiftvalue_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField<double> scalevalue_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contrib_2flibs_2fcoreml_2fScaler_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Scaler

// repeated double shiftValue = 1;
inline int Scaler::_internal_shiftvalue_size() const {
  return _impl_.shiftvalue_.size();
}
inline int Scaler::shiftvalue_size() const {
  return _internal_shiftvalue_size();
}
inline void Scaler::clear_shiftvalue() {
  _impl_.shiftvalue_.Clear();
}
inline double Scaler::shiftvalue(int index) const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.Scaler.shiftValue)
  return _internal_shiftvalue(index);
}
inline void Scaler::set_shiftvalue(int index, double value) {
  _impl_.shiftvalue_.Set(index, value);
  // @@protoc_insertion_point(field_set:CoreML.Specification.Scaler.shiftValue)
}
inline void Scaler::add_shiftvalue(double value) {
  _internal_add_shiftvalue(value);
  // @@protoc_insertion_point(field_add:CoreML.Specification.Scaler.shiftValue)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& Scaler::shiftvalue() const {
  // @@protoc_insertion_point(field_list:CoreML.Specification.Scaler.shiftValue)
  return _internal_shiftvalue();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* Scaler::mutable_shiftvalue() {
  // @@protoc_insertion_point(field_mutable_list:CoreML.Specification.Scaler.shiftValue)
  return _internal_mutable_shiftvalue();
}

inline double Scaler::_internal_shiftvalue(int index) const {
  return _impl_.shiftvalue_.Get(index);
}
inline void Scaler::_internal_add_shiftvalue(double value) { _impl_.shiftvalue_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& Scaler::_internal_shiftvalue() const {
  return _impl_.shiftvalue_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* Scaler::_internal_mutable_shiftvalue() {
  return &_impl_.shiftvalue_;
}

// repeated double scaleValue = 2;
inline int Scaler::_internal_scalevalue_size() const {
  return _impl_.scalevalue_.size();
}
inline int Scaler::scalevalue_size() const {
  return _internal_scalevalue_size();
}
inline void Scaler::clear_scalevalue() {
  _impl_.scalevalue_.Clear();
}
inline double Scaler::scalevalue(int index) const {
  // @@protoc_insertion_point(field_get:CoreML.Specification.Scaler.scaleValue)
  return _internal_scalevalue(index);
}
inline void Scaler::set_scalevalue(int index, double value) {
  _impl_.scalevalue_.Set(index, value);
  // @@protoc_insertion_point(field_set:CoreML.Specification.Scaler.scaleValue)
}
inline void Scaler::add_scalevalue(double value) {
  _internal_add_scalevalue(value);
  // @@protoc_insertion_point(field_add:CoreML.Specification.Scaler.scaleValue)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& Scaler::scalevalue() const {
  // @@protoc_insertion_point(field_list:CoreML.Specification.Scaler.scaleValue)
  return _internal_scalevalue();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* Scaler::mutable_scalevalue() {
  // @@protoc_insertion_point(field_mutable_list:CoreML.Specification.Scaler.scaleValue)
  return _internal_mutable_scalevalue();
}

inline double Scaler::_internal_scalevalue(int index) const {
  return _impl_.scalevalue_.Get(index);
}
inline void Scaler::_internal_add_scalevalue(double value) { _impl_.scalevalue_.Add(value); }
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>& Scaler::_internal_scalevalue() const {
  return _impl_.scalevalue_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<double>* Scaler::_internal_mutable_scalevalue() {
  return &_impl_.scalevalue_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Specification
}  // namespace CoreML


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_contrib_2flibs_2fcoreml_2fScaler_2eproto_2epb_2eh
